### ISSUE TITLE
[Q] reload with consent, should opt-in/scripts trigger ?

### ISSUE THREAD

**Issue by birdspider** [KIProtect/klaro#101]
I tested klaro embedded in a webpack harness and everyhing seems to work ok, 

except that I expected the `script[type=opt-in]` functionality to persist on reloads.
It triggers after consent was given (+ok button) but subsequent reloads do not touch `script[opt-in]` tags.

even explicit calling of 
```
  const klaro = renderKlaro(config)
  // getManager(config).applyConsents()
  klaro.props.manager.applyConsents()
```

does not change that.

Is this by design or a bug. I could not find any documentation of `[type=opt-in]` regarding subsequent visits.

**Comment by jaller94** [comment]
What are the steps I have to take to reproduce this?
If you think that your config matters, could you upload it to https://gist.github.com/ and link it here?
Do you have a small, public repo where this is reproducible?

**Comment by birdspider** [comment]
nevermind, I seems to work now (stale webpack?), so "activating" opt-in after reload is indeed what should happen.

thx

**Comment by jaller94** [comment]
Happy to help, feel free to re-open the issue if it happens again or ask other questions in new issues.
