### ISSUE TITLE
Don't show "Toggle all apps" if there is only one app

### ISSUE THREAD

**Issue by dmgroom** [KIProtect/klaro#106]
If there is only one app which Klaro manages then it does not seem appropriate to also show the "toggle all apps"  button in the consent manager.

It would be good if there was either an option to not show the "toggle all apps button", or if there was only one app then the "toggle all apps button" was automatically not shown.

**Comment by jaller94** [comment]
For others, this is the issue case. There should be at least two non-required items for this toggle to show up.

![Screenshot_2019-11-01 Klaro Consent Manager Utility(1)](https://user-images.githubusercontent.com/10872136/68029587-d1c3de00-fcb7-11e9-9b71-6aefaa2b2a42.png)
