### ISSUE TITLE
Link in the cookie-notice window

### ISSUE THREAD

**Issue by astruzh** [kiprotect/klaro#116]
I try to find a way to add a link in the consentNotice. The normal a-tag will be nor rendering. Can you give me a workaround for it?

**Comment by jaller94** [comment]
This seems very similar to issue #76.

The translation and configuration strings may only include strings and `{placeholder}`s, no HTML or JSX code.

If you wan to build your own consent notice, you can find an example of `<strong>` being inserted to a placeholder here:
https://github.com/KIProtect/klaro/blob/561a2589ef2ec9bfb0082d544a65a318d20458a2/src/components/consent-notice.js#L64

**Comment by nussisworld** [comment]
Hi Jaller,
how can I work with consent-notice.js. I tried to change something inside this script, but nothing changed. Should I copy parts from it to klaro.js? Sorry, I am a beginner.

**Comment by adewes** [comment]
This is solved by the `htmlText` config option now.
