### ISSUE TITLE
File translations.yml not found

### ISSUE THREAD

**Issue by astruzh** [KIProtect/klaro#119]
Hello!
I found a description about how to work with a different translations in klaro. 
In the config.js line 40-43:
// You can overwrite existing translations and add translations for your
// app descriptions and purposes. See `src/translations.yml` for a full
// list of translations that can be overwritten:
// https://github.com/DPKit/klaro/blob/master/src/translations.yml

But I van't find this file translations.yml
Can you fix it or change the description?

Thank you!

**Comment by jaller94** [comment]
Thanks for pointing out that these links were outdated.

As we got more translations, the file got split into a folder of files per language:
https://github.com/KIProtect/klaro/tree/master/src/translations
