### ISSUE TITLE
How to support older browser like IE 9

### ISSUE THREAD

**Issue by mkkeck** [kiprotect/klaro#121]
Hello,

I like this cookie consent manager. But what do I need (polyfill, shims, addons), that Klaro will work on older browsers to.
I would support Android 4.x, older iOS (iPhone 6) and InternetExplorer 9, 10 and 11. My websites (for local community) is also used by persons with older hard- and software.

The normal build step (descriped in Readme) does not include required parts for older systems.
Example: Symbol, Map not defined, klaro.version unsupported, script.dataset (currentScript) null object ...

Regards
Michael

**Comment by jmartsch** [comment]
I also want to know that. It seems, that IE 11 has a problem with object.keys, which is being used.

**Comment by mkkeck** [comment]
I've done little work:
`npm install core-js` to include some dependencies like Map, Symbol and Array.functions.

In klaro.js (main src file) add:
```import 'core-js/es/array';
import 'core-js/es/map';
import 'core-js/es/symbol';
```

**Comment by mkkeck** [comment]
I think for supporting all actual used browsers by my vistors I have to write my own Cookie Consent Manager, based on Klaro.

**Comment by jmartsch** [comment]
Why should you write something own? Instead extending klaro would be a good thing.
An extra script with the needed polyfills for older browser would be good.
Oil.js is another good and free cookie consent manager.

**Comment by mkkeck** [comment]
> Why should you write something own? Instead extending klaro would be a good thing.
> An extra script with the needed polyfills for older browser would be good.
That's the problem. I've done many tests with polyfills but all results in unknown exception or exception is not handled. And if other older browsers for example on older Android or iOS working with polyfills is not guaranteed

> Oil.js is another good and free cookie consent manager.
Yes! I've seen this, but not still tried.

> Your fix for IE 11 works here too, on IE11 Win10 Pro 64
That's nice to know

**Comment by jmartsch** [comment]
Well, sadly it still does not work correctly in IE11. It seems the klaro cookie is not being saved, and so on every reload of the page, the consent banner appears again, and all apps are checked :(

**Comment by mkkeck** [comment]
Ok, I will test it later again. Perhabs some other 'polyfill' is missing. Did you get an error in the console?

**Comment by leonexcc** [comment]
It ist probably missing the polyfill for Set

**Comment by jmartsch** [comment]
I can confirm that #124 works in IE11 on Win10 Pro 64. Thank you :)

**Comment by mkkeck** [comment]
I've a solution for older browsers:
`script.dataset` won't work on older browser. I've replaced with `script.getAttribute("data-name-of-attr")` and `script.setAttribute("data-name-of-attr", theValue)` in main file `klaro.js` and `consent-manger.js`. Some other minor changes have to be done too. I will fork klaro and put my changes on a separate branch soon as posible.
My modification works down to IE9.

**Comment by adewes** [comment]
We just made the necessary changes to make Klaro compatible with IE10 & IE11 (and possibly IE9, thanks for your suggestions and contributions!
