### ISSUE TITLE
In most consent tools the primary "ok" button works as "accept all" - even if the apps are unchecked by default

### ISSUE THREAD

**Issue by jobee** [KIProtect/klaro#122]
**Steps to reproduce**

1.) Configure all apps to `default: false`
2.) Click "Ok" or "Decline" button

**Current behavior**

"Ok" is just a configuration (default value) acceptance.
If all apps are disabled by default - except for the necessary ones - "Ok" and "Decline" is doing the same thing.

**Expected behavior**

In most consent tools the primary "ok" button works as "accept all" - even if the apps are unchecked by default. That should push the acceptance rate and meet the "current law" I guess.

**Comment by leonexcc** [comment]
I tried to do the same and sent a pull request (https://github.com/KIProtect/klaro/pull/118) which accepts all apps with `default: true` on "Ok" but does not show them as active if you open the manager the first time.

**Comment by DalbertHab** [comment]
I also tried it in #123. In my tests, all cookies are accepted.

**Comment by jaller94** [comment]
This works as intended.
If a site owner chooses to make all non-required apps explicit opt-in options, we may want to replace "Ok" with "Learn more" to ease opening the modal.

The proposed change by @leonexcc reflects best what we consider consent, where "Ok" enables default apps and the manager allows you to opt-in to all available apps.
