### ISSUE TITLE
klaro.kiprotect.com is outdated

### ISSUE THREAD

**Issue by futureweb** [KIProtect/klaro#129]
Hey there,
I just downloaded klaro.js as noted in Readme from: https://klaro.kiprotect.com/klaro.js - but it seems like this Version is outdated? It's missing some translations which are already added to latest GitHub Release, also it unsets *required* cookies when using 'unset all' ...
So where to get latest .js Version without manually building it?
thx

**Comment by jaller94** [comment]
The build of the website is currently broken. It's a few versions behind.
I'll try to get it fixed.

Until then, the latest (packaged) version can be found here:
https://www.npmjs.com/package/klaro

This Url will give you the latest JavaScript file:
https://unpkg.com/klaro

**Comment by adewes** [comment]
Should be fixed and up-to-date now.
