### ISSUE TITLE
Close button can't be clicked in modal

### ISSUE THREAD

**Issue by moabi** [KIProtect/klaro#135]
**Steps to reproduce**

+ when the main modal window is open, the h2.title overlaps the close button in .cm-header
+ if the translation is missing, the close button title will be : [missing translation: de/close], like the SVG icon included in it. maybe we can add default "close" label

**Current behavior**

modal is therefore difficult to close (I'm using bulma in my project, don't know if this plays a role)

**Expected behavior**

enlarge the close button area with a superior z-index, or even better, elements should not share the space (in case of long title for example)

**Comment by jaller94** [comment]
I assume you mean `h1.title`. When does it overlap the close X?

![klaro-title](https://user-images.githubusercontent.com/10872136/70240934-6c5b8500-176e-11ea-8e59-14b3a7370d52.png)

Would a translation of "close" in every language fix the issue or is there additional work necessary?

**Comment by jaller94** [comment]
It bugs me not to know why this is happening on your page but seemingly no other.
`z-index: 1` on the X button does fix it.
The missing translation does not seem to have an affect on the issue.

**Comment by moabi** [comment]
Yes I was on it, this is because I have a relative position on the H1
thanks

**Comment by jaller94** [comment]
Just released [0.2.12](https://github.com/KIProtect/klaro/releases/tag/v0.2.12) with the fix included.
May I ask where you download Klaro from?

The website is currently outdated. NPM did get updated.

**Comment by moabi** [comment]
From Github, thx for this neat solution (lightweight, no dependencies, open source, flexible...)
