### ISSUE TITLE
Accept All by "OK" without setting "default" to "true"

### ISSUE THREAD

**Issue by GottHeit** [KIProtect/klaro#138]
Not sure if Idid something wrong, but I expected that all consents would be set to "true" (accepted) by hitting the "OK-Button" - even when every app in the config.js is set to "default: false". 

This should be the behaviour which corresponds to the conditions necessary in Germany. 
As I understood it is not possible to set every app to "default:true" in the further settings; in that menu the apps have to be disabled and the user has to accept them on their own.

If each app is set to "default:false" no app is set to an "enabled state" by the "OK-Button". 
How do I change that? Can I do that? 

Thanks a lot!

**Comment by MLzen** [comment]
I have the same problem and hope someone can help with it :(

**Comment by jobee** [comment]
would be solved by https://github.com/KIProtect/klaro/pull/118 - still waiting for the merge :)

**Comment by danielzellfelder** [comment]
also waiting for the merge :)

**Comment by DalbertHab** [comment]
You can have a look at #123

**Comment by matjaeck** [comment]
> Not sure if Idid something wrong, but I expected that all consents would be set to "true" (accepted) by hitting the "OK-Button" - even when every app in the config.js is set to "default: false".

This would effectively be the same as pre-checked checkboxes, and courts say that these are not adequate to obtain valid consent. So I would feel better if we could introduce a new config parameter for this behavior.

**Comment by GottHeit** [comment]
> > Not sure if Idid something wrong, but I expected that all consents would be set to "true" (accepted) by hitting the "OK-Button" - even when every app in the config.js is set to "default: false".
> 
> This would effectively be the same as pre-checked checkboxes, and courts say that these are not adequate to obtain valid consent. So I would feel better if we could introduce a new config parameter for this behavior.

I do not really agree, but a config parameter would be fine, too. As long as it is possible to get an "accept all" somehow in first modal.

In my understanding it should be different. As you have two equal options: yes (all) or no (none) - thereby there is no preliminary decision (you can see that in much consent tools actually). The acutal behaivour does definitely not comply with the law, if you set every single to default:true therefore. They have to be selected to true one by one by the page visitor in the further settings. So the OK-button does just nothing right now... Because of me it would be okay to just rename it to "accept all" if it has the possibility to get that function

So of course there will be more judgements about it, I guess. And I personally do not see any argument why not implenting a config parameter for those who want that feature, right :)

**Comment by DalbertHab** [comment]
#123 has the accept all button that accepts all cookies with config setting **default: false**

![image](https://user-images.githubusercontent.com/10434787/72596023-70e99080-390b-11ea-91da-25f0f0b1861b.png)
![image](https://user-images.githubusercontent.com/10434787/72596030-747d1780-390b-11ea-8c7c-79d0b10dec9b.png)

**Comment by MLzen** [comment]
Are you sure the "togge all apps"-option should be active here? Imo it should be inactive and become active after clicking itself or "accept all". 

Best scenario would be:
After clicking "accept all" the toggle-all-transition/animation finishes and THEN the modal closes.

OT: There should be possibilites at all to animate the modal open/close...now it's just instant there or gone. :(

**Comment by GottHeit** [comment]
> 
> 
> #123 has the accept all button that accepts all cookies with config setting **default: false**
> 
> ![image](https://user-images.githubusercontent.com/10434787/72596023-70e99080-390b-11ea-91da-25f0f0b1861b.png)

Ah okay, I see :) 

> Added option to replace "decline all" with open modal.

But then it has to have "open modal" aswell, like:
Ok (accept all)
Decline (decline all)
More (further settings)

**Comment by maartenmachiels** [comment]
Hi, just came across Klaro and it looks great. Any update on when the merge would be ready? If not, is there any way to hide the decline-button in the current version? I'd like to only keep two options: "accept all" and "preferences". "Preferences" would open the modal with all options unchecked as required by law and "accept all" would accept everything :-)... Thanks in advance.

**Comment by maartenmachiels** [comment]
Thanks for your great work on this plugin. Is there any documentation available on how to use this new functionality? I'm using version 2.1.4 now but am unable to figure out how to get the "Accept all" button both in the consentNotice and in the cookieModal. Also, I cannot figure out how to hide the decline all button. The screenshots in this thread are exactly the functionality what I'm looking for.

**Comment by DalbertHab** [comment]
@maartenmachiels This change is still in review: #123

**Comment by gebeer** [comment]
+1 for this change. If it will not be accepted, I will have to switch to @DalbertHab's fork.

**Comment by adewes** [comment]
We'll make improvements to the modal UI in order to accomodate this workflow and make the choices more obvious to the user.

**Comment by maartenmachiels** [comment]
Thank you very much! Do you have any idea of the timing for this release?

**Comment by adewes** [comment]
@maartenmachiels this should be fixed with the new release I think, let me know if it's still not what you want or if you have any improvements!

**Comment by maartenmachiels** [comment]
Hi, I just wanted to let you know that I tested this out and it works perfectly. Thank you very much for your nice work.
