### ISSUE TITLE
required + optOut = wording failure

### ISSUE THREAD

**Issue by futureweb** [KIProtect/klaro#139]
Hey there,
when 'required' AND 'optOut' is 'true' on some Cookies - the "wording" of the Hover Text is a bit misleading ... it says "This App is loaded by default (but you can opt out)" which is wrong - one can't Opt-Out of 'required' Cookies. Maybe one can honor this combination with it's own hoover text.

![grafik](https://user-images.githubusercontent.com/1698881/70605841-87f5de00-1bfb-11ea-9d5d-2834345043d7.png)

**Comment by adewes** [comment]
Hm I think the combination of the `optOut: true` and `required: true` options just doesn't make sense here, this is more a configuration problem, but we'll look into it. Thanks for pointing this out!
