### ISSUE TITLE
Wordpress WPML Übersetzung

### ISSUE THREAD

**Issue by Bimm-zz** [KIProtect/klaro#142]
Es wäre schön, die Kompatibilität mit WPML herzustellen.

Hier die Rückmelung des Supports:

I can see the plugin is loaded before the wpml is loaded and hence the
WPML filter are not working.

The Query on klaro-consent-manager/klaro.php line 1013 that I have
mentioned should be execute after the plugins_loaded action hook, But
it is loaded in the enqueu_script which is causing the issue. I could
not see an easy fix here as there are a couple of places that need to
be edited.

Invite the plugin author to our go global program so that the plugin
can be made 100% compatible with wpml
https://wpml.org/documentation/theme-compatibility/go-global-program/

**Comment by jaller94** [comment]
There is one Wordpress plugin maintained by a third party outside of our team.
We currently do not release a build to Wordpress.org.

Link: https://wordpress.org/plugins/klaro-consent-manager/ (not affiliated with us)

---

A thread about translating strings for Klaro from within Wordpress:
https://wpml.org/forums/topic/translate-klaro-cookie-consent-manager-application-text/

**Comment by Bimm-zz** [comment]
Thank you - i send the request to the plugin author.


am Montag, 16. Dezember 2019 um 15:46 schrieben Sie:

> There is one Wordpress plugin maintained by a third party outside of our team.
> We currently do not release a build to Wordpress.org.

> Link: https://wordpress.org/plugins/klaro-consent-manager/ (not affiliated with us)

> ---

> A thread about translating strings for Klaro from within Wordpress:
> https://wpml.org/forums/topic/translate-klaro-cookie-consent-manager-application-text/



--

christian.bimm.coers
cbc|design
bürgersruh 16
13469 berlin

030.44 34 15 48
coers@cbc-design.de
www.cbc-design.de
