### ISSUE TITLE
How to handle dynamically added script blocks?

### ISSUE THREAD

**Issue by sysiler** [KIProtect/klaro#143]
Hi everyone, 

I was wondering how I could deal with script blocks that are added dynamically to the DOM.
In my case, I have an external service that returns a script block like this:
`<script type="opt-in" data-type="application/javascript" data-name="mytest">console.log("This is working!");</script>`
which is added to the DOM with jquery:
`$("#mydiv").html(scriptstring);`

However, the script is not executed (it is when sending `<script>` only, without type opt-in).
Is there a way to trigger klaro.js again to convert an execute the script block? Just as simple as `klaro.getManager(config).runAgain();` or something :D 

Thanks for your input!

**Comment by nussisworld** [comment]
Hi,

I did it for iframes like this:

`<script>
  // iframe Block
 jQuery(function ($) {
$(document).ready(function(){


   $('iframe[src*="youtu"],iframe[src*="vimeo"],iframe[src*="facebook"]').each(function(){
      var video = $(this);
        video.attr('data-src',video.attr('src')).removeAttr('src').attr('type', 'opt-in').attr('data-name', 'youtube');

    

   });

  
});
});
</script>`

You can do it with scripts aswell. Just change iframe to script and replace the src values.
