### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by bell430** [KIProtect/klaro#145]
Hi!

I just tried to create a custom CSS and somehow couldn't make it. I did the following:
- Downloaded [https://unpkg.com/klaro@0.2.12/dist/klaro.js](https://unpkg.com/klaro@0.2.12/dist/klaro.js) and put it on my webserver. Also the config-file.

I put the following code in my header:
```
<style>
.my-styles {
    background-color:#bdcbcb;
    color: green;
}
</style>

<script defer type="application/javascript" src="js/klaro_config.js"></script>
<script src="js/klaro.js" data-style-prefix="my-styles"></script>
<script defer type="application/javascript" src="js/klaro.js"></script>

```
The tool itself appears, but my test-css-class is ignored. What can I do make it work?

Thanks and best regards!

**Comment by jmartsch** [comment]
Well, you have the included the klaro script two times. Remove the last line, and add the defer attribute to the line with the data-style-prefix:
`<script defer src="js/klaro.js" data-style-prefix="my-styles"></script>`

Please also note, that the default styles are not applied if you use custom styles.

**Comment by adewes** [comment]
We recently added multiple ways to customize the CSS of Klaro, please check out our website (https://klaro.kiprotect.com) for more information and let us know if you still have problems. You can e.g. embed `klaro-no-css.js` and bring your own stylesheet, we also provide an unminified version of the Klaro css stylesheet for easy modification.
