### ISSUE TITLE
setup klaro with adsense-code

### ISSUE THREAD

**Issue by paerb** [KIProtect/klaro#146]
Hello,

i managed to set up klaro with my external tracker and google-analytics. thanks for the great project!

however i have difficulties setting up klaro with my adsense code.

every adsense code has different parts:

```
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- channel -->
<ins class="adsbygoogle"
     style="display:inline-block;width:200px;height:200px"
     data-ad-client="client-id123"
     data-ad-slot="123456"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
```
if i setup only the last part with claro

`<script type="opt-in" data-type="application/javascript" data-name="adsense">
(adsbygoogle = window.adsbygoogle || []).push({});
</script>`

cookies are loaded from the external source before the user has a chance to opt-in

if i try to set up only the first part

`<script async type="opt-in" name="adsense" data-type="application/javascript" data-src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>`

or the whole code
```

<script async type="opt-in" name="adsense" data-type="application/javascript" data-src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- channel -->
<ins class="adsbygoogle"
     style="display:inline-block;width:200px;height:200px"
   data-ad-client="client-id123"
     data-ad-slot="123456"></ins>
<script type="opt-in" name="adsense" data-type="application/javascript">
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
```

it doesnt work.

any ideas how to set up adsense correctly? thank you very much!

Patrick

**Comment by adewes** [comment]
Sorry for the late answer, the `async` keyword is the problem here (I think): It causes the first script to executed asynchronously when it's loaded while the second one is executed as soon as it's created, hence it cannot use the resources defined by the asynchronous script (in most cases). You should either remove `async` or use `defer` for both scripts, which will maintain the execution order of the script.
