### ISSUE TITLE
Using a common i18n format and a l10n plateform

### ISSUE THREAD

**Issue by Heziode** [KIProtect/klaro#148]
# The problem

An overview of the state of translation is no currently possible (or at least very difficult). For example, missing translation, etc. (example: *purpose* l10n seems only available in english).

Furthermore, the translation process can be done by non developper people, that is currently not possible because it require a git and yaml knowledge.

# Proposed solution

We should concider to migrate to a format that can be managed by a translation manager.

Using an i18n framework like [i18next](https://www.i18next.com/) or [i18njs](https://i18njs.com/) and a platform like [Weblate](https://weblate.org/fr/) (self-hosted possibilities), [LingoHub](https://lingohub.com/) or [Transifex](https://www.transifex.com/) to encourage the community to help translate the site.

**Comment by jaller94** [comment]
Hi @Heziode, I'm totally on your side. Weblate seems like its best suited for us, as we host most of our development infrastructure ourselves.
We use the same code for translations across all our other applications. A change in how Klaro handles translations must be scalable to all our projects. No or minimal changes to the data structure are preferred.

**Comment by Heziode** [comment]
> A change in how Klaro handles translations must be scalable to all our projects.

Which projects ?

**Comment by jaller94** [comment]
> Which projects ?
* [KIProtect App](https://kiprotect.com/) (source not released)
* [Algoneer App](https://gitlab.com/algoneer/algoneer-app)

**Comment by adewes** [comment]
Can you create a PR for this? I'd be happy to consider this but so far I'm satisfied with our approach because it allows easy customization by users (i.e. by modifying the config). My condition for a generic framework would be that it also allows simple customization without requiring a specific toolset or recompiling of the code (as many users won't be able to do that then).

**Comment by Heziode** [comment]
@adewes I can take a look.

If I understand well your expectation, I think i18next can do the job.
