### ISSUE TITLE
Privacy statement link in consent modal not opening link

### ISSUE THREAD

**Issue by klfman** [KIProtect/klaro#152]
I upgraded from Version 0.2.9 to 0.2.12 when I realised the click on the {privacyPolicy} link in the consent modal does not open the url as expected.

I use the "mustConsent" flag, so the modal shows right in the beginning. When I change my choice (after having already consented once before) the overlay closes when clicking on the {privacyPolicy} link but does not navigate to the href of the <a> tag. It looks like a callback that is registrered in javascript prevents the browser from opening the link.
When I open the link in a new tab directly it works, however.

I think tracked the problem down (untested!) to a `hide` function which, in a commit after 0.2.9 was released, introduced a `preventDefault` on the clickhandler. I didn't have time to change the code, recompile and test, so this is just what I suspect. The problem might be somewhere else.

**Comment by jaller94** [comment]
Introduced in: 03af77311a371c203534d10e74445a1d0f060e0b

`hide` determines if `preventDefault` should be executed by testing if an event has been given.
As a developer I find this behavior unintuitive. It was introduced to prevent `<a href="#"></a>´ links from changing the hash value.

All false links have become buttons over time, with the exception of "Learn more". From an accessibility perspective, opening a modal is an action triggered by a button, not a link. Our fork Orejime solved the both issues by making "Learn more" a third button.
