### ISSUE TITLE
Add an attribute with a value of blocked or allowed when Klaro has processed an iframe

### ISSUE THREAD

**Issue by maartenmachiels** [KIProtect/klaro#157]
I'd like to have some way to target elements that have finished processing. When using Klaro in conjunction with iframes, by adding type="opt-in" and moving the src to a data-src attribute, I'd like to show a message that can be clicked to allow the iframed content.

`<iframe type="opt-in" data-name="embeddedContent" data-src="https://eventbrite.com/tickets-external?eid=xxxxx"></iframe>
`

I'd like to add an attribute like data-klaro-processed="allowed" or data-klaro-processed="blocked" to all elements that have been evaluated by Klaro. The attribute would then be able to be targetted by CSS or Javascript to show a message or connect a click handler.

I'd like to be able to easily show a message when iframed content has been blocked by the privacy settings of the user. I'd like to offer to the user the option to change their settings so that they can allow the iframed content.

`<iframe type="opt-in" data-name="embeddedContent" data-src="https://eventbrite.com/tickets-external?eid=xxxxx" data-klaro-processed="blocked"></iframe>`

CSS to target the processed but blocked iframe

```
iframe[data-klaro-processed="blocked"] {
 background: url('blocked.png');
}
```

Jquery to target the processed but blocked iframe 

```
$('body').on('click','iframe[data-klaro-processed="blocked"]',function(e) {
        klaro.show();
    });
```

**Alternative solutions**

Alternatively we could show an image tag or a message instead of the iframe, and build this into klaro, but I think this would be overly complex.

**Additional context**
I've got it working via a very unelegant workaround. This is the image I'm showing when an iframe is blocked. Again, it's less than elegant, I'm using a delay in Javascript to wait untill everything has loaded and I then evaluate if there is a data-src attribute but no src attribute... You can imagine this is suboptimal.

![image](https://user-images.githubusercontent.com/3584586/72670148-71347980-3a3a-11ea-86c3-0127391febe5.png)

What do you think? Am I overlooking something? Might there be a callback when Klaro has finished loading? That might even do the trick.

**Comment by jaller94** [comment]
There is an `app.callback` property. If a function is defined it's called every time the status of an app changes.
A global callback is being discussed in issue #59.

Accessibility side note: Background images in CSS will not be read by screen readers and `onclick` will only trigger on buttons for keyboard users.

**Comment by maartenmachiels** [comment]
Thank you for your answer and your insights regarding screen readers. I will certainly take this into account and update my solution further.

For your information, I've managed to get a rough, inbetween solution going via:
```
$(window).load(function(){
    // Add an eventlistener to all divs with classname .change-privacy-settings
    $('body').on('click','.change-privacy-settings',function(e) {
        klaro.show();
    });
    findEmbeddedBlocks();
    function findEmbeddedBlocks() {
        $('iframe[data-name="embeddedContent"]').each(function (index) {
            if (!$(this).attr('src')) {
                // Wrap the iframe with a div that has a background image
                var parent = $(this).wrap("<div class='change-privacy-settings'></div>");
            }
        });
    }
});
```
CSS

```
.change-privacy-settings {
  cursor: pointer;
  background: $grey url('../images/content-blocked.svg') no-repeat center center;
  iframe {
    /* Passthrough of pointer events so click handler is accessible */
    pointer-events: none;
  }
}
```
Thanks again for your work on this.

**Comment by adewes** [comment]
Closing this for now, if you have further questions please re-open.

**Comment by balduin-kowalski** [comment]
There is a way to solve this with the callback-function:
https://github.com/KIProtect/klaro/issues/190
