### ISSUE TITLE
Change single cookie directly from the webpage

### ISSUE THREAD

**Issue by astruzh** [KIProtect/klaro#162]
Hello!
I try to find a way to change a setup for the single cookie directly from the website.
I explain why. For example the website uses a lot of third-party services and the cookie-list in the modal window is long.
The user has declined all cookies on the start.
Then he comes on a subpage with integrated Youtube video. On this place I put the message, that he has to change the cookie setup for Youtube in the cookies-setup window and put the link to modal window like `<a onclick="klaro.show();return false;">Cookies</a>` . After the click the modal window will be opened and the user has to find the right checkbox for youtube – not really user-friendly way.
My idea to get him the opportunity to allow the youtube cookies directly without to open the modal window.
The message can be like this: To see the youtube video please allow the cookies of youtube `<a onclick="…">here</a>. You can find more info about cookie <a onclick="klaro.show();return false;">here</a>`.

I can do it with a small javascript – readout the klaro cookie, find a right name in array, change the array, save the changed cookie into the browser.

My question is, if it may be possible to do it in another way?

**Comment by matjaeck** [comment]
It's not necessary to edit the markup of embedded iFrames to conditionally enable them. See https://stackoverflow.com/a/8961617. We could offer a global setting (iFramOptIn) with a placeholder text var for this.

**Comment by adewes** [comment]
You can already do this (I think):

First, `var manager = klaro.getManager()` will retrieve the consent manager object. You can then call `manager.updateConsent("youtube", true)` and `manager.saveAndApplyConsents()` to apply the new consents. Let me know if that shouldn't work by reopening this issue, I'll close this for now.
