### ISSUE TITLE
 Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by sumiahTR** [KIProtect/klaro#163]
**Steps to reproduce**

I just have downloaded it from the github repository.and tried to run it.without any changes.but it shows 'klaro.js:9 Uncaught SyntaxError: Cannot use import statement outside a module' error.i dotn know what to do?

**Current behavior**

klaro.js:9 Uncaught SyntaxError: Cannot use import statement outside a module.this is the error showing without any changes in script.

**Expected behavior**

I expected to run the script so it pop ups the cookie banner when the sites get uploaded.

**Comment by adewes** [comment]
It seems you're trying to import the ES6 (untranspiled) version of Klaro, hence the syntax error. Please check the documentation and the example integration on the website (https://klaro.kiprotect.com). The transpiled script is compatible with all major browsers and is minified, it has only one line of code (https://klaro.kiprotect.com/klaro.js).

**Comment by sumiahTR** [comment]
Thank you soomuch it worked
