### ISSUE TITLE
Automatic deletion of cookies in Google Chrome not working

### ISSUE THREAD

**Issue by klfman** [KIProtect/klaro#165]
Automatic deletion of cookies through the function `deleteCookie` (see [src/utils/cookies.js](https://github.com/KIProtect/klaro/blob/80c4b5568a1dea7486ce5af904d1eb6e6a4d858f/src/utils/cookies.js)) only seems to work in Firefox, not in Chrome.

In Chrome a reload is necessary.

**Steps to reproduce**
I reproduced the problem with the official example page for you to reproduce yourself (also have this problem in my implementation):

Steps (in Chrome and Firefox):
1. Open https://klaro.kiprotect.com/, open devtools to inspect the cookies that were set
2. Click Button "Show manager", enable all cookies and confirm
3. Cookies `external-tracker` and `inline-tracker` are set
4. Click Button "Show manager", disable all cookies and confirm
5. Chrome: Cookies are not removed automatically, only on page reload; Firefox: Cookies are removed instantly

**Current behavior**
Cookies are not removed automatically in Google Chrome when the consent is withdrawn.

**Expected behavior**
Cookies should be removed automatically.

**Used browser versions**
I'm using up to date browsers:

- Firefox 72.0.2 (64-bit)
- Chrome 79.0.3945.130 (64-bit)

**Comment by klfman** [comment]
I'm currently not sure if my example is valid as it seems that the devtools in Chrome just fail to refresh the cookie view sometimes. If I switch tabs to, say, `Console` and then back to `Application` (where the tabs are listed) the list is empty after deleting the cookies.

So maybe I was just observing out of date cookie information.

Trying to collect more information to confirm what I'm observing ...

**Comment by klfman** [comment]
Had no time to confirm this, I'm still looking into it and will close this issue if invalid

**Comment by adewes** [comment]
I also noticed this behavior, but I think it is a bug/feature in the Chrome developer toolbar, which does not update cookies before the page is reloaded. You can confirm the deletion takes place by disabling Javascript before reloading the page after having Klaro erase some cookies. If they're gone you know they must have been deleted before.

Feel free to reopen this if you think it's really a bug on our side, so far I assume this is a Chrome issue.
