### ISSUE TITLE
W3C Validator Bad value opt-in for attribute type on element script

### ISSUE THREAD

**Issue by gebeer** [KIProtect/klaro#169]
**The problem**

`<script>` tags with `type="opt-in"` do not pass W3C validation on https://html5.validator.nu/

**Proposed solution**

choose a different, valid value for the type attribute to mark script as opt-in
or use a data attribute, e.g. `data-optin="1"`

**Comment by adewes** [comment]
While I don't think this will cause problems (it's just important that the browser does not try to interpret the script), we can use e.g. `text/plain` to have a valid mimetype in the field.

**Comment by adewes** [comment]
@gebeer fixed in the new release, closing this.
