### ISSUE TITLE
Deletion of cookies of different domain not working

### ISSUE THREAD

**Issue by klfman** [KIProtect/klaro#171]
The functions `updateAppCookies` of [consentManager.js](https://github.com/KIProtect/klaro/blob/0895f8cbbd32425c315acf3911baebbda1402c4d/src/consent-manager.js#L238) and `deleteCookie` of [cookies.js](https://github.com/KIProtect/klaro/blob/0895f8cbbd32425c315acf3911baebbda1402c4d/src/utils/cookies.js#L43) fail in deleting cookies with a domain that is not the current domain.

My apps configuration is:
```
{
  "title": "Facebook Pixel",
  "description": "Tracking des Nutzerverhaltens (z.B. für gezieltere Werbekampagnen).",
  "name": "facebookPixel",
  "cookies": [
    [
      "_fbp",
      "/"
    ],
    [
      "fr",
      "/",
      ".facebook.com"
    ],
    [
      "",
      "/tr",
      "www.facebook.com"
    ]
  ],
  "purposes": [
    "tracking"
  ]
}
```

I read the code and played around in a current firefox and chrome and found out that it should even be impossible to delete cookies of a different domain as the current, as far as I know right now (see for example [here](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie): 

> Note: The domain must match the domain of the JavaScript origin. Setting cookies to foreign domains will be silently ignored

).

Why? Both functions use document.cookie, which will only return the cookies set by the current domain and its subdomains.

Any idea how to work around this? Or is it impossible what I'm trying to do (deleting cookies of externally loaded trackers like facebook pixel)?
If so: The documentation should be updated to tell that the `path` and `domain` part is only meant to be used with subdomains and will have no effect on other domains' cookies (even if it might sound trivial to people having worked with cookies before)

**Comment by adewes** [comment]
Yes, it's not possible to access, modify or delete cookies from a different domain than the one Klaro is installed on. Unfortunately we can't do anything against such agressive third-party cookies. As a website owner you can choose (as far as I know) to only use a first-party tracking cookie for Facebook, which I would really recommend.

We'll consider updating the documentation to make it clear that Klaro can only delete first-party cookies, thanks for your feedback!
