### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by futureweb** [kiprotect/klaro#174]
Hey there,
it would be great if there would be a Changelog so we can see what changed between Versions ... ;-)
thx, bye from Austria
Andreas

**Comment by futureweb** [comment]
Example: I just updated a few Websites with latest Version ... afterwards I noticed that some new translations has been added ... so I had to add those to all the updated Sites too ... if there would have been a Changelog I would have known forehand what's new and what to look for when updating existing instances instead of finding out "the hard way" with a bad feeling left in the stomach area that I may have missed some other things too which need action by me ... ;-)

**Comment by adewes** [comment]
Good point, we'll do that from now on!

**Comment by adewes** [comment]
Hey @futureweb , we now got a changelog (https://kiprotect.com/docs/klaro/releases) and a machine-parseable file that it's generated from (https://github.com/kiprotect/klaro/blob/master/releases.yml). If you have any suggestions what we should include please let me know! Closing this for now :)
