### ISSUE TITLE
klaro.show() is not a function

### ISSUE THREAD

**Issue by Naseki** [KIProtect/klaro#176]
My code is fairly simple, but here it is:
```
<script defer type="application/javascript" src="js/config.js"></script>
<script defer type="application/javascript" src="js/klaro.js"></script>

<div class="cookie--modifier" onclick="klaro.show()">Manage consent</div>
```
I placed this on the bottom of the page.

The config.js file mainly uses the defaults and seems to work as expected.

I first thought that maybe the show() function doesn't work the way it should due to using jQuery on the site and show() being a function there as well, but removing jQuery doesn't fix it.

"klaro" is supposed to return a module with functions as I'd seen on the website, but on mine it seems to return the element #klaro (the default) instead.

**Comment by adewes** [comment]
This looks fine to me, I think there is either a problem with your script loading (you can check this using the network tab) or that something else shadows the global `klaro` variable. Please note that browser will assign global variables for elements with an `id` property, so they might override the Klaro library depending on the loading order. We have never had any issues with this but the global importing style (as opposed to importing Klaro as an AMD module) can cause such trouble.

You could try to change the ID of your Klaro `div` element and change the `elementID` property in the config accordingly:

config.js
```
{
...
    'elementID' : 'klaroDiv',
...
}
}
``` 

Let me know if that solves your problem! I'll think about ways to avoid this in the future (if indeed it is the problem here).

**Comment by Naseki** [comment]
I don't see any problems with the script loading.

By changing the ID, `klaro` becomes undefined so I still can't use the function.

**Comment by adewes** [comment]
There must be something that blocks Klaro from executing correctly then. It might be possible that Klaro is not yet loaded when you press the button (as it is deferred), but that shouldn't be an issue unless it takes really long to load the script.

If Klaro loads correctly it will always define a global `klaro` variable in the `window` object, that this variable isn't set means the script didn't execute or encountered an issue when executing (this you should see on the console).

I can only debug this further if I can see the full webpage and Klaro config.

**Comment by Naseki** [comment]
There are no related errors in the console. I also just noticed that inline scripts don't get turned on after the cookie has been accepted, so basically only the banner and the toggle box work as expected. It does seem like part of the script doesn't get loaded, but I don't see any errors anywhere.

Here's the config: 

```
var klaroConfig = {
    elementID: 'klaroDIV',
    cookieExpiresAfterDays: 365,
    privacyPolicy: '/cookie-policy/',
    default: false,
    mustConsent: false,
    acceptAll: false,
    hideDeclineAll: false,
    lang: 'en',
    apps: [
        {
            name: 'google-analytics',
            title: 'Google Analytics',
            purposes: ['analytics'],
            cookies: ['_ga', '_gid', '_gat', /^_gac_.*$/i],
            optOut: false,
        },
        {
            name: 'recaptcha',
            title: 'Google reCAPTCHA',
            purposes: ['security'],
            required: true
        },
        {
            name: 'youtube',
            title: 'Youtube embed',
            purposes: ['functionality'],
            optOut: false,
            callback: function(consent, app) {
                console.log(consent)
            }
        }
    ],
};
```

**Comment by Naseki** [comment]
Here are some screenshots.

![1](https://user-images.githubusercontent.com/30054237/75788318-59a21d80-5d68-11ea-98b3-a429e725c82a.png)
![2](https://user-images.githubusercontent.com/30054237/75788326-5c047780-5d68-11ea-8839-ea2b7f0c1a26.png)
![3](https://user-images.githubusercontent.com/30054237/75788708-e77e0880-5d68-11ea-8e0b-8cecf3bb444e.png)
![4](https://user-images.githubusercontent.com/30054237/75788716-e9e06280-5d68-11ea-8094-a63c512fada8.png)

**Comment by adewes** [comment]
This looks fine to me, but again, if `klaro` is undefined it means that it didn't load correctly.

> I also just noticed that inline scripts don't get turned on after the cookie has been accepted, so basically only the banner and the toggle box work as expected

This I don't understand: How can you accept the cookies if the consent manager is not being loaded?

**Comment by adewes** [comment]
I cannot provide detailed debugging for your case, please have a look at the demo site at https://klaro.kiprotect.com where we show how to embed the script.
Since there is a lot of JS being loaded on your page it's possible that another script interfers with the functioning of Klaro (as again the `klaro` variable should always be defined on the `window` object), I would therefore try to remove some of your other JS in order to see if there's a problem there.

**Comment by Naseki** [comment]
Ah, by "toggle box" I meant the consent manager. The banner as well as the consent manager appear to work.

**Comment by adewes** [comment]
Ok. Then I don't understand how `window.klaro` can be undefined?

**Comment by adewes** [comment]
My guess would be that it's a problem with the loading order, maybe you can check in the console if `window.klaro` is defined?

**Comment by Naseki** [comment]
I did check in the console when I initially made this issue. Klaro stays undefined after everything.

I've deleted all scripts that loaded into the website and added everything back one by one. I found that Mailchimp's embed plugin keeps `klaro` from being undefined. I'm not sure why.

**Comment by adewes** [comment]
Cool, at least you found the culprit :D Not sure how this can happen to be honest, maybe Mailchimp does something with the globally defined variables.

You can try to reverse the loading order, i.e. put Klaro at the end of your page / after Mailchimp to see if that fixes the problem.

**Comment by Naseki** [comment]
I removed `defer` from the script tag as Mailchimp would otherwise execute before Klaro does and everything seems to be working now. Thank you for taking me to the right direction! :)
