### ISSUE TITLE
Clicking "Accept" marks consent as false and doesn't fire callbacks

### ISSUE THREAD

**Issue by darylknight** [KIProtect/klaro#177]
If I click Accept on the small dialog that pops up when I load the page, consent is marked as false for all cookie categories. Am I missing something? I couldn't see anything in the docs about how this accept button is supposed to work. If I open the dialog and use the toggle switches, cookies and callbacks are used correctly; but the Accept button doesn't seem to do anything.

**Klaro Config**

```
{% js %}

var cookieExpires = "{{ now|date_modify('+30 days')|date('l, d-M-Y H:i:s T') }}";

function set_cookie(name, value, expiry) {
  document.cookie = name +'='+ value +'; Path=/; expires=' + expiry;
}

var klaroConfig = {
  elementID: 'klaro',
  cookieName: 'klaro',
  cookieExpiresAfterDays: 365,
  privacyPolicy: '/privacy-policy',
  default: true,
  mustConsent: false,
  lang: 'en',

  translations: {
    en: {
      consentModal: {
        description:
        'Here you can see and customize the information that we collect about you.',
      },
      googleAnalytics: {
        description: 'Analytics data collected by Google for usage statistics',
      },
      thirdParty: {
        description: 'Various embeds containing tracking cookies such as Soundcloud, Spotify and others',
      },
      purposes: {
        analytics: 'Analytics',
        thirdParty: 'Third Party'
      },
    },
  },

  apps: [
    {
      name: 'googleAnalytics',
      default: false,
      title: 'Google Analytics',
      purposes: ['analytics'],
      cookies: [
        ['_ga', '/', '.boilerplate.test'],
        ['_gid', '/', '.boilerplate.test'],
        [/_gat.*/i, '/', '.boilerplate.test'],
        [/_gac_.*/i, '/', '.boilerplate.test'],
      ],

      callback: function(consent, app) {
        console.log('User consent for app ' + app.name + ': consent=' + consent);
      },
      required: false,
      optOut: false,
      onlyOnce: false,
    },
    {
      name: 'thirdParty',
      default: false,
      title: 'Third Party',
      purposes: ['thirdParty'],
      cookies: [
      ],
      callback: function(consent, app) {
        if (consent == true) {
          // consent is given for third party cookies
          // console.log('User consent for app ' + app.name + ': consent=' + consent);

          // When cookies are accepted, set a cookie saying third party cookies are allowed - used for loading the HTML block's content
          set_cookie('thirdPartyConsent', 'accepted', cookieExpires); // Marks thirdPartyCookies as accepted

          {% if getCookie('thirdPartyConsent') %}
            // The callback function runs every single time the page is loaded, so check first whether cookies have already been accepted.
            // If this section runs, there is a thirdPartConsent cookie set, which means consent has previously been given, so don't reload the page to show html blocks
            console.log('User consent for ' + app.name + ': consent=' + consent);
          {% else %}
            // If this section runs, it means it's the first time the user has clicked accept, so reload the page to load the HTML blocks
            location.reload();
          {% endif %}
        } else {
          // consent has either just been revoked, or not been given
          {% if getCookie('thirdPartyConsent') %}
            // If this section runs, there is a thirdPartyConsent cookie set, which means consent has just been revoked, so reload the page to hide the html blocks
            location.reload();
          {% endif %}
        }
      },
      required: false,
      optOut: false,
      onlyOnce: false,
    },
  ],
};

{% endjs %}
```

**HTML Code of Page**

	<script defer type="application/javascript">{% include '_includes/klaroConfig' %}</script>{# Klaro config #}
	<script defer type="application/javascript" src="/assets/js/klaro-no-css.js"></script>{# Klaro script #}

--------------

When I click "Accept", a cookie named `klaro` is created with the following content:
`%7B%22googleAnalytics%22%3Afalse%2C%22thirdParty%22%3Afalse%7D`

Shouldn't the Accept button mark those two categories as 'true'?

**Comment by adewes** [comment]
We're about to rewrite our documentation so apologies if the workflow is not very clear. We have two workflows now:

* The normal workflow will have Accept and Decline buttons, which will either accept the default selection of apps or decline them.
* The `acceptAll` workflow has an "Accept All" button that will enable **all** apps and accept them, with the remaining workflow being identical.

You can choose which flow you want to implement, we enable the normal workflow by default to be backwards-compatible.

**Comment by darylknight** [comment]
Thanks for the fast reply :) Ok, so I think the implementation of that is slightly confusing - at least for me. The description for 'default' on a per-app basis is:

    // If "default" is set to true, the app will be enabled by default
    // Overwrites global "default" setting.
    // We recommend leaving this to "false" for apps that collect
    // personal information.
    default: false,

That makes perfect sense to me - apps that collect personal information should be disabled by default. 'by default', I mean the state of consent before the user clicks anything.

However, once a user gets to a website and clicks the dialogue that says "Accept", I would expect that accept button to accept all categories.

I guess the reason I missed this is because my config file doesn't have an acceptAll setting - the default config must have been updated since I set this up.

So I think the answer to my question is that I need to set "default: true" on anything that I would expect to be accepted by clicking accept.

**Comment by adewes** [comment]
You can enable the "Accept all" flow by setting `acceptAll: true` in your config, I think this will give you the desired workflow. Setting `default: true` for all apps you'd like to be preselected is another way to achieve this.

**Comment by adewes** [comment]
And yes, the `acceptAll` workflow is quite new, it was only deployed last week :)

**Comment by darylknight** [comment]
Got it, thank you!
