### ISSUE TITLE
Support Content Security Policy (CSP) on inline scripts

### ISSUE THREAD

**Issue by kevinvermeersch** [kiprotect/klaro#178]
**The problem**

I'm using a Content Security Policy (CSP) that blocks inline scripts unless a specific 'nonce' is added.

***EXAMPLE***:
Header:
`Content-Security-Policy:  default-src 'none';script-src 'self' 'nonce-<base64-value>'`

Html:
`<script nonce="<base64-value>"   type="text/plain"  data-type="application/javascript" data-name="linkedinInsights">`      

consent-manager.js should copy this nonce when creating the new script tag.

**Proposed solution**

ADD `newElement.nonce = element.nonce`

https://github.com/KIProtect/klaro/blob/af26de74d4a9401210e431f2b286cead7c863bd9/src/consent-manager.js#L206

**Additional context**

More info on CSP: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src

**Comment by adewes** [comment]
Sounds like a good idea! I'll check if we can implement something that will also work for other attributes, as we want to reproduce script tags as faithfully as possible.

**Comment by adewes** [comment]
This should be implemented now.
