### ISSUE TITLE
Move "Accept All" to the right

### ISSUE THREAD

**Issue by DalbertHab** [kiprotect/klaro#183]
**The problem**

If the `acceptAll` option is enabled, the "Accept All" Button is placed between "Decline" and "Customize" in the cookie notice and at left in the modal window.

Submit buttons tend to be the buttons at the right ones of a form.

***Notice***
![image](https://user-images.githubusercontent.com/10434787/76072190-cea76a00-5f97-11ea-9117-d946abbf36b2.png)

***Modal***
![image](https://user-images.githubusercontent.com/10434787/76072206-d7983b80-5f97-11ea-8f7c-57793d13011f.png)

**Proposed solution**

Change the order of the buttons/links in the notice and the modal.

***Notice***
![image](https://user-images.githubusercontent.com/10434787/76072228-dff07680-5f97-11ea-8d88-6f7b8787f072.png)

***Modal***
![image](https://user-images.githubusercontent.com/10434787/76072245-e8e14800-5f97-11ea-8563-d14f3d5842ba.png)

Releated Pull Request: #181

**Comment by adewes** [comment]
Looks nice, I'll review it and merge it!

**Comment by apptum** [comment]
+1

**Comment by stefanistrate** [comment]
+1
