### ISSUE TITLE
Add privacy policy to notice

### ISSUE THREAD

**Issue by DalbertHab** [KIProtect/klaro#184]
According to our data protection officer a link to the privacy policy must be present on the cookie notice.

**Comment by ZNicoZ** [comment]
what´s wrong with this config parameter?
![image](https://user-images.githubusercontent.com/7655980/78421616-5648cd00-7659-11ea-9ba1-b01e47a7c460.png)

**Comment by DalbertHab** [comment]
@ZNicoZ this parameter sets the privacy policy url for the modal window but we need a link to the policy in the notice.

**Comment by marcOSS040** [comment]
> @ZNicoZ this parameter sets the privacy policy url for the modal window but we need a link to the policy in the notice.

Hi DalbertHab, did you scripted the privacy policy in some way into the notice? Maybe you have some simple approach?
