### ISSUE TITLE
Block the full page with the cookie banner

### ISSUE THREAD

**Issue by amenk** [kiprotect/klaro#196]
**The problem**

People might oversee the cookie banner and not accept the banner.

**Proposed solution**

The banner should be configurable as full screen with a simple accept / decline / details option.

**Additional context**

The privacy page still has to be browseable without being blocked by the banner

**Comment by DalbertHab** [comment]
Hi amenk,

you can try the pull request #189 with the following config settings:
```
    acceptAll: true,
    hideDeclineAll: true,
    bigButtons: true,
    noticeIsModal: true,
```

The privacy policy exclusion is missing.

**Comment by amenk** [comment]
Great - thanks. I would suggest to just show it in the minimized-way on certain excluded URLs (like privacy policy)

**Comment by maartenmachiels** [comment]
Hi, I'd like to chime in here. Yesterday I followed a workshop about this topic, and they said that, as @amenk suggested, the optimal way would be to force consent upon first visit. 

If a link to our site had an utm_source or something else, this would be dropped after the first request on our site. This would imply that we'd lose specific information.

The option "mustConsent" is great in this perspective. The only issue is that this option immediatly shows all the checkboxes, which I think should only be visible after clicking "my preferences".

Can have the option to do it the way OneTrust does it, i.e. show a simplified cookie popup in the middle of the screen (with three buttons: "accept all", "reject all" and "my preferences"), whilst not allowing the user to ignore the popup, and hide the cookie checkboxes until the user has clicked on "preferences"?

@DalbertHab  can you please clarify if this would be possible?

Thank you for all your work. The recent changes have really had a positive impact. One of my clients reported 60% more traffic in Google Analytics after implementing the "Accept all" button!!

**Comment by maartenmachiels** [comment]
@amenk Great idea concerning the excluded urls. I'm working in October CMS, and in Twig, and my workaround at the moment (based on your suggestion) is:

```
{% if 'legal-info' in this.page.id %}
hideDeclineAll: true, 
bigButtons: true, 
noticeIsModal: true,
{% else %}
mustConsent: true,
{% endif %}
```
Of course this relies heavily on what technology is being used...

**Comment by adewes** [comment]
There are several ways to do this now, e.g. via `noticeAsModal` (which will display the notice as a modal window) or via `mustConsent`, which will directly show the consent modal with all details.
