### ISSUE TITLE
Log-File for consented actions

### ISSUE THREAD

**Issue by basenic** [kiprotect/klaro#198]
Good morning,
i have the following suggestion:

**The problem**
The consent-tool does not have a log-file for the consented actions (time, date, selected options). So it is not possible to retrace when a visitor is demanding evidence that he used the consent-tool.

**Proposed solution**
Native integration of log-file-writing with columns to activate or deactivate.

**Alternative solutions**
Alternatively creating the possibility to react on a consenting visitor, so it is possible to create a write-file-function by ourselves.

**Additional context**
Thank you for this fantastic consent-tool! You are doing an awesome job!

Best regards.

**Comment by ZNicoZ** [comment]
I´m not an expert but I don´t understand your use-case - where do you want to store such a log-file?

Do you know the callback functionality, available for each app?
It looks like the following sample, perhaps you can use it to achieve whatever you are up to :)

```
callback: function (consent, app) {
                // This is an example callback function.
                console.log(
                    'User consent for app ' + app.name + ': consent=' + consent
                );
            },
```
In this implementation, consent state will be logged to the console.

**Comment by basenic** [comment]
Thank you ZNicoZ. I didn't know about the callbacks!
Looking good and i will try it.

**Comment by balduin-kowalski** [comment]
I would also be very interested in such a solution. 
§ 15 DSGVO demands that every vistor of a website has to be able to get a history of the consents he made during his visit. Other ConsentManagers like usercentrics.com provide this in form of a „history-tab“ in the consent-popup.

I guess that for klaro that would mean an essential-cookie has to be set for every session and the history of consents (Action of activating/deactivating each consent with timestamp) has to be saved in it. Maybe that is even possible without reading the log-files?

**Comment by adewes** [comment]
Hey @balduin-kowalski, we have that features in our hosted version now, if you're interested in trying that let me (klaro@kiprotect.com) know and I'll send you an access-code for a free plan. Same offer for everyone else reading on this thread of course :smile:

We can log consent for anonymous users and logged in users (via a token mechanism), the latter is still in beta and not officially available, but will be released in the coming weeks as well.
