### ISSUE TITLE
Change Consent by Javascript Call

### ISSUE THREAD

**Issue by ingoreuter** [KIProtect/klaro#200]
Blocking external iframes (youtube, vimeo, ...) is best practice to respect users' privacy. Isse #157 discusses displaying message instead of the (blocked) iframe. The user can click the message to display consent modal and allow the external content. 

It would be even more convenient to display a message like "Click here to allow external content on this site" an bind the message to an on-click event to set the new consent.

I tried this:
```html
<iframe type="text/plain" data-name="embeddedContent" data-src="<<externalLink>>" data-klaro-processed="blocked"></iframe>
<a href="#" class="external-blocked">Click here to allow external content</a>
```

```javascript
$('.external-blocked).on('click', function() {
	klaro.getManager().updateConsent('external', true)
});
```

Unfortunately `updateConsent()` works only, it the consent window is visible. Maybe Klaro can be extended to something like `klaro.setConsent(app, state)` to set consent immediately.

**Comment by balduin-kowalski** [comment]
Try the callback-function: https://github.com/KIProtect/klaro/issues/190

**Comment by ingoreuter** [comment]
Thanks for your reply. #190 uses the same approach as #157. Both use the ```klaro.show()``` method to show the consent modal and let the user change the consent settings. 

See https://github.com/KIProtect/klaro/issues/190#issuecomment-599535459:
> ``` html
> $(this).parent().addClass("blocked").prepend("<p class='message'><strong>External media blocked</strong><a class='pref' onclick='return klaro.show();'>Change preferences</a><a class='extlink' target='_blank' href='" + extlink + "'>Open on external website</a></p>"); 
> ```

I'm looking for a solution changing the consent **immediately** by clicking an element (e.g. more generally by calling a JavaScript method of the klaro instance) without showing the consent modal first.

As written above, a call of ```klaro.getManager().updateConsent('external', true)``` has no effect unless the consent modal is visible.

**Comment by ingoreuter** [comment]
After some digging in the source code, I've found a solution:
Setting the consent first; saving **and** applying the changes afterwords updates the consent successfully: 

```javascript
klaro.getManager().updateConsent('external', true);klaro.getManager().saveAndApplyConsents();
```
