### ISSUE TITLE
Deactivate attribute async for scripts

### ISSUE THREAD

**Issue by balduin-kowalski** [kiprotect/klaro#201]
On my website I got some scripts which have to be loaded in a certain order. This is messed up if I try to control them with klaro. The reason is, that klaro adds the attribute async to each script by default, it looks like this:

`<script data-src="files/js/tracker-example.js" data-type="application/javascript" data-name="cookietest" type="text/plain" style="" id="" async=""></script>`

Is there a way to deactivate that?

Some other attributes which are also added to each script by default are id and style - I do not think they make much sense for a script…

**Comment by DalbertHab** [comment]
Please have a look at #187

**Comment by adewes** [comment]
Hi @balduin-kowalski, I think this should have been fixed by the updates already, I'm closing this therefore.
