### ISSUE TITLE
Translation for apps title

### ISSUE THREAD

**Issue by pixelina** [kiprotect/klaro#202]
Hi everbody!

I'm implementing Klaro for a multilanguage website and didn't find a way to translate the title for the apps. We use 3 apps (essential, functional, marketing) and they have titles like "Required (give website access)", "Functional (improve the website)" and "Marketing (feature personalised ads)". We need to show this titles in 5 different languages.
It's possible to translate the f.e. app.required.title, but not the app title itself.

My solution now is to generate the full config via PHP, it's a solution, but would be cool if I could translate the text directly in the config file. Is there any way?

Regards,
Ingrid

**Comment by mtvweb** [comment]
Modifying app-item.js line 25 to 

`<span className="cm-app-title">{title || t([name, 'title'])}</span>{requiredText}{optOutText}`

enables the possibility to pass a translated title. The title in the app section has to be unset in this case.

**Comment by rmelchner** [comment]
+1

**Comment by effkah** [comment]
This method doesn't seem to work anymore or am I doing something wrong?

```
translations: {
en: {
system: {            
description: 'You cannot deselect these cookies because we need them to ensure the proper operation of the website.',
title: 'Essential',
},  
},
},
```

**Comment by effkah** [comment]
push

**Comment by effkah** [comment]
push

**Comment by jealouskid** [comment]
Hi, we need that feature as well, but can't get it to work ...

**Comment by sebsoftware** [comment]
You have to build it with node. Find a patched build at 

[https://files.sebsoftware.de/s/EpTPJTFtoxkcyoc](url)

Please remember to drop the title from the app section.

i.E.

```...
translations: {
        // If you erase the "consentModal" translations, Klaro will use the
        // bundled translations.
        de: {
        	consentNotice: {
        		  description: "Wir speichern Informationen (Cookies) für folgende Zwecke: {purposes}."
        	},
            consentModal: {
                description:
                    'Hier können Sie einsehen und anpassen, welche Information wir über Sie sammeln.',
            },
            sessionid: {
            	title : 'Sitzungsdaten',
                description: 'Benötigte Daten zur Sitzungsverwaltung',
            },
            purposes: {
                system: "System",
				...
            },
        },
        en: {
        	consentNotice: {
      		  description: "We are storing data (cookies) for the following purposes: {purposes}."
        	},
            consentModal: {
                description:
                    'Here you can see and customize the information that we collect about you.',
            },
            sessionid: {
            	title : 'Session data',
                description: 'Session data required to manage the current user session',
            },
            purposes: {
                system: "System",
                ...
            },
        },
    },
    
    // This is a list of third-party apps that Klaro will manage for you.
    apps: [
        {
            name: 'sessionid',
            purposes: ['system'],
            required: true,
        },
    ],
...`

**Comment by jealouskid** [comment]
> You have to build it with node. Find a patched build at
> 
> [https://files.sebsoftware.de/s/EpTPJTFtoxkcyoc](url)
> 
> Please remember to drop the title from the app section.
> 
> i.E.
> 
> ```
> translations: {
>         // If you erase the "consentModal" translations, Klaro will use the
>         // bundled translations.
>         de: {
>         	consentNotice: {
>         		  description: "Wir speichern Informationen (Cookies) für folgende Zwecke: {purposes}."
>         	},
>             consentModal: {
>                 description:
>                     'Hier können Sie einsehen und anpassen, welche Information wir über Sie sammeln.',
>             },
>             sessionid: {
>             	title : 'Sitzungsdaten',
>                 description: 'Benötigte Daten zur Sitzungsverwaltung',
>             },
>             purposes: {
>                 system: "System",
> 				...
>             },
>         },
>         en: {
>         	consentNotice: {
>       		  description: "We are storing data (cookies) for the following purposes: {purposes}."
>         	},
>             consentModal: {
>                 description:
>                     'Here you can see and customize the information that we collect about you.',
>             },
>             sessionid: {
>             	title : 'Session data',
>                 description: 'Session data required to manage the current user session',
>             },
>             purposes: {
>                 system: "System",
>                 ...
>             },
>         },
>     },
>     
>     // This is a list of third-party apps that Klaro will manage for you.
>     apps: [
>         {
>             name: 'sessionid',
>             purposes: ['system'],
>             required: true,
>         },
>     ],
> ...`
> ```

Thanks Seb! Works like a charm ...
