### ISSUE TITLE
I am trying to build Dev on my local

### ISSUE THREAD

**Issue by jedidrew42** [KIProtect/klaro#203]
When I try to use NPM install I get errors in my terminal.

I also want to know how to compile the scss and js into the DIst folder. Do you have a build command thats missing from your docs?

Thank you

**Comment by adewes** [comment]
You can have a look at the `.gitlab-ci.yml` file, which contains the build decsription we use to build & test the system in our CI (Gitlab):

https://github.com/KIProtect/klaro/blob/master/.gitlab-ci.yml

It contains information about specific node versions and other packages that we install before building the app, I think it should help you to set up a build environment.

**Comment by jedidrew42** [comment]
We want to use this solution for all of our Hugo static websites. How do I build a local dev environment that can then be modified and pushed into our production and staging?

**Comment by adewes** [comment]
You can build Klaro independently of your static website, there is no need to integrate it into your build pipeline unless you want to build a fork. In that case I would recommend running the build on Gitlab, for which we already have an existing configuration. We cannot provide any guidance on how to build Klaro in other CI infrastructures, the project follows standard Javascript build practices so it should be easy to build. Please refer e.g. to the CI config file mentioned above and the documentation of npm.
