### ISSUE TITLE
Hugo Site: I can’t get the consent manager popup to work

### ISSUE THREAD

**Issue by jedidrew42** [KIProtect/klaro#205]
I installed all the CSS and JS and added my Hubspot third party JS into config.js

I can’t get the consent manager popup to work what I am I missing? Can you please check my site and repo to see what’s wrong. Also I want my consent messages in both EN and DE.

Danke

[click here](https://my-klaro-demo.netlify.app/)

Access to git repo
[click here for repo](https://github.com/jedidrew42/casper-cms-template)

**Comment by adewes** [comment]
You are including the raw Klaro source file, which is not compatible with most browser as it is written in ES6. Please only use the compiled `klaro.js` file as described on the website.
