### ISSUE TITLE
Reload after Save Button in Modal View

### ISSUE THREAD

**Issue by fuzzy20** [kiprotect/klaro#207]
Hi,
In the first modal view that appears, the buttons at the bottom are "Accept selected"/"accept all". When clicking on these buttons the page is reloading. That's perfect!
But when using onclick="return klaro.show() to show the modal view the button at the bottom is a "save" button. The problem is that the page isn't reloading after "save".  Is there a possibility to exchange the "save" button against the "accept selected" button? Or is it possible to add a page reload to the save button?
Thanks a lot for your help!

**Comment by adewes** [comment]
Hey @fuzzy20, sorry for the late reply, I'll answer this nevertheless in case it comes up again in the future. You can use the `callback` function to trigger a page reload, we don't do that by default since it's usually not necessary.
