### ISSUE TITLE
Klaro! and Google Maps

### ISSUE THREAD

**Issue by fuzzy20** [kiprotect/klaro#208]
Hi,
I#m going crazy, slowly but surely!
My Klaro! integration with Google Maps isn't working (YouTube, Google Analytics, ... are working great). This is how the script looks like:
`<script data-src='$file' type='opt-in' data-type='text/javascript' data-name='googleMap'></script>`
and this is the relevant section in klaro_config:
`		{
            name: 'googleMap',
            title: 'Google Maps',
            purposes: ['externalmedia'],
        },`
Can somebody help me, please?

**Comment by manuxi** [comment]
Seems like  type should be "text/plain". "Opt-In" will be added by Klaro.

**Comment by piccto** [comment]
Making Klaro work with Google Maps Api this did the trick for me: add `&callback=initialize` at the end of script.
`<script type="text/plain" data-type="text/javascript" data-name="googleMaps" data-src="https://maps.googleapis.com/maps/api/js?key=XXX&callback=initialize"></script>`
