### ISSUE TITLE
Additional Links

### ISSUE THREAD

**Issue by therealras** [kiprotect/klaro#209]
**The problem**

Is there any possibility to generate 2 additional Links at the bottom of the consent boxes (both) in order to place links to "Imprint" and "Legal Terms". Unfortunately, the consent box covers legal information links that are placed on the website.

**Comment by adewes** [comment]
Hey @andyhausmann and @therealras , have a look at the `extraHTML` translation entry, which you can apply both to the consent notice and the consent modal, and which allows you to put arbitrary HTML there. Let me know if that doesn't resolve your issue, will reopen this then.
