### ISSUE TITLE
Change order of buttons

### ISSUE THREAD

**Issue by Stekowus** [kiprotect/klaro#215]
Hello Klaro-People,

we are looking really forward using your tool. But unfortunately our customer want to change the Decline and the Accept Area in order. Is there any chance that you guys have a non minimized Javascript. So I can change the code? Or a hint how I can change the order?

Would save my day!

Kind regards, Stephanie

<img width="325" alt="Bildschirmfoto 2020-05-26 um 09 54 31" src="https://user-images.githubusercontent.com/35839758/82876831-af3a3080-9f39-11ea-89dc-45cfd368c36a.png">

**Comment by DalbertHab** [comment]
Hi @Stekowus,

please have a look at #183. There is a related PR that you can use to patch the source. To compile the code you can check the .gitlab-ci.yml. Until the PR is merged that the only possibility.

Best regards
David

**Comment by adewes** [comment]
I don't want to force a specific button layout, so we will make this configurable via the config.

**Comment by Werbschaft** [comment]
It's Flexbox, simply define by "order: 1" and "order: 2" with the matching CSS Selectors

**Comment by adewes** [comment]
Buttons are now changed and use flexbox so the order can be easily changed via CSS (thanks @DalbertHab), let me know if that solves your problem, otherwise I'll reopen this.

**Comment by travisbotello** [comment]
> Buttons are now changed and use flexbox so the order can be easily changed via CSS (thanks @DalbertHab), let me know if that solves your problem, otherwise I'll reopen this.

Seems like the CSS/flexbox fix only applies to the buttons inside the modal. The issue described in the OP persists. Any other solutions for this?
