### ISSUE TITLE
Delete Cookies from the website itself?

### ISSUE THREAD

**Issue by Flaschenzug** [kiprotect/klaro#216]
Is there a way to delete cookies from the website itself? I tried to delete a cookie that is not 3rd party. But I assume, the script only works for 3rd party cookies?

`{
            name: 'cookie_notice',
            title: 'cookie_notice Test',
            purposes: ['test123'],
            cookies: ['cookie_notice'],
            optOut: false,
            callback: function(consent, app) {
                // This is an example callback function.
                console.log(
                    'User consent for app ' + app.name + ': consent=' + consent
                );
            },
        },`

**Comment by adewes** [comment]
Hi @Flaschenzug , the script only works for first-party cookies that are Javascript-accessible, HTTP-Only cookies and cookies belonging to different domains can never be accessed by Javascript for security reasons, so we can't delete them.
