### ISSUE TITLE
Javascript function that shows  if a user has given consent to a script

### ISSUE THREAD

**Issue by mr-simba** [kiprotect/klaro#217]
Hello!

Does Klaro! offer a javascript function that shows if a user has given consent to a script?

For example:
I use a local ad server. 
- If a user has given consent to Google Adsense, the adserver should show ads from zoneid 1 (Google Adsense and local hosted ads). 
- If a user has **NOT** given consent to Google Adsense, the adserver should show ads from zoneid 2 (only local hosted ads)

This would be possible with a javascript function that shows if the user has given consent to a script, like this:

<script>
if (klaro.hasAgreed("Adsense")) {zoneid=1;} else {zoneid=2}
</script>

Is something like this possible with Klaro?

**Comment by setcooki** [comment]
we made it directly via the cookie

```
var getCookie = function (name) {
  var value = "; " + document.cookie;
  var parts = value.split("; " + name + "=");
  if (parts.length == 2) return parts.pop().split(";").shift();
};

var hasConsent = function (name) {
  var cookie = getCookie('klaro');
  if (cookie) {
    cookie = JSON.parse(decodeURIComponent(cookie));
    return (cookie && name in cookie) ? cookie[name] : false;
  }
  return true;
}
```

**Comment by mr-simba** [comment]
The following javascript function seems to work:
klaro.getManager().consents.[enter name of script/cookie as used in klaro]

For example:
klaro.getManager().consents.matomo

**Comment by adewes** [comment]
Exactly @mr-simba , glad you found it! We have that in our documentation now as well: https://kiprotect.com/docs/klaro/js_api
