### ISSUE TITLE
it8n: privacyPolicy link language aware?

### ISSUE THREAD

**Issue by tbba** [kiprotect/klaro#220]
I.m.h.o. the privacyPolicy link should also be language-aware?
(If this is possible already via translations:, pls. include an example for this in your example?)

**Comment by d-klx** [comment]
I think this is done in the example config: https://github.com/KIProtect/klaro/blob/master/dist/configs/i18n.js

```
// Put a link to your privacy policy here (relative or absolute).
privacyPolicy: {
	default: '/default-privacy-policy',
	en: '/en-privacy-policy',
},
```

**Comment by adewes** [comment]
Yes this should work.
