### ISSUE TITLE
Placeholders with Consent-Buttons for Apps (like YouTube-iFrame)

### ISSUE THREAD

**Issue by robinson2** [kiprotect/klaro#222]
Is it possible to get approval for individual apps (like inlineTracker, adsense or youTube) via a text link on the website without having to open the complete manager again?

I imagine to integrate e.g. Google-Maps and YouTube placeholder elements, in which I ask for the consent: "Click here to allow the integration of YouTube videos".

And how could I hide such a placeholder after approval?

**Comment by d-klx** [comment]
https://github.com/KIProtect/klaro/issues/200#issuecomment-616227170

**Comment by robinson2** [comment]
… and https://github.com/kiprotect/klaro/issues/190
