### ISSUE TITLE
Klaro! + Matomo's "disableCookies" Feature

### ISSUE THREAD

**Issue by futureweb** [kiprotect/klaro#223]
Hey there,
maybe one of you got an idea on this ... ;-)
In our CMS I can activate Klaro! in my CMS Backend ... when it's activated I also load Matomo with the "disableCookies" Feature ...
```
if($whatever['cookieConsent']==1){
     echo "_paq.push(['disableCookies']);";
}
```
Not quite sure how to re-enable the Cookies if Visitor gave Consent?!?
thx, bye from Austria
Andreas

**Comment by futureweb** [comment]
Hey there,
maybe one of you got an idea on this ... ;-)
In our CMS I can activate Klaro! in my CMS Backend ... when it's activated I also trigger Matomo with the "disableCookies" Feature ...
```
if($whatever['cookieConsent']==1){
     echo "_paq.push(['disableCookies']);";
}
```
Not quite sure how to re-enable the Cookies if Visitor gave Consent?!?
thx, bye from Austria
Andreas

**Comment by d-klx** [comment]
I think you can use the Klaro feature to enable/disable the inline tracking sript as shown on the Klaro! home page (https://klaro.kiprotect.com/#getting-started). In case the user withdraws consent, Klaro! automatically deletes the cookies if you specify them in the config.js.
This way you don't need to use the Matomo functions like 'disableCookies'.

```
       cookies: [
                   [/^_pk_.*$/, '/', 'klaro.kiprotect.com'], //for the production version
                   [/^_pk_.*$/, '/', 'localhost'], //for the local version
                   'piwik_ignore',
       ],
```
I took this from the example configuration here: https://github.com/KIProtect/klaro/blob/master/dist/config.js

**Comment by futureweb** [comment]
Hi @d-klx 
that's the way it's currently implemented in my CMS ... BUT the problem with this is that Matomo is disabled completely when no consent is given ... (as the JS isn't executed at all - no tracking at all)

With Matomo's 'disableCookies' Feature it would still track the Visitor - but with somewhat limited Feature Set ... and without Cookies ... so it would be compliant with Cookie Rules ...

That's why I try to find a Solution using both Features ... ;-)

**Comment by d-klx** [comment]
Ah understood.
You are right, there seems to be no Matomo function to re-enable the cookies.

To re-enable the cookies when consent is given you could just stop using 'disableCookies' and force a page reload with the Klaro callback.
However this solution might have another downside to it, as it seems to be creating a new visitor ID each time the cookie is created: https://github.com/matomo-org/matomo/issues/13056#issuecomment-646250109

**Comment by derSteffen** [comment]
Maybe this colud be do? Untested! But it will be everytime set this code.

`callback: function(consent, app) {
                // This is an example callback function.
				// if (consent == true) {alert ('true: ' + consent)} 
				// if (consent == false) {alert ('false: ' + consent)} 
                // alert('User consent for app ' + app.name + ': consent=' + consent);
				if (consent == false) {
					_paq.push(['disableCookies']);
					_paq.push(['deleteCookies']);
					// location.reload();
					console.log('MATOMO Tracking disabled')
				}
            },`

Please check this solution and give feedback! Maybe there are better ways to delete the Matomo-Cookies!

**The question:** If a User change his settings, that he/she dissalow a service on "my" website .. have to delete this cookies which was saved?

**Comment by futureweb** [comment]
> 
> Please check this solution and give feedback! Maybe there are better ways to delete the Matomo-Cookies!
> 
> **The question:** If a User change his settings, that he/she dissalow a service on "my" website .. have to delete this cookies which was saved?

Guess it won't work as disableCookies needs to be called before trackPageView is used.

But it seems there is some activity from Matomo Side to help with this issue ...
Next Version there will be a "requireCookieConsent" Call - which disabled cookies, then one only needs to call "rememberCookieConsentGiven" once for Matomo to reenable cookies ...

https://github.com/matomo-org/matomo/pull/16178

Guess the Problem is solved once this is live ... ;-)

**Comment by futureweb** [comment]
Short Update here - call Matomo with requireCookieConsent Option:

`_paq.push(['requireCookieConsent']);`

And use this Callback for Matomo within klaro config ...

```
callback : function(consent, app){
   if(consent==true){
       _paq.push(['rememberCookieConsentGiven']);
   } else {
       _paq.push(['forgetCookieConsentGiven']);
   }
}
```
Working like a charm! ;-)

**Comment by adewes** [comment]
Cool, thanks @futureweb ! I just merged your change into master, let me know if that doesn't solve this issue.
