### ISSUE TITLE
Open modal overlay instead of small notice automatically

### ISSUE THREAD

**Issue by basenic** [kiprotect/klaro#226]
Hello,
is it possible to open the modal overlay automatically instead of the small notice in the lower right corner? I could do this with "klaro.show();", but then i have to check if Klaro was already executed before. Maybe there is a built in parameter?

**Comment by basenic** [comment]
Oh...also just checked: klaro.show(); does not open the Modal-Dialog, when the Notice-Box in the bottom right corner is still showing. So it is currently not possible to force it with this command also?

**Comment by piccto** [comment]
`mustConsent: true,`
Put this in your config file and it will open the modal instead of the notice window

**Comment by basenic** [comment]
Thank you piccto for your answer!

**Comment by adewes** [comment]
Thanks for the help @piccto !
