### ISSUE TITLE
Add link to privacy policy to notice

### ISSUE THREAD

**Issue by javalexG** [kiprotect/klaro#227]
Hi,
is it possible to add a link to privacy policy into the description line in cookie notice, in the same way as in the modal? Maybe as an option in config or by adding a placeholder in the description text?
Best regards,

**Comment by pepesale** [comment]
I would need the same feature.
Or alternatively allow html-code in the cookie notice. In that way it would possible to place own custom links.

**Comment by adewes** [comment]
@javalexG and @pepesale , this is now possibly by adding arbitrary HTML to the notice and modal (see the example config). More documentation is coming!
