### ISSUE TITLE
Logo-Image between modal-h1- and p-tag

### ISSUE THREAD

**Issue by basenic** [KIProtect/klaro#228]
I would like to place an individual logo between the modal-h1- and p-tag.

A new translation field (like de>consentModal>title or de>consentModal>description) for an image-path.

Best regards

**Comment by portalzine** [comment]
You can easily add a logo via a CSS pseudo element, using :before.

**Comment by basenic** [comment]
Just to sum it up. Here is my code for anyone interested on including an image below the header:

> .klaro .cookie-modal h1:after {
    background-image: url('../images/fot-logo.svg');
    background-size: 200px 70px;
    display: block;
    width: 200px;
    height: 70px;
	margin: 0 auto;
    content:"";
}
