### ISSUE TITLE
Install via package manager

### ISSUE THREAD

**Issue by florianbouvot** [kiprotect/klaro#23]
Hi, 

Did you plan to publish Klaro on npm ?

Thank you.

**Comment by adewes** [comment]
Hi @florianbouvot !
Can you tell me a bit more about your use case? How would you like to integrate Klaro with other packages using npm? Would you e.g. like to use it as a standalone React component in an existing app?
We'd be happy to offer an npm package we were just not certain how to structure it so far, but if you provide me some feedback I'll be happy to build one.
