### ISSUE TITLE
Missing translation for acceptSelected in klaro-no-css.js

### ISSUE THREAD

**Issue by instantflorian** [kiprotect/klaro#230]
When using klaro-no-css.js instead of klaro.js and the language is set to german, the button "Accept Selected" is not translated (instead a missing translation notice appears).

**Comment by derSteffen** [comment]
Look in the klaro.js
`acceptAll:"Allen zustimmen",`
and change this in
`acceptAll:"Allen zustimmen",acceptSelected:"Auswahl zustimmen",`

**Comment by adewes** [comment]
Can you check if this issue persists with the latest version @instantflorian ?

**Comment by instantflorian** [comment]
It persists in the latest "official" release (0.3.4), since although that release was published just three weeks ago, the assets of that release were last changed on March 11, 2020.
As far as I can see the issue is fixed in the current inofficial release 0.4.3.
