### ISSUE TITLE
How to import klaro with webpack?

### ISSUE THREAD

**Issue by sowinski** [kiprotect/klaro#235]
Hi,

1) How can I import klaro with webpack?

2) How can I import klaro lazy with webpack? I would like to do something like
```
if (cookie not set ...)
{
  import('klaro').then... {
    klaro.open_settings();
  }
}
```

**Comment by adewes** [comment]
Hey @sowinski! We now have an up-to-date version of klaro on `npm`, and we also have [an example](../tree/master/examples/klaro-and-webpack) of how to use Klaro with Node.js and webpack. Please also look at the README for more information. Let me know if you have any more questions!
