### ISSUE TITLE
Add additional link in the modal or in the notice

### ISSUE THREAD

**Issue by derSteffen** [kiprotect/klaro#236]
It is very easy to implement the privacy police in the modal. 

But in germany links to "legal notice" or "terms" should be also easy to find. Is there a possibility in the future to add additional links in the modal or in the notice?

Thanks

**Comment by intradesign** [comment]
I would also very much appreciate it if you could add one or more additional links in the Cookie Notice as well as in the Cookie Modal, like /privacy-policy (already possible) and additionally eg. privacy-policy/cookie-information. Then you could link to more than just the privacy policy.

**Comment by adewes** [comment]
Hi @derSteffen and @intradesign, we've added a way to add arbitrary HTML to the notice and modal, so you can put as many links as you like now :smile:

**Comment by intradesign** [comment]
Hi Andreas,

In addition to HTML in notice and modal, it would also be convenient to be
able to place HTML in the app descriptions. For example, you could link
directly to the privacy policies of third party providers, such as Google
Analytics as done in other consent tools.

Translated with www.DeepL.com/Translator (free version)
*intraDESIGN* / Timo Mackowiak / Husstäenweg 4 / 26629 Großefehn / Tel
0441-55979455 / Mobil 0173-5237884 / timo.mackowiak@intradesign.xyz /
USt-IdNr. DE259414283

Diese E-Mail könnte vertrauliche und/oder rechtlich geschützte
Informationen enthalten. Wenn Sie nicht der richtige Adressat sind oder
diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den
Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die
unbefugte Weitergabe dieser Mail sind nicht gestattet.

THINK before printing!


Am Do., 30. Juli 2020 um 15:20 Uhr schrieb Andreas Dewes <
notifications@github.com>:
