### ISSUE TITLE
Klaro no more building when "npm run make"

### ISSUE THREAD

**Issue by syriaca** [KIProtect/klaro#237]
Hello, I found that klaro is not building when i do "npm run make".
But it does when i do "npm run make-dev"...

Am I the only one having that issue ? Is it possible to solve the problem ?

Below is the error thrown in the console:

λ npm run make

> klaro@0.3.2 make D:\Leetchi\Klaro\klaro
> cross-env APP_ENV=production cross-env APP_VERSION=$(git tag --points-at HEAD) cross-env APP_COMMIT=$(git rev-parse HEAD) webpack --config webpack.config.js

'tag' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn tag ENOENT
    at notFoundError (D:\Leetchi\Klaro\klaro\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (D:\Leetchi\Klaro\klaro\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (D:\Leetchi\Klaro\klaro\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (D:\Leetchi\Klaro\klaro\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn tag',
  path: 'tag',
  spawnargs: [
    '--points-at',
    'HEAD)',
    'cross-env',
    'APP_COMMIT=$(git',
    'rev-parse',
    'HEAD)',
    'webpack',
    '--config',
    'webpack.config.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! klaro@0.3.2 make: `cross-env APP_ENV=production cross-env APP_VERSION=$(git tag --points-at HEAD) cross-env APP_COMMIT=$(git rev-parse HEAD) webpack --config webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the klaro@0.3.2 make script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-07-03T16_04_41_150Z-debug.log`

**Comment by adewes** [comment]
It seems git is not installed on your system? Please make sure you have an up-to-date git installation.

**Comment by syriaca** [comment]
I've updated my node and git installation to latest... the problem is still there...
