### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by UniversalDesignz** [kiprotect/klaro#238]
Hi guy's,

I am sure this can not be to difficult to install and execute the klaro on to any site can you kindly provide with instruction how to do implement and execute this to a website.

Currently the box on the right shows up but doesn't do anything non of the buttons work.

Thank you in advance.

Kindest Regards
Jay 

If you have a support question, feel free to ask it here.

Before submitting a new question, please make sure you:

- Read [the introduction](https://klaro.kiprotect.com).
- Searched opened and closed [GitHub issues](https://github.com/KIProtect/klaro/issues?utf8=%E2%9C%93&q=is%3Aissue).

**Comment by adewes** [comment]
There are several examples on our [website](https://klaro.kiprotect.com) (in fact, the entire website is an example of how to use Klaro) and in the [examples directory](../tree/master/examples) of this repository. We are also working on a more extensive documentation, please stay tuned for that!
