### ISSUE TITLE
Two spaces in front of privacy policy text

### ISSUE THREAD

**Issue by Henning-IG** [kiprotect/klaro#239]
**Two spaces in front of privacy policy**

Small issue: There are two spaces between the texts "description" and "privacy policy" in the consent modal. I can't get rid of them. Is more visible with other styles. Would be even nice to insert a line break optionally.

**Steps to reproduce**

- go to https://klaro.kiprotect.com/
- click "Show manager"
- Search for "website.  To"

**Current behavior**

There are two spaces between "website." and "To".

**Expected behavior**

There must be just one space.

**Comment by adewes** [comment]
Thanks for the catch, @Henning-IG ! It's fixed in the new release.
