### ISSUE TITLE
Latest version not available on NPM

### ISSUE THREAD

**Issue by dahaupt** [kiprotect/klaro#240]
I'd like to include the library via npm to easily get updates. Currently, only version 0.2.20 is available on npm.

Is this situation intended? Thanks for any response!

**Comment by sowinski** [comment]
Would be nice if the current version could be published on npm and please don't forget to add the src folder to npm as well :)

**Comment by adewes** [comment]
Yes we'll work on that and automate the deployment to npm as well!

**Comment by adewes** [comment]
The newest version is always available on npm now, @dahaupt!

**Comment by dahaupt** [comment]
@adewes Thanks. Have a nice day! :slightly_smiling_face:
