### ISSUE TITLE
missing translation

### ISSUE THREAD

**Issue by peitman** [kiprotect/klaro#250]
In the Button "Accept selectet" ist this text "[missing translation: de/acceptSelected]"

What is wrong?

**Comment by peitman** [comment]
Hello, here are the Files an the URL to the Website: www.bema-tech.de
[klaro.js.txt](https://github.com/kiprotect/klaro/files/4951597/klaro.js.txt)
[config.js.txt](https://github.com/kiprotect/klaro/files/4951599/config.js.txt)

**Comment by adewes** [comment]
It seems correct to me, the entry for the translation is also present in the translations files. Can you try to upgrade to 0.4.2 (which we just released) and see if the problem still persists?

**Comment by peitman** [comment]
Hello, thank you for your mail. With the update to 0.4.2 the error message has disappeared.

Thank you an have a nice Weekend.

 

 

Freundliche Grüße I Best regards

Dirk Peiter

 

pdesign-media I dirk peiter

ringstraße 14

56218 mülheim-kärlich

 

m: 0171 4737050

info@pdesign-media.de <mailto:info@pdesign-media.de>  

 

www.pdesign-media.de <http://www.pdesign-media.de> 

 

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

 

 

Von: Andreas Dewes <notifications@github.com> 
Gesendet: Mittwoch, 22. Juli 2020 17:18
An: kiprotect/klaro <klaro@noreply.github.com>
Cc: peitman <info@pdesign-media.de>; Author <author@noreply.github.com>
Betreff: Re: [kiprotect/klaro] missing translation (#250)

 

It seems correct to me, the entry for the translation is also present in the translations files. Can you try to upgrade to 0.4.2 (which we just released) and see if the problem still persists?

**Comment by adewes** [comment]
Ok great! I deleted you last message @peitman as it contained your e-mail address and personal data btw.
