### ISSUE TITLE
Missing build of klaro-no-css.js in 0.4.1

### ISSUE THREAD

**Issue by kulmjens** [kiprotect/klaro#255]
In Version 0.4.1 I see an `target="_blank"`attribute added to the privacyPolicy link.

https://github.com/kiprotect/klaro/blob/92ec06c1525776253dff905e49eef8ace0094a5e/src/components/consent-modal.js#L44

But the file `dist/klaro-no-css.js` seems to not having it.

Also `dist/klaro-no-css.js` is of 12.5.20, while `dist/klaro.js` is of 10.7.20.

Could you please build the 0.4.1 version of `klaro-no-css.js` and do an additional release?

**Comment by adewes** [comment]
There was  a problem with the build process due to a linting error, I've fixed that and triggered a deployment of a new version (0.4.2), it should be up shortly @kulmjens.

**Comment by kulmjens** [comment]
But the file `klaro-no-css.js` didn't change in 0.4.2 or 0.4.3.
It's still the version of 12.5.20 without the target attribute.

**Comment by kulmjens** [comment]
Still in Version 0.4.4 the target attribute is missing in `dist/klaro-no-css.js`.

In `dist/klaro.js` there is this code part:
`s.privacyPolicy.default||s.privacyPolicy,v=ce("a",{onClick:o,href:m,target:"_blank",rel:"noopener noreferrer"},`

In `dist/klaro-no-css.js` there is only this part:
`u.privacyPolicy.default||u.privacyPolicy,y=ke.createElement("a",{onClick:o,href:v},`

Or am I missing something?
