### ISSUE TITLE
klaro.js:9 Uncaught TypeError

### ISSUE THREAD

**Issue by pixelbreit** [kiprotect/klaro#256]
Unfortunately I get an error with klaro version v0.4.4. 
The GitHub Master example is also affected. 
Version 0.4.3 works fine

Mozilla Firefox Console shows the following: 
`klaro.js:9 Uncaught TypeError: r.imprint is undefined`
and Google Chrome: 
`klaro.js:9 Uncaught TypeError: Cannot read property 'default' of undefined`

**Comment by adewes** [comment]
The `dist` files were  not up to date, I just fixed that.
