### ISSUE TITLE
Klaro does not start on website

### ISSUE THREAD

**Issue by flosse1968** [kiprotect/klaro#257]
Hello, I have often tried to perform the configuration according to the instructions. I correctly specified the paths for the config.js and Klaro.js in the html in the footer area and saved the files in the correct path. Unfortunately nothing happens when the website starts. I can't find any further instructions anywhere, can someone give me a tip on what I have forgotten? Kind regards Jens

**Comment by adewes** [comment]
Can you point me to your website or provide the source? It's hard to debug without any further information.

Here are some general tips on how to debug this: As a first step, you might want to open your developer tools, go to the network tab and check that `klaro.js` gets correctly loaded. Then, open your console (also in the developer tools) and check if there are any Javascript errors. Then, check if typing `klaro` into the console prompt returns an object. Finally, make sure your DIV IDs matches the one in your configuration.

**Comment by flosse1968** [comment]
Hello adewes, thanks a lot for your response, enclosed please find the index.html and javascript files. The files ar located in the root. I read that no modfications on both files are necessary isn´t? I chose the tool because it is easy to integrate. 
[index.zip](https://github.com/kiprotect/klaro/files/4980891/index.zip)
[config_klaro.zip](https://github.com/kiprotect/klaro/files/4980901/config_klaro.zip)

**Comment by adewes** [comment]
It seems you've included the Klaro source code, which cannot be loaded in the browser. Please include the file linked on the website (https://klaro.kiprotect.com) or from the `dist` folder in the repository. There is a version with CSS intergrated (`klaro.js`) and one without CSS (`klaro-no-css.js`).

**Comment by adewes** [comment]
Since this seems to happen frequently and is hard to debug for someone without experience with JS I've also added a note in the README so that it hopefully won't happen again. Let me know if the integration works with the correct file, if not please reopen this issue!

**Comment by flosse1968** [comment]
Thank you!!! it works, sorry for this stupid mistake ... :-)

**Comment by adewes** [comment]
No worries it can happen :) I've added some more information to make sure people download the correct files.
