### ISSUE TITLE
Configurable button classes

### ISSUE THREAD

**Issue by dahaupt** [kiprotect/klaro#258]
**The problem**
We want to retain the existing CI style of a website in all Klaro UI elements. Using the provided scss files and changing some variables there is a good starting point. But reusing existing classes would be way easier then overwriting or removing the provided scss configuration of klaro.

**Proposed solution**
Add the possibility to configure classes of buttons in `klaroConfig`.

**Alternative solutions**
I could also imagine to include some presets for popular CSS frameworks like Bootstrap or Tailwind.

**Comment by adewes** [comment]
Thanks for creating this issue @dahaupt! I'm wondering if it would not be sufficient to add a rule for `cm-btn` to your own CSS? This enables you to overwrite all the styles that you'd like to modify and leave everything else untouched. You can achieve this without relying on `!important` directives if you wrap the Klaro `div` in another class (e.g. `my-klaro-style`) and then specify your CSS as `.my-klaro-style .cm-btn`). Would that not work for you?

I'm a bit hesitant to add configuration if an existing mechanism is sufficient to address a need, as having more config options makes the software more error-prone and complex. Happy to hear your feedback on this though!

**Comment by dahaupt** [comment]
Hey @adewes, thanks for your reply. I think that your proposed approach is sufficient for the time being, as long as the topic is not addressed by further users. 

Of course it would be easier and more comfortable if we could e.g. customize the HTML template to add or change classes. 

I do not like **redefining existing** CSS rules, but using SASS at least allows us to use `@extend` mechanism to not have duplicated rules.
