### ISSUE TITLE
Custom stylePrefix

### ISSUE THREAD

**Issue by gregBerthelot** [KIProtect/klaro#26]
Hi

Where can we set the stylePrefix value for `<div className={stylePrefix}>`?

Thanks
Greg

**Comment by adewes** [comment]
You can add this as a data attribute to the `script` that in which you load Klaro, like this:

    <script src="klaro.js" data-style-prefix="my-prefix"></script>

Let me know if that shouldn't work or if you encounter any other problems.

**Comment by gregBerthelot** [comment]
Works like a charm :) thanks a lot
