### ISSUE TITLE
Undefined Error with TrustedShop Badges

### ISSUE THREAD

**Issue by simkea** [kiprotect/klaro#260]
If the snippet loads the external javascript (//widgets.trustedshops.com/js/ tsid .js), there is a conflict.

**Steps to reproduce**
Add this Code to Markup with a valid TSID

`
 (function () {
                    var _tsid = 'XXXXXXXXX';
                    _tsConfig = {
                        'yOffset': '250', /* offset from page bottom */
                        'variant': 'reviews', /* text, default, small, reviews, custom, custom_reviews */
                        'customElementId': '', /* required for variants custom and custom_reviews */
                        'trustcardDirection': '', /* for custom variants: topRight, topLeft, bottomRight, bottomLeft */
                        'customBadgeWidth': '', /* for custom variants: 40 - 90 (in pixels) */
                        'customBadgeHeight': '', /* for custom variants: 40 - 90 (in pixels) */
                        'disableResponsive': 'false', /* deactivate responsive behaviour */
                        'disableTrustbadge': 'false', /* deactivate trustbadge */
                        'trustCardTrigger': 'mouseenter', /* set to 'click' if you want the trustcard to be opened on click instead */
                        'customCheckoutElementId': '' /* required for custom trustcard */
                    };
                    var _ts = document.createElement('script');
                    _ts.type = 'text/javascript';
                    _ts.charset = 'utf-8';
                    _ts.async = true;
                    _ts.src = '//widgets.trustedshops.com/js/' + _tsid + '.js';
                    var __ts = document.getElementsByTagName('script')[0];
                    __ts.parentNode.insertBefore(_ts, __ts);
                })();
`

![image](https://user-images.githubusercontent.com/612913/88915060-e5f73480-d263-11ea-97fc-d302358a26d5.png)

![image](https://user-images.githubusercontent.com/612913/88915256-3c647300-d264-11ea-9334-a528ffed3bda.png)

**Comment by adewes** [comment]
Hm I can't really debug this with that information. Could you provide a complete snapshot of the code (HTML + JS)?

**Comment by adewes** [comment]
It seems to work fine for me with the latest Klaro and the following HTML (from our webkit example):

```html
<!doctype html>
<html>
  <head>
    <style>
      body {
        font-family: Arial, Helvetica, sans-serif;
      }
    </style>
    <meta charset="utf-8"/>
    <title>Klaro as a script</title>
    <script src="main.js"></script>
    <script data-type="text/javascript" type="text/plain" data-name="trustedShops">
      (function () { var _tsid = 'xxxxxxxxxx'; _tsConfig = { 'yOffset': '250', /* offset from page bottom */ 'variant': 'reviews', /* text, default, small, reviews, custom, custom_reviews */ 'customElementId': '', /* required for variants custom and custom_reviews */ 'trustcardDirection': '', /* for custom variants: topRight, topLeft, bottomRight, bottomLeft */ 'customBadgeWidth': '', /* for custom variants: 40 - 90 (in pixels) */ 'customBadgeHeight': '', /* for custom variants: 40 - 90 (in pixels) */ 'disableResponsive': 'false', /* deactivate responsive behaviour */ 'disableTrustbadge': 'false', /* deactivate trustbadge */ 'trustCardTrigger': 'mouseenter', /* set to 'click' if you want the trustcard to be opened on click instead */ 'customCheckoutElementId': '' /* required for custom trustcard */ }; var _ts = document.createElement('script'); _ts.type = 'text/javascript'; _ts.charset = 'utf-8'; _ts.async = true; _ts.src = '//widgets.trustedshops.com/js/' + _tsid + '.js'; var __ts = document.getElementsByTagName('script')[0]; __ts.parentNode.insertBefore(_ts, __ts); })();
    </script>
  </head>
  <body onload="klaro.show(config);">
    <h1>Klaro Example</h1>
    <p>
      This is a simple example that shows how to embed Klaro in your own JS
      app. Normally only your script has access to Klaro, here we explicitly
      assign it to the "window" object inside "index.js" so that we can show
      the manager, which would usually be done by your app.
    </p>
    <button onClick="return klaro.show(config);">show manager</button>
    <button onClick="klaro.getManager(config).resetConsent();klaro.show(config);">reset consent</button>
  </body>
</html>
```

The Klaro config looks as follows:

```js
const config = {
    translations: {
        en: {
            trustedShops: {
                title: "Trusted Shops",
                description: "The trusted shops seal.",
            },
            purposes: {
                marketing: "Marketing",
            }
        }
    },
    default: true,
    apps: [
        {
            name: "trustedShops",
            purposes: ["marketing"],
        },
    ],
    privacyPolicy: "",
};

```

**Comment by simkea** [comment]
Thx, i have an Magento 1 System with old prototype Version 1.7 library.
I believe the problem is this definition:

  function toArray() {
    return this.map();
  }

**Comment by simkea** [comment]
Okay i solved the Problem:

in the prototype library changed code to:

`  function toArray() {
      if (typeof this.isArray === 'undefined') {
        return [];
      }
      return this.map();
  }`

**Comment by pragmaticMartin** [comment]
I have a similar issue at the moment but witg amgento 1.9 . The prototype js fix didnt work for me. Any Sugestions?

**Comment by adewes** [comment]
Hey @pragmaticMartin, we need a working URL to look at, otherwise this is impossible to debug.

In general we can't take responsibility for the environment in which you install Klaro. I would start by removing/disabling your other JS scripts one by one to identify the problem, often it's a function that overwrites JS functionality that Klaro relies on. Unfortunately we don't have a way to defend against this as we need to assume Klaro is being run in a standard-compliant JS environment.
