### ISSUE TITLE
Checking Satus for an app

### ISSUE THREAD

**Issue by intradesign** [kiprotect/klaro#263]
Hi there!

It is also possible to query the status for an app with a javascript call as it is possible to set it, such as whether approval has been granted for YouTube, in order to use the result for content output. I have seen the callback function, but when I want to play back more complex content with it, it is quite uncomfortable. I can integrate this into the templates of the Content Management System very easy, using the callback function for this is quite cumbersome.

What I want to achieve is:
If the approval has not been given yet, e.g. show a placeholder image, if it has been given show the Youtube iFrame as usual.

Thanks and best regards,
Timo

**Comment by adewes** [comment]
Hi @intradesign! You can use the consent manager object to do that. Please have a look at our new documentation website: https://kiprotect.com/docs/klaro/js_api, you can e.g. use `klaro.getManager().getConsent("app-name")` or `klaro.getManager().consents` to get all consents. Please note that these consents reflect the current selected state (which might have been changed by the user), if you are interested in the consents that were applied you can use `klaro.getManager().savedConsents`, which contains the consents that have been saved when the user clicked on "Accept" or "Decline".
