### ISSUE TITLE
Multiple privacy policy links

### ISSUE THREAD

**Issue by user123801** [kiprotect/klaro#264]
I want to use klaro on a multilingual website with one privacy policy link per language. While I could use JS to alter the link/config based on the html tag's lang attribute, I'm wondering if there's a better way. Is it possible to add more than one of those links to the config?
https://klaro.kiprotect.com/config.js Can't find it in this config, so...

**Comment by intradesign** [comment]
**You can add urls for multiple languages in the config.js like this:**

```
// Put a link to your privacy policy here (relative or absolute).
    privacyPolicy: {
        default: '/de/datenschutzerklaerung',
        de: '/de/datenschutzerklaerung',
        en: '/en/privacy-policy',
        fr: '/fr/confidentialite',
        es: '/es/politica-de-privacidad',
        hu: '/hu/adatvedelmi-tajekoztato',
        pl: '/pl/ochrona-prywatnosci',
        ro: '/ro/declaratia-de-confidentialitate', 
},

```

**Comment by user123801** [comment]
@intradesign Thank you, will do it that way, then.

**Comment by adewes** [comment]
Thanks for the help @intradesign !
