### ISSUE TITLE
Block complete <div>

### ISSUE THREAD

**Issue by intradesign** [kiprotect/klaro#265]
Is it also possible to block complete `<div>`s containing scripts / thirdparty elements? In this special case a openstreetmap is loaded by a javascript but the script is only a part of the code that also contains elements needed by the map. This code structure is given by the template of an extension of the CMS.

It`s like that:
```
<div> // block this!
   <div>
      some html
      <div>
         some more html
      <div>
      <script 1 to be blocked>
   </div>
   <script 2 to be blocked>
<div>

```

**Comment by nussisworld** [comment]
Hi, 

we do it like that:

`apps: [
	
	{
			name: 'marketing',
			title: 'Marketing',
			purposes: ['marketing'],

			callback: function(consent, app) {
				
				

				var consentcheck = app.name + consent;
				
	 var map_replace = '<div class="card text-white bg-blue mb-3"><div class="card-header h4">Hier wurde eine Land-/Straßenkarte blockiert: Bitte aktiviere "Marketing Cookies"</div><div class="card-body text-center"><h5 class="card-title">Wir brauchen Dein Einverständnis!</h5><p class="card-text">Wir benutzen Kartenmaterial von Open Streetmap. Dadurch können persönliche Daten über Deine Aktivitäten gesammelt werden. Du kannst diese Karte sehen, wenn Du in unseren Cookie-Einstellungen "Marketing" aktivierst.</p><p class="card-text"><button type="button" class="btn btn-lg btn-danger" onClick="klaro.show();return false;">Cookie Einstellungen</button></p></div></div>';
                
				if (consentcheck == "marketingfalse") {
				
 	    
	$(map_replace).insertBefore( ".jrMapModule" );
  	$('.jrMapModule').remove();
	$(map_replace).insertBefore( "#jr-map-layout" );
	$('.jr-directions-address').remove();
	$('.jr-map-canvas').remove();				
				
				} else {
					$('iframe').each(function() { 
						$(this).parent().removeClass("blocked").find(".message").remove();  
					});
				} 
			},
		},`

Explanation:

`<div class="jrMapModule"> // block this!
   <div>
      some html
      <div>
         some more html
      <div>
      <script 1 to be blocked>
   </div>
   <script 2 to be blocked>
<div>`

The script is searching for the class "jrMapModule". If there is no consent for the cookie category "marketing" it will replace this code with the html from "var map_replace". 

Please try it.

**Comment by nussisworld** [comment]
Explanation:
`<div class="jrMapModule"> 
   <div>
      some html
      <div>
         some more html
      <div>
      <script 1 to be blocked>
   </div>
   <script 2 to be blocked>
<div>`
The script is searching for the class "jrMapModule". If there is no consent for the cookie category "marketing" it will replace this code with the html from "var map_replace". 

Please try it.

**Comment by adewes** [comment]
Thanks for the help @nussisworld ! For the next iteration of Klaro we will add more functionality to block iframes or divs. Let me know if you still have an issue with this, will reopen this then.
