### ISSUE TITLE
Required scripts/cookies autoloads without consent.

### ISSUE THREAD

**Issue by MasterIceFLash** [kiprotect/klaro#266]
**Klaro Config**

```
var klaroConfig = {
    elementID: 'klaro',
    storageMethod: 'localStorage',
    cookieName: 'klaro',
    cookieExpiresAfterDays: 1,
    privacyPolicy: '/privacy.html',
    default: false,
    mustConsent: true,
    acceptAll: true,
    hideDeclineAll: false,
    hideLearnMore: false,

        {
            name: 'adsense',
            title: 'Google AdSense',
	    default: false,
            purposes: ['advertising'],
            onlyOnce: true,
            required: true,
        },
```

**HTML Code of Page**

`<script async type="text/plain" data-type="text/javascript" data-name="adsense" data-src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>`
<br /><br />

**Current behavior**

If I set the required tag = true, the scripts are beeing executed automaticly without User Interaction.
In this Case the whole adsense code is beeing executed instantly as the Klaro.js script loads.
If the Required tag is not set, its not loading automaticly.

**Expected behavior**

It shall not load the Cookies/Trackers even when they are required. The User should still can go away/quit Window without to accept and stay private.

In Some other cases it could be useful to load required scripts without consent but not in mine.

**Comment by adewes** [comment]
Hi @MasterIceFLash! Setting an app to `required` means that it is needed for the proper functioning of the page, so Klaro enables it by default and executes it right away. I think you should use `default : true` to indicate that an app should be loaded by default if the user clicks on "Accept". Let me know if that solves your problem!

**Comment by adewes** [comment]
Let me know if this is still an issue, will reopen this in that case.
