### ISSUE TITLE
How to open modal window via link if notice is still open?

### ISSUE THREAD

**Issue by robinson2** [kiprotect/klaro#267]
If there's a link like `This video is blocked by your settings – <a onClick="klaro.show();return false;">manage your consents</a>` the user can reopen the settings to adjust those. But if the user has not closed the notice window before clicking on this link, nothing happens. How can I force switching from notice to modal window in this case?

I tried a few things like `onclick="klaro.getManager().showModal();"` on the off chance, but didn't find a solution.

**Comment by adewes** [comment]
Hi @robinson2! We will add a way to force opening the modal, right now the logic is that if the notice is open the modal shouldn't be opened, but it seems that doesn't cover use cases like yours. I'll get back to you with an update very soon.

**Comment by adewes** [comment]
Hi @robinson2! You can now force the opening of the modal by calling `klaro.show(undefined, true)` (first parameter is your config, which is automatically inferred if not given). Let me know if that shouldn't work! It should be deployed and available on npm in a few minutes.

**Comment by robinson2** [comment]
This works great, thank you very much!

**Comment by 01Kuzma** [comment]
Hi!
A lot of time has passed.
What is the best solution to call the modal window with a HTML button after the consent was given?
It is the `<a onClick="klaro.show();return false;">manage your consents</a>` a solution ?
