### ISSUE TITLE
Modal &nbsp inside privacyPolicy text

### ISSUE THREAD

**Issue by sebastiancx** [kiprotect/klaro#272]
**Klaro Config**
![grafik](https://user-images.githubusercontent.com/25252089/90241885-3c4fa000-de2c-11ea-8d21-9f0eaa0c0160.png)

**HTML Code of Page**
![grafik](https://user-images.githubusercontent.com/25252089/90241426-4f15a500-de2b-11ea-9b14-a441d7796ba9.png)

**Steps to reproduce**
/

**Current behavior**
Unfortunately, we noticed that there is a failed break when using Klaro. Between the consentModal description and the privacyPolicy text there is a &nbsp by default (see screenshot above), but this does not help. If you want to put a \n or <br/> in one of them, it won't work either.

**Expected behavior**
To get a break inside the consentModal description or privacyPolicy text.

**Comment by adewes** [comment]
Hi @sebastiancx, so you want to get a line break in your description text? In that case you could use the `extraHTML` translation key (see example config), which you can pass HTML to. You can put empty strings in the `description` and `privacyPolicy` in that case.

**Comment by sebastiancx** [comment]
Thanks @adewes, that works so far, but when i make the description and privacyPolicy empty, the <p> tag is still there with the &nbsp in it...

![grafik](https://user-images.githubusercontent.com/25252089/90242969-50949c80-de2e-11ea-89d5-8954f7e19bb2.png)
![grafik](https://user-images.githubusercontent.com/25252089/90243077-83d72b80-de2e-11ea-951a-410c99490ffa.png)

**Comment by adewes** [comment]
Hey @sebastiancx, we just fixed this and improved the way you can render HTML in the consentNotice. The new version (`0.5.32`) now supports setting the `htmlTexts` config option, which allows you to write plain HTML in the consent notice and modal, so there's no need for the `extraHTML` fields. The `&` is also gone :D Let me know if that solves your problem, if not I'll reopen this!

**Comment by adewes** [comment]
The new release should be online in 5-10 minutes.
