### ISSUE TITLE
Info: Aggregated JS and IE11

### ISSUE THREAD

**Issue by kulmjens** [kiprotect/klaro#273]
I'm working with 0.4.27 and have a JS error in IE11 on a site that uses aggregation of js files (in my case Drupal 7).

As IE11 doesn't understand `document.currentScript` the klaro library goes through all scripts and looks for the string `klaro` in their src-attributes. But with aggregation turned on, the sources of the the aggregated scripts are now hashed names which do not inlcude the string `klaro` anymore. So the klaro library can't start itself and throws an error like `cannot use getAttribute on a null value`.

In my case it was enough to exclude the klaro library from aggregation.

**Comment by adewes** [comment]
Hi @kulmjens ! Thanks for reporting that bug, this shouldn't happen of course. I think we can implement a workaround for this by e.g. looking for a specific data attribute instead. I'll get back to you shortly!

**Comment by kulmjens** [comment]
Hi @adewes!
In Drupal 7 the easy workaround was, to exclude the klaro.js / klaro-no-css.js from the js-files beeing aggregated. It's done with a `preprocess = FALSE` either in hook_library or drupal_add_js().
I don't know exactly if the aggregation in Drupal is able to add data-atributes to the aggregated script-tags.

**Comment by adewes** [comment]
Ok, great you have found a workaround! Still it would be nice to be able to bundle Klaro with other scripts, so I'll think about it. Thanks for the info in any case!
