### ISSUE TITLE
Fn.delete is not a function if call resetManagers()

### ISSUE THREAD

**Issue by vanderb** [kiprotect/klaro#275]
Hi,

if I call the resetManagers-method i get following error

```
TypeError: Fn.delete is not a function
    at Module.Vn (klaro-no-css.js?b076:4)
    at Object.resetManagers (klaro.js?9c3b:59)
```

Searched the files here in the repo. The method is defined in `src/klaro.js` Line 89.
Error caused by following code `managers.delete(key)` Line 91.

`managers` could be one of possible types: object or ConsentManager, none of them have a delete-method.

Can you verify that?

Thank you.

**Comment by adewes** [comment]
Thanks for reporting this @vanderb , this is fixed, new release will be up in 10 minutes!
