### ISSUE TITLE
Allow language based styling of dialoges

### ISSUE THREAD

**Issue by ronald** [kiprotect/klaro#276]
**Thanks**

Thank you for providing klaro :-)

**The problem**

We'd like to style klaro different dependent on klaro.language()
A simple way would be to use css selectors like
`#klaro:lang(en) {} `
but this requires lang="en" attribute on `<div id="klaro">`

**Proposed solution**
Add `lang="{value of config.lang}"` to `<div id="klaro">`

**Comment by adewes** [comment]
Hm, couldn't you just set

```
html:lang(de) #klaro {
....
}
```

to achieve that?

**Comment by ronald** [comment]
We have a german site using english klaro to get consent.
Afterwards we use google translator to translate to english.

**Comment by adewes** [comment]
Ok, that's quite interesting. I added the `lang` attribute to the `div` and added an `additionalClass` config option that you can use to give the Klaro div an additional class (or classes), should be up in a few minutes.
