### ISSUE TITLE
App title translation

### ISSUE THREAD

**Issue by gregBerthelot** [KIProtect/klaro#28]
@adewes we can translate app description in config but it seems that we can't add app title translation. Am i wrong?

```
translations: {
    en: {
        security : {
            description: 'DDos attack protection',
            title: 'Website security' // Does not work
        }
    }
}
```

**Comment by gregBerthelot** [comment]
Fixed by changing `<span className="cookie-modal-app-title">{app.title}</span>{requiredText}{optOutText}` to `<span className="cookie-modal-app-title">{t([app.name, 'title'])}</span>{requiredText}{optOutText}` in apps.js L63

**Comment by robinson2** [comment]
Could you reopen this issue? The possibility to translate the title does not seem to be implemented yet and the mentioned workaround is no longer up to date if I did not miss anything.

**Comment by effkah** [comment]
push
