### ISSUE TITLE
hideLearnMore Missing

### ISSUE THREAD

**Issue by labatt** [kiprotect/klaro#284]
**Klaro Config**

```
var klaroConfig = {
    elementID: 'klaro',
    htmlTexts: false,
    embedded: false,
    groupByPurpose: true,
    storageMethod: 'cookie',
    cookieName: 'cookieconsent',
    cookieExpiresAfterDays: 365,
    privacyPolicy: '/privacy',
    default: true,
    mustConsent: false,
    acceptAll: true,
    hideDeclineAll: true,
    hideLearnMore: true,
    noticeAsModal: false,
    translations: {

```

**Current behavior**

I noticed that when setting hideLearnMore to true the "Customize..." link still showed up. I searched the code here on GitHub and couldn't find any code in the current codebase that does anything with "hideLearnMore".

**Comment by adewes** [comment]
Hey @labatt, thanks for reporting this. Seems the `hideLearnMore` setting is indeed obsolete and we simply forgot to remove it from the example config, I'll do that with the next release.

**Comment by labatt** [comment]
Was not the answer I was hoping for lol. We want to launch klaro with a simple accept button and then enable the ability to pick your cookies later. Any new option for this or is css the approach at this point?

**Comment by adewes** [comment]
Ah I see. We could add that option again, as long as there's a way to decline consent it's still a compliant flow, although it's always preferable to have the "customize" option IMHO (as it also doesn't take away additional vertical space). Is the Klaro cookie notice still too big for your needs?

**Comment by ckidow** [comment]
+1 for adding this again

**Comment by adewes** [comment]
Hey @ckidow and @labatt ! The `hideLearnMore` works again and we added a way to show the `learnMore` link in the consent notice text (if desired), thanks to @sichgeis . 

The new version `0.6.5` incorporates all these changes and is available for download, let me know if you have any further questions or remarks about this or if something shouldn't work.
