### ISSUE TITLE
Missing klaro.js and css in dist folder

### ISSUE THREAD

**Issue by intradesign** [kiprotect/klaro#285]
Hello everyone,
since a short time i miss the files klaro.js and the CSS file in the download directory under /dist.

Therefore the provided example file index.html does not work anymore, because the local versions of the klaro files are referenced there (which are missing).

Should Klaro! now only be integrated via CDN?

I would consider this a "step back" if one would rather embed Klaro! locally than via the CDN.

What is the intention behind this?

Many thanks and best regards
Timo

**Comment by adewes** [comment]
Hi @intradesign, yes we don't include them in the source tree anymore, if you want to run the local examples you just need to run `make build` first, this will generate all necessary files in the `dist` directory. I'll update the example code to use the CDN versions of Klaro.

**Comment by adewes** [comment]
The intention was that including the transpiled JS files caused unnecessary headaches when merging pull requests and I and other collaborators sometimes forgot to update the dist files when pushing new commits, so they were not always in sync with the source files. So I thought it would be best to not include them in the source tree anymore.

**Comment by adewes** [comment]
Hey @intradesign, it seems I underestimated how many people look for distribution files in the repo, so I added the files again.

**Comment by intradesign** [comment]
Hi adewes, it looks like many of us are not developers.

I wouldn't even know how to create the files myself. I am just glad that there is such a good open source consent script that I can embed on websites and only have to modify the configuration.

So at this point, thank you very much for your efforts and continuous development!
