### ISSUE TITLE
Except some cookies from the "Accept all"-configuration

### ISSUE THREAD

**Issue by saschafoerster** [kiprotect/klaro#289]
I would like to keep using the "Accept all"-button, but then, there are some cookies that I only want to allow, when they where explicitly und individually accepted through the consent modal. So I wish for a kind of "AcceptAllException"? :) 

A concret example: Right now there is a button to accept all social media embeddings from Facebook, Twitter, Instagram and YouTube together with one click. Klaro sets then a cookie to allow all of this networks. When this button is not accepted I still have "Embed Privacy", so that the user has to accept every single embedded tweet und video. 

But: with social media embeddings, there is data-transfer out of the EU. So I am not happy to let people just "Accept all", but "Accept all 🇪🇺EU-Cookies" or "Accept all First-Party-Cookies", and then set the third-country-cookies one by one trough the modal. 

I know, it makes Klaro maybe even more difficult to understand and configure, but I hope a made a good case clear. :)

**Comment by adewes** [comment]
Hey @saschafoerster! You can set `acceptAll: false` in your config and then choose the apps you want to be enabled by default using the `default: true` parameter (you can set a global value and override that in each app). This should accomplish exactly what you want, I think.

**Comment by adewes** [comment]
Hey @saschafoerster, did you have a chance to try the proposed solution?

**Comment by saschafoerster** [comment]
Yep! Looks nice and I think this is as close to a good and conform solution as I can get. 
<img width="382" alt="Bildschirmfoto 2020-09-02 um 00 20 35" src="https://user-images.githubusercontent.com/1153741/91912071-a54f6880-ecb2-11ea-8842-5f078411bbec.png">
