### ISSUE TITLE
/dist files/subdirectories missing in npm package

### ISSUE THREAD

**Issue by dennisfrank** [kiprotect/klaro#293]
**The problem**

I miss many files and subdirectories from [`/dist`](https://github.com/kiprotect/klaro/tree/master/dist) (e.g. [`klaro-no-translations.js`](https://github.com/kiprotect/klaro/blob/master/dist/klaro-no-translations.js)) in the NPM package. It would be great if I could copy these files directly from `.node_modules/klaro/dist` without having to download them manually from the website or GitHub.

**Proposed solution**

Add the complete `/dist` directory to the NPM package.

**Comment by adewes** [comment]
Hey @dennisfrank, thanks for reporting this! It seems the `package.json` rules did not include all relevant files before, I've changed that and made a new release (available in 5-10 minutes), let me know if that shouldn't fix the issue!
