### ISSUE TITLE
HTML-Code im Text

### ISSUE THREAD

**Issue by Schockwelle** [kiprotect/klaro#295]
Guten Tag und vielen Dank für Eure Arbeit.
Ich möchte das Script etwas modifizieren und z.B. Text fett schreiben oder einen Link im Text selbst einfügen.

Leider wird der HTML-Code (z.B.: <a href="".... oder <b>abc</b> nur ausgegeben, aber nicht interpretiert.

Hat jemand einen Tipp für mich? 

Viele Grüße.

**Comment by adewes** [comment]
Hallo, einfach `htmlTexts` auf `true` setzen in der Konfiguration, die Texte im Consent-Modal und der Notice werden dann als HTML interpretiert. Die Beispielkonfiguration und Doku enthalten weitere Informationen hierzu.

**Comment by Schockwelle** [comment]
Herzlichen Dank!  Ich habe schon gesucht, aber – zugegeben – nicht die Comments in der config.js durchgelesen. 

Kann hier gern geschlossen werden.
