### ISSUE TITLE
Webpack example behavior?

### ISSUE THREAD

**Issue by Kiina** [kiprotect/klaro#296]
So I wanted to implement klaro into my site and looked at the webpack example provided. 

On first load it shows the banner:

![image](https://user-images.githubusercontent.com/2419591/93438752-050e5c00-f8ce-11ea-8a19-4cb062533315.png)

But if I agree or decline the terms on each subsequent load it pops up the Information:

![image](https://user-images.githubusercontent.com/2419591/93438721-fa53c700-f8cd-11ea-8583-30c26a5698ac.png)

This kinda doesn't strike me as the intended behavior. Shouldn't the manager not load when I don't press the "show manager" button?

I need to call `Klaro.show(config);` for it to even show up in the first place but `Klaro.show(config);` also opens the settings if you agree to it once. In the [documentation]( https://kiprotect.com/docs/klaro/js_api) there are different methods  like `renderKlaro `or `initialize` which seem to be removed?! What would be the correct way to call klaro to get the intended behavior of showing the little banner if you didn't agree and not popping up everytime the page loads if you agreed?

My js:
```
const Klaro = require("klaro");

const config = {
  elementID: "klaro",
  privacyPolicy: '/privacy',
  groupByPurpose: true,
  storageMethod: 'cookie',
  cookieName: 'klaro',
  cookieExpiresAfterDays: 365,
  default: false,
  mustConsent: false,
  acceptAll: true,
  hideDeclineAll: false,
  hideLearnMore: false,
  translations: {
    de: {
      googleAnalytics: {
        description: 'Sammeln von Besucherstatistiken',
      },
      recaptcha: {
        description: 'Aussortieren von Spammern',
      },
      purposes: {
        analytics: 'Besucher-Statistiken',
        security: 'Sicherheit',
        livechat: 'Live Chat',
        advertising: 'Anzeigen von Werbung',
        styling: 'Styling',
      },
    },
    en: {
      googleAnalytics: {
        description: 'User Statistics',
      },
      recaptcha: {
        description: 'Prevent Spam',
      },
      purposes: {
        analytics: 'Analytics',
        security: 'Security',
        livechat: 'Livechat',
        advertising: 'Advertising',
        styling: 'Styling',
      },
    }
  },
  apps: [{
      name: "googleAnalytics",
      title: 'Google Analytics',
      purposes: ["analytics"],
    },
    {
      name: "recaptcha",
      title: "Recaptcha",
      purposes: ["security"],
    }
  ]
};

Klaro.show(config);
```

**Comment by adewes** [comment]
Hi @Kiina, thanks for reporting this! I realized this was probably a bit confusing so we updated the example and made it easier to initialize Klaro from within a script. Basically, you just import Klaro and call `Klaro.setup(config)` with your config to initialize it. It should then behave exactly like the standalone Klaro script, showing the consent notice if the user hasn't consented yet and not showing it if he/she has consented.

We've just published a new release that will be available in 5-10 minutes, please have a look at the updated example there and let me know if that fixes your problem! I realize the documentation isn't fully in sync as we've had a lot of changes recently (lots of great stuff coming to the OS version of Klaro), we'll improve that soon as well.

**Comment by Kiina** [comment]
That was fast. Newest release does indeed work as I would expect using Klaro.setup(config). Thanks a lot!
