### ISSUE TITLE
Cookies form iFrame

### ISSUE THREAD

**Issue by gregBerthelot** [KIProtect/klaro#30]
Hi

Is there a way to manage cookies set from an iFrame the ones set by YouTube when you embed a video?

Thanks
Greg

**Comment by gregBerthelot** [comment]
make sense but I guess we should get the user consent before allowing youtube to write dozen of cookies… but as you have been thinking all use cases it is possible to prevent external resources with:

````
<iframe type="opt-in"
        data-src="https://www.youtube.com/my-embedded-video…"
        data-name="youtube">
```

Just get it :)

Thanks for you great job

**Comment by adewes** [comment]
Yes exactly, you can also disable iframes using those data attributes :) Didn't understand your use case, this makes total sense of course!

**Comment by minstyle** [comment]
> make sense but I guess we should get the user consent before allowing youtube to write dozen of cookies… but as you have been thinking all use cases it is possible to prevent external resources with:
> 
> ```
> <iframe type="opt-in"
>         data-src="https://www.youtube.com/my-embedded-video…"
>         data-name="youtube">
> ```
> 
> Just get it :)
> 
> Thanks for you great job

The "type" attribute is not allowed (W3C valid) and not necessary on iframe element.

The following code should also work:

```
<iframe 
         data-src="https://www.youtube.com/my-embedded-video…"
         data-name="youtube">
```

**Comment by adewes** [comment]
Hey @minstyle , we're finally working on a feature for these embeds and will make this much easier soon, I'll let you know once it's done!
