### ISSUE TITLE
IE11: No consent notice / Unhandled Exception

### ISSUE THREAD

**Issue by saitho** [kiprotect/klaro#302]
**Steps to reproduce**

1. Start IE11 and open the debug window
2. Open the Klaro homepage https://klaro.kiprotect.com/
3. Debug window will show the exception

> Unable to get property 'getAttribute' of undefined or null reference

![error](https://user-images.githubusercontent.com/7293310/94939565-9e469080-04d2-11eb-8bd5-1c2502168b87.png)

**Current behavior**

No consent banner is shown in IE11. Instead an error is shown in debug window.

Probably the fallback for IE11 fails: https://github.com/kiprotect/klaro/blob/master/src/utils/compat.js#L1

**Expected behavior**

I expect to see a consent banner in IE11.

**Comment by adewes** [comment]
Hi @saitho, thanks for reporting this! Seems it's a regression that was introduced when we changed some compatibility code, unfortunately it slipped through QA as we don't have an automated test suite for IE at the moment.

We patched it and I made a new release (0.6.18) which fixes the bug and should be online in 5-10 minutes.

**Comment by saitho** [comment]
Wow, thanks for the quick response and fix. I'll test that on Monday and get back to you here. :)

**Comment by saitho** [comment]
Worked, thanks!
