### ISSUE TITLE
"Activate all" slider active when not all applications are checked in "app-based" modal

### ISSUE THREAD

**Issue by saitho** [kiprotect/klaro#303]
**Klaro Config**

```javascript
var klaroConfig = {
  mustConsent: false,
  noticeAsModal: true,
  groupByPurpose: false,
  acceptAll: true,
  apps: [{"name":"app1","title":"App1","description":"Test","required":true},{"name":"app2","title":"App2","description":"Test2"},{"name":"test3","title":"App3","description":"Test3"}],
};

```

**Current behavior**

The bug occurs in the modal configuration where applications are not grouped by purpose whne multiple applications are configured. When enabling a single application, the "Activate all" slider ("Alle Dienste aktivieren oder deaktivieren") is enabled as well.

The bug can not be seen on the Klaro website as it used the `groupByPurpose: true` setting.

![activateall-bug](https://user-images.githubusercontent.com/7293310/95075054-d8e93c80-070f-11eb-93b6-429e1cd7dbbd.png)

**Expected behavior**

The "Activate all" slider should only be fully enabled when the user has consented to all applications.

**Comment by saitho** [comment]
I just saw another issue also talking about this (#117).

Not sure if this is a duplicate then. The issue went into the direction of introducing buttons instead of the toggle.
That's why I'll keep this issue open as a bug report, as the behaviour differs from the behaviour with `groupByPurpose: true` setting.

**Comment by adewes** [comment]
Hi @saitho! Actually this is a feature :wink:

Right now the "Toggle all" slider is only shown in the ON state if all services are enabled, otherwise it will be shown in the OFF state. We could change that so that the slider appears in the OFF state until all services are enabled.

As you said maybe a slider is not the right UI solution here. In the meantime we could also add an option to disable the slider.

I like your styling of Klaro btw, looks great!

**Comment by adewes** [comment]
Nevermind, I think I see the problem now, as the default toggling behavior does indeed differ between grouped and ungrouped consent. This should be easy to fix, we'll shortly make a new release.

**Comment by adewes** [comment]
Hey @saitho, we made a new release `0.7.1` that makes the behavior consistent in all modes, let us know what you think.

**Comment by saitho** [comment]
Whoa nice work! Can't test it right away as the breaking change in 0.7.0 (despite of said fallbacks) requires more coordination at our end.
It would be marvellous if you could also backport this bugfix to 0.6. Otherwise it might take a while for me to confirm it works.

Thanks!

**Comment by adewes** [comment]
We'l check if we can do that, we just started publishing stable release branches that receive backwards-compatible updates, right now we only have the `0.7` release as a branch though, I'll check if we can backport this though.

**Comment by saitho** [comment]
I've upgraded our integration to Klaro 0.7 and am able to confirm the fix. Thanks!
