### ISSUE TITLE
Changing language

### ISSUE THREAD

**Issue by luniiix** [kiprotect/klaro#307]
Hi,

I try to change the klaro plugin language with the klaro.language('fr').

But when i try to override the varibale, she stay on 'en'.

However, i wanted to see the translations available with klaro.getTranslations(). That return me an error that klaro.getTranslations() is not a function.

![image](https://user-images.githubusercontent.com/6369410/95446199-412e5d00-0960-11eb-88df-b23407c6662c.png)

Did i do something wrong ? :s

Thanks for the help.

**Comment by adewes** [comment]
Hi @luniiix! Sorry it seems our docs were misleading here, we recently changed the function name into `klaro.getConfigTranslations(config)` (we just updated the docs to fix this), so if Klaro has been successfully initialized you can simply call `klaro.getConfigTranslations(klaro.defaultConfig)` to get all available translations. `klaro.language()` is a read-only function, to change the language you need to update the `lang` variable in your config, e.g. like this:

```
klaro.defaultConfig.lang = 'fr'
klaro.show()
```

This should render the notice in French. Normally it suffices to either leave `lang` undefined in your config or set it to `zz`, then Klaro wil either use the window-defined language `window.language` or the document language `document.documentElement.lang`. So for a website in French it will automatically render Klaro in French.

**Comment by luniiix** [comment]
Hi @adewes ,

Thanks for this fastest answer ! :)
Actually, this is not in french when, i open it. it's in english.
I tryed to set the `document.documentElement.lang = "zz"` and have some undefined translation.
![image](https://user-images.githubusercontent.com/6369410/95456997-7e9ae680-0970-11eb-9d65-32c918236795.png)
I probably did something wrong again. :S

However, it's not a problem for me, i will set everytime the language.
Thanks for the help. 💯 

Best Regards,
@luniiix

**Comment by adewes** [comment]
Great, thanks we could resolve this! We'll soon integrate the IDE into the open-source version, which will make configuring Klaro much easier and give you an easy way to override translations:

![image](https://user-images.githubusercontent.com/550026/95498153-b0797080-09a3-11eb-92a6-3a6065ba069d.png)
