### ISSUE TITLE
Wrap the "cookie-notice" in another div

### ISSUE THREAD

**Issue by Gajel** [kiprotect/klaro#309]
First of all, thank you for this awesome open source project. Great work, I love it.

I would like to wrap the `<div class="cookie-notice"></div>` in another div like the `<div class="cm-modal cm-klaro"></div>`. 
So that I can center the small div, just like the other div.

So this:

```
<div id="klaro">
  <div lang="de" class="klaro">
    <div class="cookie-notice "></div>
  </div>
</div>
```

schould become this:

```
<div id="klaro">
  <div lang="de" class="klaro">
    <div class="cookie-modal">
      <div class="cm-bg"></div>
      <div class="cookie-notice "></div>
    </div>
  </div>
</div>
```
Just like it is here
```
<div id="klaro">
  <div lang="de" class="klaro">
    <div class="cookie-modal">
      <div class="cm-bg"></div>
      <div class="cm-modal cm-klaro"></div>
    </div>
  </div>
</div>
```

Is there a quick way to do this? I think its a bit more work to the js file right?

Grüße aus nähe Hamburg :D

**Comment by Gajel** [comment]
I did it quick and dirty like this.

`return p?se("div",{className:"cookie-modal"},se("div",{className:"cm-bg"}),S):S`

become

`return p?se("div",{className: "cookie-modal cm-embedded"},S):se("div",{className:"cookie-modal"},se("div",{className:"cm-bg",onClick:r}),S)`

**Comment by adewes** [comment]
Hey @Gajel, if you like to display the notice as a modal, you can do it via the `noticeAsModal` option, which will center the consent notice in the middle of the screen. You could also try the `embed` option, which will render Klaro inside another div that you can position relatively to center e.g. the notice in there.
