### ISSUE TITLE
HTML in Service Descriptions

### ISSUE THREAD

**Issue by intradesign** [kiprotect/klaro#310]
Hi there, I haven't worked with Klaro! for a few weeks now and I am very impressed with the new features in version 0.7 that I looked at yesterday.

I like the possibility to enter HTML as descriptions, but I miss this option in the descriptions of the services. Especially here it would be very handy if you could insert HTML. In the Modal Description I use e.g. for several explanation sections HTML details to expand which looks quite good.

```
<details>
<summary>A short summary of the following</summary>
Some more details
</details>

```

![CleanShot 2020-10-12 at 11 06 00@2x](https://user-images.githubusercontent.com/21263208/95727886-181d0d80-0c7b-11eb-8504-ff230da89b1e.png)

This is exactly what I would like to do in the descriptions to provide further information on the services, for example to list the cookies used and their functions and a link to the services' privacy policy.

I don't understand why there is no HTML for the service descriptions. Is there a reasonable argument against it?

At this point, thank you again for your efforts to develop Klaro!

Thanks and best regards
Timo

**Comment by adewes** [comment]
I'm closing this for now as it's implemented in Klaro, let me know if you have further questions or input, and thanks again for opening this issue!
