### ISSUE TITLE
[Services] : Events & Hooks

### ISSUE THREAD

**Issue by sulman8s** [kiprotect/klaro#316]
I have written a Javascript function that manipulates the Services Description on load. I want to now integrate this Javascript function on **Services Toggle button** (.cm-list-input), and on **Overly** (.cm-bg ) click.

Because on Services Toggle button or on Overly click, it updates the Services Description and append default Service Description after the manipulated description.

Any idea?

<img width="749" alt="services-desc" src="https://user-images.githubusercontent.com/2495429/96579543-5186f600-12d7-11eb-8b41-3a56d8310ee5.png">

**Comment by pdyckerhoff** [comment]
Hey, 

defining callback functions in the klaro cfg could be one way to trigger your text changes.

Or you can do this with extending your javascript function as well. There are unique id´s for the services slider (just hmtl inputs with type checkbox) that are disabled or not. So you can listen for the input state and change the text based on that. 

I would try the callback functions first ;)
