### ISSUE TITLE
Defining a fallback language

### ISSUE THREAD

**Issue by saitho** [kiprotect/klaro#317]
**The problem**

We're currently rolling out Klaro for multiple countries and languages.
We noticed that some translations are incomplete (da, el, fi, hr, hu, no, ro, ru, sr, sv, tr) or some languages are even not available (cs).

**Proposed solution**

I'd like to be able to define a fallback language in configuration that Klaro tries to use when a translation is missing.

```javascript
translationFallback: 'en',
```

That would try to load the label from the English language if it is missing in the current language and not defined in "zz" fallback language.

**Alternative solutions**

An alternative solution is having to redefine every translation in "zz" key which is already possible.

**Comment by adewes** [comment]
Hi @saitho! You can either define `fallbackLang` in your config, then translations will fall back to that language. If you leave it undefined, it will try to fall back to the `zz` language. I wouldn't define all translations in the `zz` key, the main purpose of it is to provide translation keys for things like a privacy policy.

We're using DeepL to translate Klaro into languages from English, currently that API doesn't support all languages, the translations for some unsupported languages were community-contributed but are not completely up-to-date, as you noticed. We will soon add support for the Google Translation API which will allow us to provide more languages. For some languages we might only be able to offer manual translations in the subscription-based version, as good translators are not cheap, we'll try to keep most European languages covered by the open-source version and we're of course always happy to have people help us, so if you're translating Klaro into languages that are not yet part of the open-source release please consider contributing your translations back.

**Comment by saitho** [comment]
Ah, I knew I saw `fallbackLang` somewhere! I guess it's just missing in the annotated configuration file. :)
Closing then as feature is already there. ^^
