### ISSUE TITLE
"data-no-auto-load=true" not having any effect. What am I doing wrong?

### ISSUE THREAD

**Issue by jhtjards** [kiprotect/klaro#320]
Hi, 
I'm having a little trouble with the data-no-auto-load script tag attribute.

I have set `noticeAsModal: true,` but on my data privacy page I need my visitors to be able to view the policy before accepting or declining, so the easiest solution would be to not auto-load klaro. I've found the above mentioned script tag attribute, but it doesn't have any effect at my site. So the Modal still shows up on page load when no klaro-cookie is set.

Am I missing something?

I'm using v0.7.4 (no css, no translations) 
The script tags (at the end of the body) look like this:
`<script type='text/javascript' src='https://example.com/js/klaro/config.js?ver=1604419369' id='klaro-config-js'></script><script type='text/javascript' src='https://example.com/js/klaro/klaro-no-translations-no-css-test.js?ver=1604418237' id='klaro-lean-js' data-no-auto-load="true"></script>`

My config is set as follows
`version: 1,
elementID: 'klaro',
htmlTexts: true,
embedded: false,
groupByPurpose: true,
storageMethod: 'cookie',
cookieName: 'klaro',
cookieExpiresAfterDays: 365,
default: false,
mustConsent: false,
acceptAll: true,
hideDeclineAll: true,
hideLearnMore: false,
noticeAsModal: true`

**Comment by adewes** [comment]
Hi @jhtjards, please use the `noAutoLoad: true` config option instead. I realized we still reference the `data-no-auto-load` parameter in the config, we'll fix this.

**Comment by jhtjards** [comment]
Hi @adewes, thanks a lot, that did work nicely!
