### ISSUE TITLE
Avira Browsersafety - Klaro is blocked

### ISSUE THREAD

**Issue by partyjunky** [kiprotect/klaro#321]
On a tryout I installed Klaro as discribed on a real simple html page (no scripts etc.) and it works fine at desktop, by going public not.

 So I lookes why. 
Avira browsersafety blocked it, when I switch it off everything is even onilne fine, when it is activated not.
 I looked at klaro website and searched the companys like Brockhaus AG and ohters, there it work even with activated Avira browsersafety, so what went wrong. 

Even with the github example index.html and the unchanged config.js it don't work.

**Comment by adewes** [comment]
Hi @partyjunky! Thanks for reporting this. Sometimes Klaro gets detected as a tracker, we have seen this behavior with PrivacyBadger as well but can't really explain it so far. Can you provide some additional debugging information?

The problem with these extensions is that they try to "learn" which scripts are trackers using a so-called heuristic engine. Especially if you're using Klaro on localhost for development/debugging and on several domains the extension might think that it's a tracker.

Can you try to test with a clean install of Avira Browsersafety and see if the problem persists?

**Comment by partyjunky** [comment]
So far not.

first law compatible workout is to set  mustConsent: false, on true, so ariva don't be able to block. not the golden conclusion till now, but it is conform to law. late today, so i try tomorrow testing with a clean avira browser safety.

Oh the others first i thought which pass thrugh, the don't, they  got  also mustConsent: true, so i guess something marks klaro always as a tracker

**Comment by partyjunky** [comment]
So did not solved it. 
My recipe is to set mustConsent: true;  this will get a reaction from the user and always been show up, even with the scriptblocker.
