### ISSUE TITLE
Page Load Error with Dialog loading in NextJS

### ISSUE THREAD

**Issue by maxwolfs** [kiprotect/klaro#323]
Hi! First of all thanks for the nice work! Unfortunately I'm having some troubles getting it started in NextJS.

**Klaro Config**

It's the one provided with the docs:
https://kiprotect.com/de/doku/klaro/kommentierte-konfiguration

**HTML Code of Page**

Tech Stack is NextJS.
Klaro is imported async as NPM package.

```
import config from "../klaro.config";

const DefaultLayout = props => {

  const loadKlaro = async () => {
    if (typeof window !== "undefined") {
      const Klaro = await import ("klaro/") 
      window.klaro = Klaro;
      window.klaroConfig = config;
      Klaro.setup(config);
    }
  }

}
```

**Steps to reproduce**

I Import Klaro and load it. When `mustConsent: true` the followin Error comes immediately.
 
**Current behavior**

On page load i get the following error:

<img width="720" alt="Bildschirmfoto 2020-11-12 um 11 34 10" src="https://user-images.githubusercontent.com/28341836/98929252-290ba980-24db-11eb-9f62-8bfabc25897a.png">
<img width="718" alt="Bildschirmfoto 2020-11-12 um 11 34 34" src="https://user-images.githubusercontent.com/28341836/98929257-2ad56d00-24db-11eb-8690-1c04409165c8.png">

I suspect the translations, but not sure how to debug.

**Expected behavior**

Load the modal for making cookie decisions.

**Comment by adewes** [comment]
Hi @maxwolfs! Thanks for reporting this. Could you try to use either the example config from the Webpack example in the `examples` directory, or the config given in the `dist` directory and check if the problem persists? As you said there might be something amiss with the config format, from the traceback of the minified code it's hard to tell unfortunately.

**Comment by maxwolfs** [comment]
Hi @adewes! Yeah changing the config was indeed the solution. I took the one from the `dist` folder and everything was running – Thanks!
