### ISSUE TITLE
Uncaught TypeError: this.config.apps is undefined

### ISSUE THREAD

**Issue by SimonMayerhofer** [kiprotect/klaro#333]
**Klaro Config**

default config example

**Current behavior**

The default config example https://github.com/kiprotect/klaro/blob/master/dist/config.js is not correct. I get a error:
`Uncaught TypeError: this.config.apps is undefined`

`klaroConfig.services` needs to be renamed in `klaroConfig.apps`

**Comment by adewes** [comment]
Hi @SimonMayerhofer! Which Klaro version are you using? We migrated `apps` to `services` a while ago and there should be no reference to `config.apps` from recent Klaro versions. Can you check that you're on the latest (0.7.x) version of Klaro?

**Comment by SimonMayerhofer** [comment]
Thanks for your reply. Seems like I had version v0.6.18 running. Don't know how that happend.

**Comment by tpinne** [comment]
I currently ran into the same issue with `https://cdn.kiprotect.com/klaro/latest/klaro.js`. 

When I reference `https://cdn.kiprotect.com/klaro/v0.7.16/klaro.js` or `https://cdn.kiprotect.com/klaro/v0.7/klaro.js` directly it works as expected.

It seems there is still an old cached `latest` version out there which resolves to an older version.

**Comment by adewes** [comment]
Hi @tpinne, as we state in the README we no longer update the `latest` tag in our CDN as it risks breaking existing Klaro installations. We recommend using the `v0.x` tags, which will receive minor updates, or an exact version like `v0.7.16`, which has the advantage of being able to specify an `integrity` tag (which you'll find in `releases.yml`). The best option is of course to self-host Klaro, as you then won't need to trust a third party to host code for you.

**Comment by adewes** [comment]
Good point! Getting people to update their Klaro version is a big concern for us, we might stop offering the CDN solution altogether and just ask people to create a (free) account in order to get the hosted Klaro version, that will allow us to get in touch with them as well. So please consider signing up for an account as well if you don't want to self-host Klaro.
