### ISSUE TITLE
iframe src="undefined"

### ISSUE THREAD

**Issue by Flaschenzug** [kiprotect/klaro#335]
When using contextualConsentOnly for YouTube Videos, I get the following error in Safari & Firefox:

src="undefined"
it results in an invalid URL to the webpage:
domain.com/undefined

And it throws an error in the Terminal.

Is that a configuration problem or a common problem?

Update: I just realised that Google Page Speed is Complaining about the "wrong" URL.

**Comment by adewes** [comment]
Hi @Flaschenzug, thanks for reporting this and yes we already have a fix for that in master, will deploy it later today with the latest version!

**Comment by Flaschenzug** [comment]
Amazing @adewes

**Comment by adewes** [comment]
Hey @Flaschenzug, this problem should be fixed now with the `0.7.10` release we just pushed, let me know if that's not the case.
