### ISSUE TITLE
The use of cm.js is poorly documented

### ISSUE THREAD

**Issue by Heziode** [kiprotect/klaro#336]
From the [README.md](https://github.com/kiprotect/klaro/README.md) we can see the following code:

```
// import only the consent manager (no UI components)
import 'klaro/dist/cm'
```

And... that's it, no more info on ow to use the CM, it is not documented/mentioned at all on the [doc](https://kiprotect.com/docs/klaro/)

I want to design my own component UI, and only use the core of Klaro to manage the consentment, that what I think CM should provide. But I have no Idea on how to manage it with a component.

**Comment by Heziode** [comment]
My bad, it's documented [here](https://kiprotect.com/docs/klaro/js_api#ConsentManager).

**Comment by adewes** [comment]
We're working on a new, better version of the docs btw!

**Comment by davemecha** [comment]
I tried using  `import 'klaro/dist/cm';` as well and I also checked the [API docs](https://klaro.org/docs/api/js_api). it says after importing `cm`, it should have been added to the global scope but I can't find it in `window`.

The docs still give no clue at all. 🤷
