### ISSUE TITLE
Custom data-config not working

### ISSUE THREAD

**Issue by BitchCO** [kiprotect/klaro#343]
**Klaro Config**
ORIGINAL: `var klaroConfig = {...`
CUSTOM: `var someOtherVarName = {...`

**HTML Code of Page**
`<script defer type="application/javascript" src="klaro.js" data-config="someOtherVarName " data-style-prefix="klaro">`

**Steps to reproduce**
Change the var name from to anything else.

**Current behavior**
Not working with custom var name.
Only works with default global var _klaroConfig_

**Expected behavior**
Should be working with custom var name, as explained in first lines of config.js. See https://kiprotect.com/docs/klaro/annotated-configuration

Using latest version of klaro.js

**Comment by vstuber** [comment]
I just found out that the attribute which defines the variable name of the config to use is not named "data-config" but instead "data-klaro-config". With the exact same problem that you describe, this is the solution that worked:

`<script 
    defer
    data-klaro-config="klaroCustomConfig"
    type="application/javascript"
    src="/files/klaro/klaro.js">
</script>`

**Comment by afanjul** [comment]
Many thanks, I had the same problem and now I do know why ... ;-) 
BTW: I feel that is more standard name the "data-config" attribute

**Comment by adewes** [comment]
Thanks for pointing out the fix @vstuber, we just fixed the annotated config in our docs!
