### ISSUE TITLE
Klaro does not clear cookie domains prepended with a dot

### ISSUE THREAD

**Issue by Jako** [kiprotect/klaro#346]
**Steps to reproduce**
I am using the following code for gtag.js:

```
<script type="text/plain" data-type="application/javascript" async data-src="https://www.googletagmanager.com/gtag/js?id=UA-xxx" data-name="googleAnalytics"></script>
<script type="text/plain" data-type="application/javascript" data-name="googleAnalytics">
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-xxx', {
      'cookie_domain': 'my.domain.de'
  });
</script>
```

**Current behavior**

gtag.js creates a cookie with the domain `.my.domain.de` and the cookies of that domain are not cleared, when the service is disabled. Klaro itself creates a cookie with the domain `my.domain.de`

**Expected behavior**

Klaro should clear the cookie with the domain `.my.domain.de`, when the service is disabled.

**Comment by Jako** [comment]
The option `'cookie_domain': 'none'` does help here.

**Comment by adewes** [comment]
Hi @Jako! Can you post your Klaro config as well? In general, if a cookie is set for a different domain or path you will need to specify that in the `cookies` section, so instead of just giving the name of the cookie you'd give a list of the form `['cookie name', 'cookie path', 'cookie domain']`, see .e.g [here](https://kiprotect.com/docs/klaro/annotated-configuration) for a more detailed example. If you're using the hosted version of Klaro simply click on the `Google Tag Manager` service and add the domain name to the specific cookie.

Let me know if you still have trouble removing the cookie!

**Comment by Jako** [comment]
I could narrow it a bit: 

```
    {
            "name": "googleAnalytics",
            "title": "Google Analytics",
            "description": "Sammelt statistische Daten dar\u00fcber, wie der Besucher die Website nutzt.",
            "purposes": [
                "performance"
            ],
            "cookies": [
                "_ga",
                "_gid",
                "_gat",
                "AMP_TOKEN",
                /^_gac.*$/,
                /^_gat.*$/
            ],
            "onlyOnce": true
        }
```

In this service configuration, the cookies found with a regular expression are removed and ones with a string not. But maybe I use the config somehow wrong.

**Comment by adewes** [comment]
For cookies that are not set on the current domain for the root path (`/`) you need to specify the domain and path explicitly, see my answer above.

**Comment by Jako** [comment]
I have an issue with your answer: Why does Klaro remove the cookies found with a regular expression and the other ones not?

The `/^_gat.*$/` cookie is removed and the `"_ga"` cookie not.

**Comment by adewes** [comment]
Is the `ga` cookie set on another domain maybe? Could you post the names, paths and domains of the `_ga` cookie as shown by the development tools?

**Comment by Jako** [comment]
Now all GTAG/GA cookies are not deleted. So it must have been a different issue, but I currently can't reproduce this.

I will use the GA `'cookie_domain': 'none'` option.
