### ISSUE TITLE
Google Tag Manager not working

### ISSUE THREAD

**Issue by rogoit** [kiprotect/klaro#347]
Hello friends,

first massive thx for your open source passion and this project here.

I want to add the Google Tag Manager and there are not cookies set. This is a big problem for me, because I need this feature very urgent for three clients. I pushed my Sulu CMS project here to GitHub. Its also open source. And when i have a result i will blog about it and do a little video tutorial to help more people.

So here is the project
https://github.com/nevercodealone/cms-symfony-sulu

Klaro files
https://github.com/nevercodealone/cms-symfony-sulu/tree/master/public/klaro

Base template with the no script part
https://github.com/nevercodealone/cms-symfony-sulu/blob/master/templates/base.html.twig 

Header file
https://github.com/nevercodealone/cms-symfony-sulu/blob/master/templates/partial/analytics.html.twig

Result page
https://nevercodealone.de/de

In the result when i accept all cookies I do not see anything of Google. In the footer there is also a option to open the seetings.

Thx for support friends!!

**Comment by adewes** [comment]
Hi @rogoit! Did you check out our Google Tag Manager (GTM) tutorial [here](https://kiprotect.com/docs/klaro/tutorials/google_tag_manager)? It contains a live example of how to manage GTM with Klaro, it should show you how to integrate it. If you haven't looked at this yet please start there and let me know if you problem still persists after configuring your Klaro instance in accordance with the tutorial.

**Comment by rogoit** [comment]
Yes, i do this from offical tutorial 😎

**Comment by adewes** [comment]
Ok. I'm unfortunately not able to provide integration consulting for the open-source version. If you think there's a bug in the way we handle GTM I'll need an example to reproduce it. Checking your website I can see that Klaro gets correctly loaded and that the GTM script tag gets activated when I consent, so the  basic configuration seems to be correct.

**Comment by rogoit** [comment]
Ok, that sounds good so far. Can I contact you for a paid consulting?

**Comment by adewes** [comment]
Hey @rogoit, integration consulting is included in our ["Company" and "Agency" plans](https://kiprotect.com/klaro/prices) if you sign up for a yearly subscription. We then provide fast e-mail based support and debugging and also help with customization and implementation of small feature requests. In addition you of course get all the awesome backend functionality of Klaro including e.g. website scanning, consent records, hosted configs, graphical configuration, service provider database, consent statistics, and you can deploy it on your clients' websites as well. We also have more features in the works like privacy policy generation, A/B testing, privacy proxies, security and privacy monitoring, weekly reports and much more. If you have any questions about that you can also contact me via e-mail, contact details are on the website!

**Comment by rogoit** [comment]
Ok, I register now ;)

**Comment by rogoit** [comment]
Hope for support now ;)
