### ISSUE TITLE
learnMoreLink: var "extraText" is not configurable

### ISSUE THREAD

**Issue by saschanos** [kiprotect/klaro#349]
**Klaro Config**

Directly in klaro.js, there's a variable called extraText. It's always field with three dots ("..."). This should be configurable.

**Code snippet**

<img width="482" alt="Bildschirmfoto 2021-01-09 um 14 04 03" src="https://user-images.githubusercontent.com/4348851/104092367-c7ba4980-5283-11eb-88fd-28a863786cab.png">

**Comment by SirRelhek** [comment]
I also want this feature. At the moment i use this workaround to remove the dots:
`const learnMore = document.querySelector('a.cm-link.cn-learn-more')`
      `learnMore.innerHTML = learnMore.innerHTML.substring(
        0,
        learnMore.innerHTML.length - 3
      )`

**Comment by Hirbod** [comment]
+1. Annoying 3 dots
