### ISSUE TITLE
How to generate klaro-no-css.js file?

### ISSUE THREAD

**Issue by jmartsch** [kiprotect/klaro#355]
I cloned the repo and changed something in src/components/consent-notice.jsx. Now if I run either `make-dev` or `make` my changes are reflected in klaro.js, but the klaro-no-css.js file is not generated.

I added the following code to my package.json, but it does not work

`    "make-dev-no-css": "cross-env APP_ENV=dev SEPARATE_CSS=true APP_DEV_MODE=server webpack-dev-server --host 127.0.0.1 --config webpack.config.js --history-api-fallback"`

I want to work with the klaro-no-css.js file and HMR to reflect my changes fast.

When I run `npm run make-dev-no-css` I get the following error:
```
 ERROR in ./lib.js
    Module not found: Error: Can't resolve '[object Object]' in 'D:\htdocs\klaro\src'
     @ ./lib.js 55:0-27
     @ ./klaro.js
```

The file is generated if I dont use webpack-dev-server like so:
`"make": "cross-env APP_ENV=production SEPARATE_CSS=true webpack --config webpack.config.js",`

There should be a npm task to generate both files `klaro.js` and `klaro-no-css.js` in a dev environment with HMR. If that isn't possible, then there should be a separate task to generate the no-css file.

**Comment by jmartsch** [comment]
I added the following code to my package.json, but it does not work

`    "make-dev-no-css": "cross-env APP_ENV=dev SEPARATE_CSS=true APP_DEV_MODE=server webpack-dev-server --host 127.0.0.1 --config webpack.config.js --history-api-fallback"`

I want to work with the klaro-no-css.js file and HMR to reflect my changes fast.

When I run `npm run make-dev-no-css` I get the following error:
```
 ERROR in ./lib.js
    Module not found: Error: Can't resolve '[object Object]' in 'D:\htdocs\klaro\src'
     @ ./lib.js 55:0-27
     @ ./klaro.js
```

**Comment by caioricciuti** [comment]
Hey @jmartsch in order to create klaro-no-css file you should run `SEPARATE_CSS=1 npm run-script make`. It worked for me, tell me if it works for you too! 
Kind regards.

**Comment by adewes** [comment]
Thanks @caioricciuti for answering this, I'll close this for now, if there's anything amiss please let me know.

**Comment by jmartsch** [comment]
Please reopen this issue, as my question is not answered. @caioricciuti just restated, what I had already mentioned in my question.

I am looking for a solution to generate both files klaro.js and klaro-no-css.js while using webpack-dev-server with file watching and HMR (Hot module replacement). The klaro-no-css.js file is just generated, if the APP_ENV is production, which is not the case when using webpack-dev-server.

If I add `SEPARATE_CSS=true` or `SEPARATE_CSS=1` the error that I mentioned in my question occurs.
