### ISSUE TITLE
I there a way to build Klaro no minify?

### ISSUE THREAD

**Issue by caioricciuti** [kiprotect/klaro#362]
Hello,
First of all, this consent manager is without doubt INCREDIBLE! Thank you so much for all your hard work! 

I would like to know if there is a way to build Klaro without minifying it. I would like that because many times I went through the code and couldn't understand it. I made some modifications in klaro.js to one project I'm working on but is always hard to go through the code (I can format the file of course), but after minified the variables have no significant name, and the code practically impossible to understand. 

Many thanks in advance, 
Kind regards!

**Comment by adewes** [comment]
Hey @caioricciuti, you should not edit the minified Klaro code as it's only for "consumption" by the browser. Klaro is compiled using Webpack and relies on JSX and ES6, so you should never edit the minified output. If you want to customize Klaro you need to clone the repository and follow the instruction in the README. In a nutshell, running

    npm install
    npm run-script make-dev

should give you a local version of Klaro running on port 8080. Modifying the code in the `src` directory will automatically update that version, and as the development build includes source maps it will be easy to debug. Once you have finished your modifications, run `npm run-script make`, which will update the build files in the `dist` directory, which you can then deploy.
