### ISSUE TITLE
TCF v2

### ISSUE THREAD

**Issue by ErikSom** [kiprotect/klaro#367]
Hi,

Is this lib compatible with TCF v2?

Kind regards,

Erik

**Comment by adewes** [comment]
Hi @ErikSom, to put it short we're currently deliberately not supporting the TCF 2.0 as we deem it incompatible with the GDPR. Also, to use TCF 2.0 with the open-source version of Klaro from your website you'd need to register as a CMP provider, which comes at a cost of 1.200 € / year. Alternatively, we could register as a CMP provider there but then you'd need to have a contract with us (i.e. use the hosted version of Klaro) as we could not lend you our CMP ID if you run the open-source version yourself (as we take on the compliance liability as a CMP if you send consent data using our ID). So sadly we're not able to offer support for TCF 2.0 at the moment. We're about to publish a longer article on this subject on our website that goes through the finer points of why we think the framework isn't compliant with the GDPR in the first place and should not be used on any website that really cares about visitor privacy.

That said you often don't need TCF 2.0 to display ads on your website, most publishers like Google support alternative consent workflows that Klaro can implement and that are more user-friendly and thereby have a higher chance of actually being compliant with the GDPR.

**Comment by adewes** [comment]
Sure no problem! BTW I opened an issue in the IAB TCF 2.0 repository asking for clarification (https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/issues/263), if you like why not give that a "Thumbs Up" or add a comment to let them know you're interested in this as well.
