### ISSUE TITLE
External chat script is not loaded/removed after update the consent

### ISSUE THREAD

**Issue by asofiane82** [kiprotect/klaro#370]
Hi every one, 

I would like to implement an external chat widget on Klaro consent here is a sample code
`<script src="https://tools.mysite.com/prod/widgets/chat/js/v2/chat-v2.js"></script>

    <script type="opt-in"data-type="application/javascript"  data-name="webcomChat" >
     window.webc.chat.init({token: "b038323f20aaaa757f422965ab757c3",mainColor: "#333"})
    </script>`

and here is my service 

`{
            name: 'webcomChat',
            purposes: ['chat'],
            cookies: [
                ["__webc_chat_id","/", "{{global.site.url}}"],
            ],            

            callback : function(consent, app){
              // this is an example callback function... 
                console.log(consent)
                if(consent === false){  createCookie("wc_chat_consent_optout","no","365");               
                    
                }else{                         
                    createCookie("wc_chat_consent_optout","yes","365");
                    
                }
            }
        }`

my problem is that when I accept/decline , the "chat box" is not loaded/removed, until I reload my page (got no error).

I am sorry, I'm a newbie and I have some difficulties to understand everything.

Thanks a lot for help

**Comment by adewes** [comment]
Hey @asofiane82, it seems your chat app consists of two scripts, one that loads the chat library and another one that loads up the chat window. When the user clicks on "Accept", Klaro will enable both script tags simultaneously, which might lead to the second script executing before the first one. The easiest way to fix this behavior is by changing your code like this:

```
<script type="opt-in" data-src="https://tools.mysite.com/prod/widgets/chat/js/v2/chat-v2.js" data-name="webcomChat" onload="loadChat()"></script>
<script type="opt-in"data-type="application/javascript"  data-name="webcomChat" >
function loadChat(){
    window.webc.chat.init({token: "b038323f20aaaa757f422965ab757c3",mainColor: "#333"})
}
</script>`
```
This should ensure that your chat widget will be displayed after the user clicks on "Accept".

**Comment by asofiane82** [comment]
Hi @adewes , thanks for the answer.

I tried your suggestion but doesn't seems to work

here is my complete code implementation
` <div id="chat-wrap"></div>
<script defer type="application/javascript"
src="/res/js/rgpd_klaro.js"></script>
<script defer   
    type="application/javascript" 
    type="text/javascript"
    data-klaro-config="rgpdconfig"
    src="/res/js/klaro.js" charset="UTF-8"></script>
    <script type="opt-in" data-src="https://tools.mysite.com/prod/widgets/chat/js/v2/chat-v2.js" data-name="webcomChat" onload="loadChat()"></script>
    <script type="opt-in" data-type="application/javascript"  data-name="webcomChat" >function loadChat(){
     window.webc.chat.init({token: "b038323f20dadcf757f422965ab757c3",mainColor: "#333"})}
    </script>
`

**Comment by adewes** [comment]
What is the console output? Any errors? What is the state of the DOM after accepting the service in Klaro, does the script tag get correctly rewritten? Please provide this information, I cannot debug this further otherwise. You can check the console output via the developer tab, to inspect the current state of the DOM you can use the "inspect element" functionality.

**Comment by asofiane82** [comment]
No problem at all on the console output.

But something strange when I inspect the first script of the chat I got type="undefined" and not opt-in

is it normal ?

**Comment by adewes** [comment]
Ah, you might have forgotten to add `data-type="application/javascript"` to the first script, I see that now. Please add this and see if that changes the outcome.

**Comment by asofiane82** [comment]
unfortunately no changes.

You can check (If it helps) [here](https://template-victoria.agencewebcom.com)

You can reload page after accept consent to see the chat box (bottom right)

**Comment by adewes** [comment]
I don't see an `onload` handler on the first script, or anything that would call `loadChat()`. The script seems to load correctly when the user accepts.

**Comment by asofiane82** [comment]
sorry, I deleted the `onload` handler not on purpose (didn't see it)

Now it's on , 
when you accept, y'll see an error `1 Uncaught ReferenceError: loadchat is not defined`

maybe something missing on the loadchat script ?

**Comment by adewes** [comment]
Check the spelling, the function is called `loadChat`. I'd also load the second script unconditionally and synchronously to make sure the function is available when the `onload` event occurs, so you should write it like this:

```
<script defer type="opt-in" data-src="https://tools.agencewebcom.com/prod/widgets/chat/js/v2/chat-v2.js" data-type="application/javascript" data-name="webcomChat" onload="loadChat()"></script>
<script>function loadChat(){
     window.webc.chat.init({token: "b038323f20dadcf757f422965ab757c3",mainColor: "#333",language:'fr'})}
</script>
```

**Comment by asofiane82** [comment]
Sorry I was not focusing enough (probably fatigue)

Ok so I did the same as you, same result, no problems but the chat box is still lunched after refreshing the page

**Comment by adewes** [comment]
I don't know your chat solution, I can verify though that the external script is loaded and that the `loadChat()` function is correctly triggered, so this is not a Klaro issue.

I looked at your chat script and it seems that it uses the `onload` trigger function of the window, hence it does not get executed if the script gets loaded asynchronously by Klaro. You need to change the way your script loads, e.g. like this:

```
    // if the document is loaded already, execute init directly
    if (/complete|interactive|loaded/.test(document.readyState)){
        handler()
    } else {
         // otherwise add an event listener
        window.addEventListener('DOMContentLoaded', handler)
    }
```

I won't provide any further debugging for your own Javascript as this is really not a Klaro issue, changing your chat init code should resolve this problem though.

**Comment by adewes** [comment]
We'll improve the documentation on this btw. And if you have other Klaro-related issues please don't hesitate to open an issue again!

**Comment by asofiane82** [comment]
Ok thank you very much for the time you gave me :)
