### ISSUE TITLE
Configuration when installing using a package manager?

### ISSUE THREAD

**Issue by spekulatius** [kiprotect/klaro#372]
Hello,

I was wondering how I set the configuration variable, if I install klaro using yarn or npm? Did I miss this? I couldn't find anything on this.

Cheers,
Peter

**Comment by adewes** [comment]
Hi @spekulatius! If you load Klaro as a module it will not automatically initialize itself, instead you have to explicitly call `klaro.setup(config)` to load a config. Sorry if that wasn't clear, we'll update the documentation in that regard.

**Comment by spekulatius** [comment]
Ah okay, no problem! Thank you for amazingly fast response! I'll try it out.

Btw, there is a missing comma in the config on https://kiprotect.com/docs/klaro/annotated-configuration:

![image](https://user-images.githubusercontent.com/8433587/110609034-40ffeb00-81a6-11eb-9aa0-bed45d79b1b3.png)

Noticed it when copying it over. I would have fixed it and send a PR but I couldn't find a repo for it...

**Comment by spekulatius** [comment]
Cool, works like a charm @adewes
