### ISSUE TITLE
Do I need a subscription to an klaro-plan to use it?

### ISSUE THREAD

**Issue by xstable** [kiprotect/klaro#375]
I'm a bit confused if there is a need for an subscription on https://heyklaro.com/pricing or not.
As I read it here on GitHub, and in the linked documentation, it seems to be an fully free opensource project. 

But I don't see, if that means only that the implementation code is free and opensource, but if it's anyway need an connection to the klaro-service (heyklaro).

**Comment by xstable** [comment]
I see now, found the section down below the pricing. Didn't scrolled down far enough.

**Comment by adewes** [comment]
Hey @xstable, the client code is fully open-source (BSD-3) and free to use, only our hosted version (which includes e.g. scanning, statistics and consent records) is paid.
