### ISSUE TITLE
Service elements are hidden by default

### ISSUE THREAD

**Issue by Jako** [kiprotect/klaro#386]
Since this patch https://github.com/kiprotect/klaro/commit/66e86dc8d9d3a4db789e40654f94116a33d73f77#diff-22654d13805f9f6c182a7303ed7922778ec18f809ed3924b4700cf92d5bf6f59L341-R365 all `data-name['servicename']` elements are hidden and there seems no setting or data attribute to avoid that. I only have the option to create a css !important rule or a callback at the moment to display them again. Or do I miss something?

**Comment by adewes** [comment]
Hi @Jako, that's actually intended behavior I think. How does it cause problems to you? Klaro hides all elements belonging to a service until the user accepts enabling that service.

You can add a `data-type=placeholder` attribute if you want to display a placeholder for a given element.

**Comment by Jako** [comment]
I am using Klaro on a site with Google reCAPTCHA and added `data-name="googleRecaptcha"` to the submit button. This button was suddenly hidden using the latest version.

Now the client wanted to have a warning message with a click on the button and I did not thought about the placeholder. And I solved that with the following jquery/bootstrap callback code:

```
function(consent, service) {
    var button = $('button[data-name="' + service.name + '"]');
    button.css('display', 'inline-block');
    if (!consent) {
        button.on('click', function(event) {
            $('#recaptchaModal').modal('show');
            event.preventDefault();
        });
    } else {
        button.off('click');
    }
}
```

In the bootstrap modal I open the Klaro consent modal with a click handler `klaro.show(window.klaroConfigs,{modal:true});`

**Comment by adewes** [comment]
Ok great. If the button only triggers an action it should probably not be managed by Klaro? In that case you can just remove the `data-name` attribute as well.

**Comment by Jako** [comment]
The function of the button has to depend on the state of the klaro googleRecaptcha service, thats the issue. It should not work, when the googleRecaptcha service is not accepted and show a bootstrap modal then.

**Comment by adewes** [comment]
Ah I see. You could use a Klaro JS hook to change the button state depending on the consent state.

**Comment by Jako** [comment]
The code above is a Klaro JS hook adding/removing jQuery click events to the button for the bootstrap modal.
