### ISSUE TITLE
Upload klaro.js to yarn or npm or better to a cdn?

### ISSUE THREAD

**Issue by Goldjan** [kiprotect/klaro#41]
Would it be possible?

**Comment by adewes** [comment]
Definitely, we discussed this before but currently it's not clear what the advantage would be or how you would use it. Do you want to embed Klaro into another app?

**Comment by mathroc** [comment]
@adewes, yes I'd like to build a nuxt.js module to easily integrate it with any nuxt.js app

**Comment by mathroc** [comment]
note that when package for npm, it should probably not start automatically because if the code is bundled for SSR for exemple, it would crash because there's no instance of `window` or `document`, instead I'd like ti be able to do something like that:

```js
const klaro = require("klaro");

klaro.start(config); // config is passed as an argument here, not from a global variable
```

**Comment by jaller94** [comment]
@mathroc Are there any other requirements for SSR? Is this easy to achieve?

**Comment by mathroc** [comment]
@jaller94 depends on what you mean, the suggestions I wrote earlier would make it possible to use Klaro in SSR components (react, vuejs, etc.) but, klaro would still run only on the client and would not be rendered on the server. making it able to be rendered on the server would probably require a port for each framework

**Comment by mathroc** [comment]
but I'm not an SSR expert so maybe there's a way I don't know about

**Comment by jaller94** [comment]
Yeah, I expected this to still require JavaScript on the FE, as the current implementation relies on JavaScript and a full SSR implementation is out of scope for this repo.
But this compatibility by not launching immediately is something that looks like a great and easy feature.

**Comment by jaller94** [comment]
As an early experiment, I published Klaro! 0.2.10 on NPM:
https://www.npmjs.com/package/klaro

A delayed start on calling `.start()` is not yet implemented but may become a thing in 0.3.0.
I have not forgotten your request and hope to deploy Klaro! releases automatically to NPM and other CDNs (or suggest NPM-based CDNs).

**Comment by birdspider** [comment]
@jaller94 any particular reason why only dist/klaro.js is on npm ?

**Comment by jaller94** [comment]
Because I'm familiar with publishing on NPM, it's easy and I think most people will expect to find it there.
NPM was not chosen to be the only platform to host Klaro on. You can also download it here on GitHub.
@birdspider Where would you prefer it to be hosted?

**Comment by birdspider** [comment]
sorry, I ment: why does the npm package only include the dist folder ?

**Comment by jaller94** [comment]
The dist folder is a collection of files building [Klaro's homepage](https://klaro.kiprotect.com/).
Currently, only `dist/klaro.js` is needed to import klaro into your own project.
The import behavior is declared here:
https://github.com/KIProtect/klaro/blob/39e40fc06e74a5eb13324de5ab582f609c48cde9/package.json#L15

**Comment by birdspider** [comment]
@jaller94 yes, but what if I want to import the react sources and es-modules ?

 I wanted to ask (since it's the second project this month) where using it as a 'dependency' via npm/webpack only gives the bundle. 

What is the recommended way[1] to, i.e. create a additional/different `AppItem` or create an extended `Apps` class, if there is no src in the package. Maybe I don't understand npm these days.

Also how do I reduce bundleSize, by i.e. dropping translations I do not need ?

[1] git clone maybe?

**Comment by jaller94** [comment]
That may be a bit of an off-topic in this issue, but it's commonly done by allowing tree-shaking and having side-effect free code. [`date-fns`](https://github.com/date-fns/date-fns) is doing this perfectly as on can tell by [its bundlephobia page](https://bundlephobia.com/result?p=date-fns@2.4.1).

The various languages won't blow up the package to any significant amount, but it's true that klaro ships with Preact and you can't get rid of it without git cloning it and building it as part of your code.

For this components like ReactDateRangePicker specify [`peerDependencies`](https://github.com/onefinestay/react-daterange-picker/blob/c73c92a7b21954374e19e81f17bc87c6142a292b/package.json#L55-L60) which you will also have to install in the project you use it. They are excluded from the build as specified by [webpack's `external` config param](https://webpack.js.org/configuration/externals/).
There should be a separate build of klaro offering a smaller build for those already using React or Preact using such a config. 👍

Got some spare time for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) or [Open Source Friday](https://opensourcefriday.com/)? I can write you a list of what to do and will review a PR.

**Comment by mathroc** [comment]
@jaller94, @birdspider is right, it's sometimes useful to bundle the source files too. it can be to import only part of the module (or parts that are only exported in other files than the entrypoint). it can also allow to transpile the js with different webpack/babel configuration.

in fact I was looking at the source code and looking how I could submit a PR to enable the delayed start and my idea was to split the src/klaro.js file into 2 files: src/klaro-modules.js and src/klaro.js and the src/klaro.js would mostly be:

```js
import * as klaro from './klaro-modules'

// some code accessing `window`

window.onload = initialize

if (module.hot) {
    if (!noAutoLoad)
        renderKlaro(config)
    module.hot.accept()
}

export klaro

export function initialize(e){
    if (!noAutoLoad)
        klaro.renderKlaro(config)
    if (originalOnLoad !== null){
        originalOnLoad(e)
    }
}
```

and everything else would go in src/klaro-modules.js

**Comment by amtee** [comment]
Hey everyone, 

first of all, let me tell you: thanks for very good work on  `klaro`!

The [package on npmjs](https://www.npmjs.com/package/klaro) should be either up-to-date or deleted. It does not make sense to offer outdated version only.

Thanks in advance!

**Comment by adewes** [comment]
Hey @amtee, the npm packages are now always up-to-date with the latest Klaro version!
