### ISSUE TITLE
Donations possible?

### ISSUE THREAD

**Issue by trevor87** [kiprotect/klaro#416]
Hi,

thanks a lot for this great tool, it is very helpful! Is there a possibility to support the tool with donations?

**Comment by adewes** [comment]
Hey @trevor87, if you want to support us you could sign up for a subscription. We might soon add another "Supporter" tier that is a bit cheaper than the Startup one for that.

**Comment by trevor87** [comment]
Thanks for the reply! The subscription unfortunately exceeds our current budget as a startup, so I guess I will wait for the supporter tier.
