### ISSUE TITLE
How to run my script only when consent is given? 

### ISSUE THREAD

**Issue by caioricciuti** [kiprotect/klaro#422]
Hello, I need some help.

I have a script in my index.html
```html
<script>alert('consent-given!')</script>
```
And I need this script to run only if consent is given... 
I have tried to use `data-name` and add it to the config file but it didn't work... 
Also I have tried to use contextual consent but since I don't have `src` I can't give a `data-src` (I can but does not work)...

There is any way to achieve what I need with klaro? 

Thank you all in advance!

**Comment by jaller94** [comment]
I don't think you can stop the inline JavaScript from getting executed, however, you can prevent it from setting cookies before consent is given.

https://github.com/kiprotect/klaro/blob/7db425d6686d7f8d7dd2a5d26899e35a5e515f19/dist/config.js#L287-L292

**Comment by sahib-afk** [comment]
Hola Caio,

actually, the answer to your question can be found in the [manual](https://heyklaro.com/docs/getting-started):

> For inline scripts, **replace the value of the type attribute with text/plain** (this keeps the browser from executing the script) and **add a data attribute with the original type**, e.g. data-type="application/javascript". **Also add a data-name attribute** that matches the name of the given app in your config, e.g. data-name="googleAnalytics"

Your example script would then look loke this:

`<script type='text/plain' data-type='application/javascript' data-name='YourAppNameHere'>alert('consent-given!')</script>`

Saludos

~sahib

**Comment by caioricciuti** [comment]
Thank you so much for the inputs!
@sahib-afk, you're right, I was focused on the the contextual-consent part of the manual. Sorry about that! Mil gracias!
