### ISSUE TITLE
Domains for cookies on multilanguage website

### ISSUE THREAD

**Issue by gregBerthelot** [KIProtect/klaro#43]
Hi

Could you please show how we should handle Domains for cookies on multilanguage website
Should we add the cookie for each domain as following?
```
cookies : [
    ['__utma', '/', 'domain.fr'], ['__utma', '/', 'domain.com']
]
```

Thanks

**Comment by adewes** [comment]
Hi @gregBerthelot, yes in principle that should work. You can of course generate a specific config for each language that you then pass to Klaro, but if you know all domains in advance it might be easier just listing them all.

**Comment by gregBerthelot** [comment]
Thanks @adewes
