### ISSUE TITLE
No custom styling possible?

### ISSUE THREAD

**Issue by pouipouidesign** [KIProtect/klaro#45]
I've applied the data attribute for a custom class but the required class is only applied to the little notice box at the bottom of the window, not the big modal. Which means it still has the old class, and also loads all the styles, which I can't overload without using !important which I'd really like to avoid... I can't give access to my dev environment but here's how I call the script:
`<script defer type="application/javascript" src="/assets/js/klaro/klaro.js" data-config="klaroConfig" data-style-prefix="rs"></script>`
Thanks for your help!

**Comment by adewes** [comment]
Thanks for your question! The style prefixing works by adding the specified style (`rs` in your case) to the outer `div` element of Klaro. Like that, you can overwrite specific styles using your CSS by putting them inside the given prefix namespace, e.g. like this (SCSS):

```
.rs {
  .cm-modal {
      background: black;
   }
}
```

That should allow you to replace styles without using `!important` as the prefixed styles will have higher specificity and will therefore have preference.

**Comment by adewes** [comment]
Hm that’s weird indeed, which version are you on? I’ll try to reproduce this, normally the modal divs should be inside the klaro div.

Von unterwegs gesendet

**Comment by pouipouidesign** [comment]
Thanks, I feel a bit less like a klutz ^^
I've downloaded the file linked on the demo page (https://klaro.kiprotect.com/klaro.js announced as 2.0.4 apparently?)... should I have not?

**Comment by pouipouidesign** [comment]
Thanks, it's perfect this way! 👍 
Should I close, or let you close, this issue?

**Comment by adewes** [comment]
Great, glad to hear it's fixed :)
