### ISSUE TITLE
Opt-in script loaded on slider click

### ISSUE THREAD

**Issue by gregBerthelot** [KIProtect/klaro#52]
Hi

seems that opt-in scripts are loaded when enable apps (click the corresponding slider) and not when clicking on Save button from the cookies manager.

Step to reproduce:
- Open https://klaro.kiprotect.com/
- Open dev tools > application tab to see cookies
- Click on Reset Consent (yellow button)
- Disable all apps and save
- Refresh page
- Open manager (green button)
- Enable all apps from Toggle all slider

This result by loading scripts and write cookies without the need to save!

Regards
Greg

**Comment by Leimi** [comment]
This happens for every app you toggle after saving the preferences for the first time. It is due to [this](https://github.com/KIProtect/klaro/blob/master/src/components/apps.js#L41-L42). Indeed it seems kinda weird to do this right away and not only when saving.

**Comment by jaller94** [comment]
As far as I can see the issue has been resolved with the listed PRs.
