### ISSUE TITLE
Add a CI integration for continous testing

### ISSUE THREAD

**Issue by DanielRuf** [KIProtect/klaro#53]
Currently there is no active CI and there is only an old GitLab CI config: https://github.com/KIProtect/klaro/blob/master/.gitlab-ci.yml

**Comment by adewes** [comment]
We have a CI on Gitlab (not public) that we use to build and deploy Klaro. We can of course set up Travis for the project, what exactly would you expect from it though?

**Comment by adewes** [comment]
We have a CI on Gitlab (not public) that we use to build and deploy Klaro. We can of course set up Travis for the project, what exactly would you expect from it though?

**Comment by DanielRuf** [comment]
It should run all tests but I see there are no unit tests or at least some testscript to see if builds are breaking in some way.

**Comment by adewes** [comment]
Yes currently we don't have tests, it's on our roadmap though. If you want to contribute some testing or CI setup we'd be very happy of course!

**Comment by jaller94** [comment]
I will try to connect GitLab CI for GitHub to it.
https://about.gitlab.com/solutions/github/

As all of our projects use GitLab CI and its an open source runner, I think that sticking with Gitlab CI and integrating it with Github will serve the most benefits to all parties.
