### ISSUE TITLE
Make Cookie-Domain and Path configurable

### ISSUE THREAD

**Issue by comede** [kiprotect/klaro#63]
I would like to use the same consentmanager on several subdomains (www.foo, shop.foo) and share the settings. Would it be possible to make the cookie-domain of the klaro-cookie itself (cc-klaro) configurable?

`    klaroConfig = {
        elementID: 'cc-klaro',
        cookieName: 'cc-klaro',
        cookieExpiresAfterDays: 365,
        cookieDomain: '.foo',
        cookiePath: '/',
...
 `

**Comment by david-soyez** [comment]
For people who needs it, you can look at my quick fork.

**Comment by leonexcc** [comment]
The cookieDomain seems to be configurable. Would it be also able to change the cookiePath? The mentioned fork also only adds the cookieDomain-Setting.
