### ISSUE TITLE
Does not work with requirejs

### ISSUE THREAD

**Issue by comede** [kiprotect/klaro#64]
- When loaded via script-tag klaro.js will not be executed at all when requirejs is in use
- When loaded via requirejs, klaro.js does not work (document.currentscript is null).

**Comment by jaller94** [comment]
A minimalist demo repository would help people without knowledge of requirejs to reproduce issue and experiment with solutions.

**Comment by rkantos** [comment]
I haven't experimented with requirejs directly, but it seems that when working with say Dojo, which uses requireJS as the 'Dojo Loader' since Dojo v1.7, Klaro (Chrome??) occasionally fails to load dojo.js before it is needed and then fails to the first 'require' definition of Dojo with `ReferenceError: require is not defined`

This is how I am loading Klaro and Dojo:
```
<script data-dojo-config="async:1" type="opt-in" data-type="text/javascript" data-name="dojotoolkit"
    data-src="//ajax.googleapis.com/ajax/libs/dojo/1.14.1/dojo/dojo.js"></script>
<link rel="stylesheet" type="text/css"
    href="//ajax.googleapis.com/ajax/libs/dojo/1.14.1/dijit/themes/tundra/tundra.css" />

<script defer type="text/javascript" src="scripts/config.js"></script>
<script defer type="text/javascript" src="scripts/klaro.js"></script>
```
https://dojotoolkit.org/reference-guide/1.10/loader/amd.html

**Comment by ExecutiveCodingProducer** [comment]
I have a similar problem as @comede is reporting. In my case it is not working with YUI (version 2.9.0).

Whether Klaro is loaded (via defer or withouth defer) before or after YUI is not changing the result.

In particular, all texts are replaced by "[object Object]" in the Klaro box.

**Comment by adewes** [comment]
This should work now with the new NPM releases.

**Comment by fritzmg** [comment]
I am in the same boat: I am trying to include the `dist/klar.js` in a Magento 2 instance - however it seems the script never executes. Presumably because requireJS is in use within Magento 2. Do I _have to_ load klaro as a requireJS module in this case?

**Comment by fritzmg** [comment]
For reference, this is what I ended up doing: https://github.com/kiprotect/klaro/issues/128#issuecomment-1199288848
