### ISSUE TITLE
'Â' character keeps appearing out of nowhere in 'consent modal description'

### ISSUE THREAD

**Issue by Genenenenaam** [KIProtect/klaro#66]
[gdpr-consent.zip](https://github.com/KIProtect/klaro/files/2855449/gdpr-consent.zip)
The consent modal description is rendering a weird character '**Â**' between the 'description' and the 'privacy policy'.

- Bug seems to take place in all default and custom defined languages

**config.js file**: (it does not matter if you set 'lang' and 'translations', bug keeps appearing)
<img width="724" alt="schermafbeelding 2019-02-12 om 11 59 27" src="https://user-images.githubusercontent.com/20650976/52630938-d3e1d480-2ebd-11e9-93ed-91cdc7747547.png">

Preview of the weird character in the modal:
![schermafbeelding 2019-02-12 om 12 02 32](https://user-images.githubusercontent.com/20650976/52631069-1efbe780-2ebe-11e9-941c-9748a9bdf5a7.png)

and in the document source:
![schermafbeelding 2019-02-12 om 12 04 25](https://user-images.githubusercontent.com/20650976/52631188-65e9dd00-2ebe-11e9-9dd2-1c4eba93c35f.png)

**Comment by Genenenenaam** [comment]
It's seems the character bug is in the minified js file:
https://klaro.kiprotect.com/klaro.js

`" Â "`

**Comment by adewes** [comment]
Did you check if it's maybe a problem with the encoding specified in your `script` tag loading Klaro, or the encoding specified for your HTML document? Can you try changing your script tag to this:

```
<script src="klaro.min.js" charset="UTF-8"></script>
```
Let me know if that fixes the problem! On our website (klaro.kiprotect.com) UTF characters seem to work fine (e.g. check the Romanian version of the dialogue), so I'm not sure what the issues arises from in your case.

**Comment by Genenenenaam** [comment]
If you search for the exact match `" Â "` in your [klaro.js](https://klaro.kiprotect.com/klaro.js) file. you will see this character standing as the only match. Deleting it seems to be the only way to get rid of it.

It seems to me that this character should not be there.

**Comment by Flothus** [comment]
Seems like the encoding of all special characters in the compiled klaro.js and the example config.js is wrong.

I grabbed the one from https://klaro.kiprotect.com/klaro.js and it's ok.

**Comment by buchdag** [comment]
https://klaro.kiprotect.com/klaro.js seems to have UTF-8 issues :

Here is the french translation part:

```javascript
function(e, t) {
  e.exports = {
    consentModal: {
      title: "Les informations que nous collectons",
      description: "Ici, vous pouvez voir et personnaliser les informations que nous collectons sur vous.\n",
      privacyPolicy: {
        name: "politique de confidentialitÃ©",
        text: "Pour en savoir plus, merci de lire notre {privacyPolicy}.\n"
      }
    },
    consentNotice: {
      changeDescription: "Des modifications ont eu lieu depuis votre derniÃ¨re visite, merci de mettre Ã  jour votre consentement.",
      description: "Nous collectons et traitons vos informations personnelles dans le but suivant : {purposes}.\n",
      learnMore: "En savoir plus"
    },
    ok: "OK",
    save: "Sauvegarder",
    decline: "Refuser",
    close: "Fermer",
    app: {
      disableAll: {
        title: "Changer toutes les options",
        description: "Utiliser ce bouton pour activer/dÃ©sactiver toutes les options"
      },
      optOut: {
        title: "(opt-out)",
        description: "Cette application est chargÃ©e par dÃ©faut (mais vous pouvez la dÃ©sactiver)"
      },
      required: {
        title: "(toujours requis)",
        description: "Cette application est toujours requise"
      },
      purposes: "Utilisations",
      purpose: "Utilisation"
    },
    poweredBy: "PropulsÃ© par Klaro!"
  }
}

```

`Ã©` should be `é` , `Ã¨` is `è`, etc

**Comment by adewes** [comment]
It might have been a problem with our server headers @buchdag, I just added an explicit "utf-8" encoding header. Can you please try to download the file again (possibly resetting your browser cache before doing so) and let me know if the problem is now solved?

**Comment by buchdag** [comment]
@adewes yup, that seem to have solved it 👍

**Comment by adewes** [comment]
Awesome, glad we could fix this issue!
