### ISSUE TITLE
Exclude default css (option)

### ISSUE THREAD

**Issue by Genenenenaam** [kiprotect/klaro#68]
Is there an option to exclude the default css? (style tag rendered in the document head).
Would be nice to do this by setting `data-style-prefix` on the script tag, or by setting an option in the config file?

**Comment by jaller94** [comment]
Are you asking for a way to restyle the interface or to avoid side effects on other parts of the embedding website?
Would the usage of Shadow DOM solve your problem?
CSS inside a Shadow DOM node not affect styles in any parent node. It localizes the rules.

**Comment by Genenenenaam** [comment]
A way to restyle the interface.

I don't mind keeping the classes, but it would be nice to exclude the css that gets added in the document head. It would be nice if this was an option in the config file:

`css: false`

**Comment by jmartsch** [comment]
@Genenenenaam Can you please close this issue? It is resolved now. There is an option to use klaro without the default styling.
