### ISSUE TITLE
Clarify if / how Klaro works with Google Tag Manager

### ISSUE THREAD

**Issue by programmdesign** [KIProtect/klaro#7]
Currently, form the docs it is unclear if Klaro will also work using Google Tag Manager. Some explanation or even an example would be great.

**Comment by programmdesign** [comment]
Hi @adewes. Thanks for clarification. That was clear in the docs. However, most pages require Tag Manger to load other tags. Google Tag Manger is not critical and can or even should be loaded. I was more wondering about the scripts that the tag manager loads asynchronously into the page. E.g. if I have a Google Analytics Tags, a Facebook Pixel etc., they will be loaded by the Tag Manager either always or under certain conditions on the fly into the page. For customer Tags (= Scripts) on Google Tag Manager, I can probably also add the > type="opt-in", but e.g. Google Analytics is supported natively by Google Tag Manger and you can't adjust the code of the Tag/Script. Other solutions just set a cookie or local storage entry that sets "ga_cookie" to "false". I can then read this value in Google Tag Manager and it will not load the Google Analytics tag if this value is false. Maybe worth quickly installing Tag Manager for one script to see what I mean.

**Comment by adewes** [comment]
As discussed OTR this functionality can be implemented using the `callback` functions. @programmdesign 
 if you end up using this and have time please feel free to add an example page showing how to deal with Google Tag Mananger, as it will be relevant to other people as well (you can also simply add an explanation to this issue).

Closing this for now, please feel free to reopen if you think the problem hasn't been properly addressed or if you have any additional questions.

**Comment by nicomollet** [comment]
I am interested in this too. Klaro a really nice solution, but I too have many "Tags" in GTM that don't have the possibility to add a special `type` to the script.

**Comment by ThomasKujawa** [comment]
@programmdesign / @nicomollet Did you solve the problem?

@adewes Did I understand that right?

Do I have to replace the placeholder with the following code?

1.)
gtmDependency
==>
GoogleAnalytics

// tell GTM to disable this particular app by setting a cookie or localStorage value...
==>
setcookie("cc_analytics","no",time()+(3600*24*365));

// enable this app / do nothing
==>
setcookie("cc_analytics","yes",time()+(3600*24*365));

2.)
gtmDependency
==>
FacebookPixel

// tell GTM to disable this particular app by setting a cookie or localStorage value...
==>
setcookie("cc_social","no",time()+(3600*24*365));

// enable this app / do nothing
==>
setcookie("cc_social","yes",time()+(3600*24*365));

**Comment by moabi** [comment]
Do not forget to add the data-type="application/javascript" in order for it to work properly

    `
    <script type="opt-in" data-name="gtm" data-type="application/javascript">(function(w,d,s,l,i) 
    {w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-XXXXXX);</script>
    `

**Comment by ThomasKujawa** [comment]
@moabi Thank you very much. That was the solution to my problem!
