### ISSUE TITLE
Grouped cookies (in modal)

### ISSUE THREAD

**Issue by TheMangoTrain** [kiprotect/klaro#74]
In the cookie settings modal, is it possible to show the cookies in groups (by purpose) rather than a list of individual items?

Take a look at the Klaro demo...

1 - Visit https://klaro.kiprotect.com
2 - Click "Show Manager" (the green button)

There's many cookies (apps) listed, each with an individual control and lots of information.
However it's a flurry of data, with no high-level organization ie grouped categories. There's prominence given to brand labels, however users may or may not be familiar with the brands. Perhaps the most important information in the moment, "purpose", is a smaller font in dim grey and at the bottom of each item.

Do we expect users to sit and think about each individual app (or cookie)?

I think we're lucky that the user has decided to review their cookie settings. They are now actively engaged with the website experience. They should be rewarded with a pleasant experience, not a jarring storm of data.

So perhaps broad cookie groups and controls...

"Essential cookies" (greyed out, no choice)
"Analytics cookies"
"Advertising cookies"
"Miscellaneous cookies"
etc

And for more details, they simply look into each group where individual cookies could still be rendered with dense information and specific controls. Whether these child items are visible right away without having to open a group, I think it's determined case-by-case (how many cookies you have, etc).

Many major consent managers seem to do this UX already.

Some examples:
https://kinsta.com
https://www.onetrust.com

**Comment by fred-mevia** [comment]
Yes please could you propose a solution in order to make grouped cookies ? Thanks!

**Comment by adewes** [comment]
Hey @fred-mevia , @TheMangoTrain and everyone eles, this is finally done and pushed! You can enable grouped consents by settings `groupByPurpose : true` in your config file, no other changes required. More documentation is forthcoming, please check out our new docs as well (https://kiprotect.com/docs/klaro) and let me know what you think!
