### ISSUE TITLE
Always display "X" icon in top-right, to close modal

### ISSUE THREAD

**Issue by TheMangoTrain** [KIProtect/klaro#75]
An "X" icon appears in the top-right of the modal on mobile, however on desktop I don't see this icon as it has a `hide` class applied to it. Is there a configuration option for this?

I'm using the following CSS to override:
```
.klaro .cookie-modal .cm-modal .hide {
  display: block !important;
}
```
It works, however the original code already uses `!important`. So now there's `!important` overriding `!important`. Somehow this feels dirty?

**Comment by jaller94** [comment]
I don't see the "X" icon on mobile.
Can you point me to the code in the repo?

![A screenshot of the Klaro modal on a mobile resolution. It does not have an X button to close it.](https://user-images.githubusercontent.com/10872136/62477662-bb39e380-b7a9-11e9-938e-0aa0682e71cb.png)

**Comment by TheMangoTrain** [comment]
Apologies, double-checking it does not appear on mobile either. I'm using the CSS override for all cases (desktop and mobile).

FYI, this is in reference to the CPC modal (not the banner notice).

Basically, ideally the "X" for close should be an option when a modal is rendered. Perhaps some end-users know enough to click a dimmed-out background, but not all.

**Comment by Henning-IG** [comment]
I think "hide" is not a good class name. I cannot see where this button gets hidden by Klaro and "hide" is used i.e. by Bootstrap to hide elements.

**Comment by adewes** [comment]
Seems fixed.
