### ISSUE TITLE
Updating to webpack 4

### ISSUE THREAD

**Issue by BhaveshSGupta** [KIProtect/klaro#80]
Hello,

I am thinking that we should update current version to weback 4? Do you support the idea.

**Comment by jaller94** [comment]
Yes, we started upgrading various projects to Webpack 4 this week and this will follow.
I can't say when, bu it may be this month.
Feel free to open a PR, if you get Klaro working with Webpack 4. 👍

**Comment by BhaveshSGupta** [comment]
@jaller94, I am new to react and webpack and I can open a pull request can you help me along?

**Comment by jaller94** [comment]
Yeah, on Monday I can provide you with a before-after-webpack config that I migrated last week.
It's mainly renaming keys in the `webpack.config.js` file, removing plugins they bundled and setting the key `mode` to `'production'` or `'development'`.
I can also review PRs during the week, if they make deliberate, small changes.

As your interest in the project seems to grow, I want to point out the possibility of a fork.
The [Empreinte Digitale built an accessible version](https://github.com/empreinte-digitale/orejime#readme) which is an awesome project! I hope to find the time to learn and replicate most of their advancements.
I'll see what I can contribute and review, though the current amount of issues and discussions is way over my capacity for Klaro.
