### ISSUE TITLE
Separate css and js bundle

### ISSUE THREAD

**Issue by BhaveshSGupta** [KIProtect/klaro#81]
Helo, 

Should we make css and js bundle into two files so that it becomes easy to configure/style whole app.

**Comment by BhaveshSGupta** [comment]
@jaller94, 
I can work on this if this is required.

**Comment by jaller94** [comment]
This is related to #68 where a website admin wants to restyle the Klaro modal.
I would like to split the CSS and JavaScript via webpack.

**Comment by BhaveshSGupta** [comment]
@jaller94, It would always be separate build right, we won't use any flag or would we?

**Comment by jaller94** [comment]
Yes, let's always separate it. A combined bundle may be a feature wish for later, but for now it sounds like unnecessary complexity.

**Comment by davidhellmann** [comment]
That's like shit sorry. But the CSS inside the JS is really uncool. can't overwrite the CSS cause the inline css was pushed before the closing `head` tag but my css comes in front of that. And set all to `!important` is not a solution. Why not just a Setting to disable the css at all??

**Comment by jaller94** [comment]
@davidhellmann I ask you not to use crude language. Your "[...] sorry" doesn't undo that. Please edit your post.

Yes, it's definitely a feature we would like to see. Does anyone know a similar library and thinks that Klaro should handle CSS like this?
Anyone may also fork Klaro and develop this feature on their own. If they come up with a good solution, we would the happy to receive a Pull Request.

**Comment by davidhellmann** [comment]
@jaller94 you're right. Sorry!

**Comment by jmartsch** [comment]
I already did this and separated the script and the scss. Should be easy to make a PR for this. I see if I find time the next days.

**Comment by adewes** [comment]
Great, thanks @jmartsch !
