### ISSUE TITLE
Understanding dist/configs/i18n.js better

### ISSUE THREAD

**Issue by BhaveshSGupta** [kiprotect/klaro#82]
Hello,

Currently we can update translations from main config file then what is use of this file dist/configs/i18n.js Can you please explain. Sorry I am trying to understand project better.

**Comment by jaller94** [comment]
The folder `dist` stands for distribution. These are generated files for usage in other projects.
With [`npm run-script make`](https://github.com/KIProtect/klaro/blob/daeb4bc7dfe5bb75715b4bca8650cb47fea02fcc/package.json#L19) webpack will build a version.
Webpack is configured to use `./dist` as the output folder.
https://github.com/KIProtect/klaro/blob/daeb4bc7dfe5bb75715b4bca8650cb47fea02fcc/webpack.config.js#L4

If you want to change the project as a developer, change files in `src` and build a version.
If you want to use klaro on your website, use the files in `dist`.

A release on NPM would likely only include the files in `dist` for others to include it in their projects.

**Comment by BhaveshSGupta** [comment]
Hello @jaller94,
Thank you for you reply,
What I am trying to say is,
in config file https://github.com/KIProtect/klaro/blob/daeb4bc7dfe5bb75715b4bca8650cb47fea02fcc/dist/config.js#L47 we have translation, then do we need to include configs/i18n.js  in our html.  https://github.com/KIProtect/klaro/blob/daeb4bc7dfe5bb75715b4bca8650cb47fea02fcc/dist/index.html#L15  Won't translation would get managed through config file only https://github.com/KIProtect/klaro/blob/daeb4bc7dfe5bb75715b4bca8650cb47fea02fcc/dist/index.html#L14

**Comment by jaller94** [comment]
Oh right, `./dist/configs/i18n.js` is just an example of how to overwrite the bundled translations.

https://github.com/KIProtect/klaro/blob/daeb4bc7dfe5bb75715b4bca8650cb47fea02fcc/dist/config.js#L45-L47

**Comment by BhaveshSGupta** [comment]
@jaller94, means we can overwrite default translations through main config file also.

**Comment by jaller94** [comment]
Looks like you're right and it is simply another way of overriding the translations. 👍
