### ISSUE TITLE
Callback doesn't work

### ISSUE THREAD

**Issue by ThomasKujawa** [KIProtect/klaro#83]
After I solved the integration with the Google Tag Manager (see Issue #7 ), the callback function is no longer executed.

our site familienfreunde.de

Can anyone help me?

config.js => https://pastebin.com/6Xjk3bVs
klaro.js => https://pastebin.com/W4C9qhPF (without changes)

**Comment by BhaveshSGupta** [comment]
It works fine for we can you try this in codepen or something similar.

**Comment by jaller94** [comment]
@ThomasKujawa The pastebin links expired. Would you mind setting up a minimal repo or send a gist?

**Comment by jaller94** [comment]
A minimal repo where the issue can be reproduced would be awesome. I am still trying to reproduce this and sadly don't have much time for the project.
My last post is meant to allow others to investigate this, because you shared a private repo with me that others are not able to access.

**Comment by ThomasKujawa** [comment]
config.js

var createCookie = function(name, value, days) {
    var expires;
    if (days) {
        var date = new Date();
        date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
        expires = "; expires=" + date.toGMTString();
    }
    else {
        expires = "";
    }
    document.cookie = name + "=" + value + expires + "; path=/";
}

var klaroConfig = {
    elementID: 'klaro',
    cookieName: 'klaro',
    cookieExpiresAfterDays: 365,
    privacyPolicy: 'https://www.familienfreunde.de/blog/datenschutzerklaerung/',
    default: true,
    mustConsent: true,
    lang: 'de',
    translations: {
        de: {
            close: 'speichern',
            consentModal: {
                description:
                    'Hier können Sie einsehen und anpassen, welche Information wir über Sie sammeln.',
            },
            gadsense: {
                description: 'Anzeigen von Werbeanzeigen',
            },
            ganalytics: {
                description: 'Sammeln von Besucherstatistiken',
            },
            onesignal: {
                description: 'Benachrichtigung über Neuigkeiten im Browser',
            },
            purposes: {
                analytics: 'Besucher-Statistiken',
                security: 'Sicherheit',
                livechat: 'Live Chat',
                advertising: 'Anzeigen von Werbung',
                styling: 'Styling',
                social: 'Soziales (Netzwerken)',
            },
        },
    },

    // This is a list of third-party apps that Klaro will manage for you.
    apps: [
        {
            name: 'ganalytics',
            default: true,
            title: 'Google Analytics',
            purposes: ['analytics'],
                callback : function(state, app){
                 if(state === false)
                    { createCookie("cc_analytics_google","no","365");}
                     else
                    { createCookie("cc_analytics_google","yes","365");}                                               
                                               },
            required: false,
            optOut: false,
            onlyOnce: true,
        },
        {
            name: 'gadsense',
            default: true,
            title: 'Google Adsense',
            purposes: ['advertising'],
                callback : function(state, app){
                 if(state === false)
                    // tell GTM to disable this particular app by setting a cookie or localStorage value...
                    { createCookie("cc_advertising_google","no","365");}
                     else
                   // enable this app / do nothing
                    { createCookie("cc_advertising_google","yes","365");} 
                                               },
            required: false,
            optOut: false,
            onlyOnce: true,
        },
        {
            name: 'onesignal',
            default: true,
            title: 'OneSignal',
            purposes: ['social'],
                callback : function(state, app){
                 if(state === false)
                    // tell GTM to disable this particular app by setting a cookie or localStorage value...
                    { createCookie("cc_social_onesignal","no","365");}
                     else
                   // enable this app / do nothing
                    { createCookie("cc_social_onesignal","yes","365");} 
                                               },
            required: false,
            optOut: false,
            onlyOnce: true,
        },
    ],
};

**Comment by jaller94** [comment]
I tried your config and the callback get executed.
- When the page got loaded, all callbacks are called with the state `false`.
- When the "Save"/"speichern" button is clicked, the callbacks of apps which changed gets called.

![klaro-callbacks](https://user-images.githubusercontent.com/10872136/66752965-ff74ee80-ee92-11e9-868b-661e5e345cc7.gif)


Off topic: @ThomasKujawa, did you know that GitHub's Markdown supports [Code and Syntax Highlighting](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)?
That makes code look nice while preserving line breaks and white spaces.

**Comment by ThomasKujawa** [comment]
Thank you @jaller94 !

How can I tell the script that the page should be reloaded when it is saved?

sorry for the unreadable code. I was online on my cell phone.

**Comment by jaller94** [comment]
... While this is likely bad for the users' experience, JavaScript has
[`window.location.reload()`](https://developer.mozilla.org/en-US/docs/Web/API/Location/reload) and [`window.location.assign('https://developer.mozilla.org/');`](https://developer.mozilla.org/en-US/docs/Web/API/Location/assign)
