### ISSUE TITLE
Required apps not working as expected: can be disabled and not loading by default. 

### ISSUE THREAD

**Issue by bacanu** [KIProtect/klaro#86]
Expected behaviour:

If an app is configured as required, it should execute without consent, the same as if it was optOut
If an app is configured as required, clicking "decline" shouldn't set the app to false in the klaro config.

Example gist: https://gist.github.com/bacanu/e153615f9185f4a89b7bf1ff41d86dd2

If this behaviour is intended, you can close this issue.
If not, I have a patch and can make a PR.

Thank you.

**Comment by jaller94** [comment]
As by its definition a required app shouldn't get blocked by a user interaction.

https://github.com/KIProtect/klaro/blob/fbb80c10d7f3c5de84652e955ccea845c092f790/dist/config.js#L225-L227

Please send your patch our way so we can review it.
Thanks for catching this.
