### ISSUE TITLE
Let users turn off each cookie individually in privacy statement

### ISSUE THREAD

**Issue by programmdesign** [KIProtect/klaro#9]
Like here, but again sub-organized in sections (see #8) and per service. 

<img width="507" alt="screenshot 2018-05-29 18 10 06" src="https://user-images.githubusercontent.com/4633284/40671224-95faaba6-636b-11e8-90dc-68d70120437d.png">

**Comment by adewes** [comment]
That's a great feature and in fact Klaro already does that :) If you turn off an app for which the `cookies` variable was defined, Klaro will remove all matching cookies from the website (you can test this e.g. on our landing page with Firefox [works on Chrome too but its developer tab does not always display current cookie values correctly]). 

Klaro can't unset `HTTP-Only` cookies of course, if you use those you should implement a custom `callback` handler for an app, which can then e.g. call an API endpoint on your server that clears cookies for a given app (there's nothing we can do here on our site unfortunately).

**Comment by programmdesign** [comment]
Thanks. Does Klaro also render those buttons for each cookie in the list or just one global on/off button?

**Comment by adewes** [comment]
Klaro doesn't specifically manage cookies but apps, where a single app can have many cookies which Klaro will then set or unset. I think it doesn't make much sense to enable/disable cookies individually, you could still do it though by creating a separate `app` entry for each cookie.
Closing this for now, please feel free to reopen if you think this wasn't properly addressed or if you have additional questions.
