### ISSUE TITLE
"Toggle all apps" sets all properties to false

### ISSUE THREAD

**Issue by ExtSol** [KIProtect/klaro#92]
I noticed an anomaly: if you switch off "Toggle all apps", the "cloudflare" property in the cookie will have the 'false' value, but Cloudflare has the "always required" property.

**Comment by jaller94** [comment]
`toggleAll` calls `toggle` on each app and then [`manager.updateConsent`](https://github.com/KIProtect/klaro/blob/dbd17df0eb4a04811c452d81fb43f521eb1cd09f/src/consent-manager.js#L73-L76) with the value. None of them seem to check if the app is required.

A check like that has been added to `declineAll` which may be used for inspiration.

I think the test should be performed in `updateConsent` (and would then also become obsolete in `declineAll`).

Thanks for bringing this up.

**Comment by ExtSol** [comment]
Modifying the **[toggle](https://github.com/KIProtect/klaro/blob/1afbe442b4ceca74594e05670311d8eb59814c21/src/components/apps.js#L37-L41)** is the simplest way to solve the problem.
```javascript
const toggle = (apps, value) => {
    apps.map((app)=>{
        if  (!app.required) {
            manager.updateConsent(app.name, value)
        }
    })
}
```

Changing the [updateConsent](https://github.com/KIProtect/klaro/blob/dbd17df0eb4a04811c452d81fb43f521eb1cd09f/src/consent-manager.js#L73-L76) function according to the method described in [declineAll](https://github.com/KIProtect/klaro/blob/1afbe442b4ceca74594e05670311d8eb59814c21/src/consent-manager.js#L63-L71) is not an optimal way, because it means you go through the "**_apps_**" object too many times.

**Comment by jaller94** [comment]
It would only be one more function call per object and `app.updateConsent()` shouldn't allow false when being tested by unit tests (once there are any).

**Comment by TomerPacific** [comment]
@ExtSol , still need help solving this issue?

**Comment by ExtSol** [comment]
@TomerPacific , what solution do you have to solve this problem?

**Comment by TomerPacific** [comment]
@ExtSol , it seemed to me like the solution proposed in an earlier comment is one that you are seeking.

**Comment by QJan84** [comment]
Cloudflare has the property "always required" and should also be "true" if you click Decline. Right? Currently, cloudfare is set to false if I decline. At least this would be a good option for mandatory cookies.

**Comment by jaller94** [comment]
Correct, the property `required` is being honored, even when "Decline" is clicked.
If you have found a case where Klaro disabled an app with `required: true`, please open an issue describing your config.
