### ISSUE TITLE
Cannot run NPM scripts on Windows

### ISSUE THREAD

**Issue by jaller94** [KIProtect/klaro#95]
https://github.com/KIProtect/klaro/blob/102956b28d9ac30f565bc3c5c8f9ed6af16c2ca6/package.json#L16-L19

Environment variables are set differently on Windows, making our NPM scripts fail on non-Unix system.

**Comment by jaller94** [comment]
Fixed by #85.
@BhaveshSGupta, please let us know, if anything breaks for you.
We would love to keep this project cross platform compatible, especially with [Hacktoberfest](https://hacktoberfest.digitalocean.com/) coming up.

**Comment by ExtSol** [comment]
To run under Windows OS, we have modified the lines in "scripts" with:
"scripts": {
    "make-dev": "SET APP_ENV=dev && SET APP_DEV_MODE=server && npx webpack-dev-server --config webpack.config.js --history-api-fallback",
    "make-watch": "SET APP_ENV=dev && SET APP_DEV_MODE=watch && npx webpack --watch --config webpack.config.js",
    "make": "SET APP_ENV=production && SET APP_VERSION='1.2.3' && SET APP_COMMIT='xyz' && npx webpack --config webpack.config.js"
  }

It worked for me!
![windows](https://user-images.githubusercontent.com/5376500/65496733-ad5b3180-dec1-11e9-93b8-b51a7fd0b9a6.gif)

**Comment by jaller94** [comment]
A new release, which should allow you to run the scripts without modifications, is on its way.

**Comment by vvscode** [comment]
I can plug crossenv (common approach for such cases). @jaller94  Should I make a PR?

**Comment by jaller94** [comment]
https://github.com/KIProtect/klaro/issues/95#issuecomment-534444745
