### ISSUE TITLE
Klaro stop working once using monaco-editor

### ISSUE THREAD

**Issue by kaichaosun** [KIProtect/klaro#97]
## How to reproduce
1. Clone this repo: https://github.com/kaichaosun/rustacean-journey
2. Install [docsify](https://docsify.js.org/#/quickstart): `npm i docsify-cli -g`
3. Start server: `docsify serve docs`, go to http://localhost:3000 check the page
4. Modify **index.html** by commenting this line:
`<script type="text/javascript" src="//unpkg.com/monaco-editor@0.15.6/min/vs/loader.js"></script>`, check the page again, the consent manager should pop up in right corner.

**Comment by ohana54** [comment]
Monaco loader puts an AMD loader on the global scope, making the klaro script think that it's in an AMD environment - thus not executing immediately.
I'm not sure what's the best correct solution for this is, but one option is to add `defer` to the monaco loader script, as the browser guarantees order of execution for deferred scripts.

**Comment by kaichaosun** [comment]
I already use this workaround as a temporary solution, still worth to have a more graceful solution.

**Comment by ohana54** [comment]
Klaro offers the option to build the script yourself. You can clone the reop, change the webpack config's `libraryTarget` to `amd-require` and build the project.
I don't have other ideas, we can wait for the maintainers to weigh in :)
